### ISSUE TITLE
More recalbox.conf switches ideas

### ISSUE THREAD

**Issue by nekomania** [digitalLumberjack/recalbox-os#101]
Arcade cabinet usually don’t have labels on their buttons, I don’t want my guests accidentally pressed button X to launch kodi..
## Launch kodi by X Button
;kodi_by_xbutton=1

This switch will be useful if one might want to stay in an old version for a reason.
## Disable update autocheck at startup
;disable_update_check=1

**Comment by Energizing** [comment]
maybe resolution switching can be added in there? or it's impossible?

**Comment by digitalLumberjack** [comment]
Yeah it will be.

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-emulationstation/commit/b9ea87ec9ac2ec4ba8c98cd49c9c7d9ba86a08d2
https://github.com/digitalLumberjack/recalbox-buildroot/commit/f1eb7adfafa3dda20e1e6c6f27b4620422de4ea3
https://github.com/digitalLumberjack/recalbox-buildroot/commit/6b61b7fda9b9f2d4511224ff72c7f2f847268283
