### ISSUE TITLE
PC-Engine/TurboGrafx artwork and folder name consistency

### ISSUE THREAD

**Issue by nekomania** [digitalLumberjack/recalbox-os#102]
Since the rom share folder is called pcengine, why don’t we use the correct artwork in emulationstation to reduce user confusion?

In /root/.emulationstation/themes/simplesvgs/pcengine/art/pce.svg 
switch from tg_16.svg to pce.svg for background and logo

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/4e9fe1d5a04e08e84f88755aaf5115b76e70ee7a
