### ISSUE TITLE
Share folder for xbmc

### ISSUE THREAD

**Issue by nekomania** [digitalLumberjack/recalbox-os#103]
Provide an easy way for the users to transfer media files, just like the same way we transfer roms.

Path suggestions?
share/roms/xbmc/video
share/roms/xbmc/music
share/roms/xbmc/pictures

**Comment by Yamakaky** [comment]
Why not simply share/{videos,music,pictures} ?

**Comment by eldoncoy** [comment]
Et mettre un serveur SFTP afin de pouvoir voir tout le contenu ? et donc modifié divers fichiers de conf de Kodi

**Comment by Yamakaky** [comment]
BTW, how is it shared actually ? There is a tuto for windows, but I couldn't find any mention of the techno for linux. Samba, nfs, other ?

**Comment by digitalLumberjack** [comment]
@eldoncoy nope déja qu'il y a pas mal de soucis avec samba, les erreurs du au protocole, les erreurs de déplacement ou de suppression, je ne vais pas mettre un sftp avec acces sur /, sinon je sens que ca va fuser sur le forum...

@Yamakaky Samba. For power user ssh will do everything you want.

**Comment by eldoncoy** [comment]
je comprend tout a fait

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/fdb21a88746a5029449758eb75f2e2086ec4095c

**Comment by agenttank** [comment]
can you add a share to the kodi path as well? userdata for example for easy insert of advancedsettings.xml and easy backup...

**Comment by nicolashenry** [comment]
Est-ce que c'est possible de changer le type de la partition "/recalbox/share" (vers ext4 par exemple) ? Car le format FAT32 est limité à 4go il me semble, ce qui peut être embêtant pour regarder des vidéos de 5go ou plus.

**Comment by Yamakaky** [comment]
+1, c'est vraiment chiant quand ça arrive ^^ Il me semble que ça ne change rien pour samba ?

**Comment by digitalLumberjack** [comment]
Oui la partition share est en fat32, a la base parcequ'elle devrait etre lisible depuis windows. Mais ce superbe OS ne permet lit pas les partitions logiques sur la partition étendue, en tout cas crées par noobs... 
Pour ce qui est de passer la partition en ext4, je ne peux pas le faire. Ca causerait beaucoup trop de soucis pour les mises à jour, entre ceux qui ont déjà une install en fat32 et les nouveaux avec un ext4...

**Comment by nicolashenry** [comment]
Ça ne serait pas possible de faire en sorte que la partition soit en ext4 seulement pour les nouvelles installations ? Ou sinon rajouter "mkfs.ext4" pour pouvoir faire soi-même la conversion ?
