### ISSUE TITLE
N64 emulator not working

### ISSUE THREAD

**Issue by Ranashenka** [digitalLumberjack/recalbox-os#105]
Hello,

First thanks a lot for your work, it is really magnificent!:)

But I have a problem with the N64 emulator, it does not work...
I have downloaded several N64 games (zelda, mario, etc..) and when i start the game the screen goes black and nothing. 
After maybe 5 sec it goes back to the emulator screen were you can chose your game. And it does that for all the N64 games. 
All the other emulators are working perfectly.

[EDIT] I'm using the RPI2

**Comment by digitalLumberjack** [comment]
Rpi 1 doesn't support n64

**Comment by Ranashenka** [comment]
I'm using the RPI2

**Comment by C-Fu** [comment]
same here with me, on RPi2 it doesn't work. I thought it was just me

I'm updating right now, see if it works.

**Comment by digitalLumberjack** [comment]
Ok. I'll check that.

**Comment by Ranashenka** [comment]
I have the lastet update (done yesterday night) and still the same problem.

**Comment by Energizing** [comment]
the only game i copied (mario kart 64) is still working for me

**Comment by hackgrid** [comment]
I have the same problem on RPI2, only Mario Kart works, games like Zelda get stuck on a black boot screen, Mario 64 just exists to the main menu. Maybe its an compatiblity thing?

**Comment by niekverw** [comment]
+1, on RPI2 n64 doesn't work with 3.2.8/3.2.9 update

**Comment by Ranashenka** [comment]
I did some tests, and found out that Mario kart works, but in 1/4 screen with some horrible lags, and all the rest of the games do not work.
I'v tried to download from several web sites (the rom could be broken) and it's always the same problem.
From what i have seen, it looks more like a bad config in the emulator.. But that is were my knowledge stops.. :(

**Comment by Raulval82** [comment]
I have Mario kart, Mario 64, Lylatwars and Mortal kombat trilogy working well with 3.2.9 beta 2. I will update it to final version today... Lets see what happens... My roms are from theoldcomputer.

**Comment by digitalLumberjack** [comment]
Closing that one, after the job of @rockaddicted on rice plugin. We cannot do better for now
