### ISSUE TITLE
Zoid Theme ES 2.x

### ISSUE THREAD

**Issue by mgoulartBR** [digitalLumberjack/recalbox-os#107]
Hi again,

Is it possible to install this theme on the next version?
http://blog.petrockblock.com/forums/topic/theme-zoid/

**Comment by digitalLumberjack** [comment]
Hi !
Themes looks good but i would have to edit each theme.xml file adding the bg sound of the system, and remove unecessary jpg and png files in orderto avoid to add 60 mo to the installer :)

**Comment by digitalLumberjack** [comment]
If someone has the courage :)

**Comment by mgoulartBR** [comment]
If I try it you can test it?

**Comment by mgoulartBR** [comment]
Could you send me any theme.xml file to see how I put the parameter to bg
sound?

**Comment by digitalLumberjack** [comment]
Hi,
you can see an example at https://github.com/digitalLumberjack/recalbox-buildroot/tree/recalbox/board/recalbox/fsoverlay/root/.emulationstation/themes/simplesvgs/snes 
Go one directory back to get the list of themes. Many themes are not used, base yourself on https://github.com/digitalLumberjack/recalbox-buildroot/blob/recalbox/board/recalbox/fsoverlay/root/.emulationstation/es_systems.cfg to see what themes you must adapt (just add thoses themes pleaz :))
Can you work directly on a fork and create a pull request ?
For the recalbox branch, not recalbox-rpi2, i'll merge.

**Comment by mgoulartBR** [comment]
I will try to do it today!!!

**Comment by mgoulartBR** [comment]
Lumberjack,

Just fork recalbox-os branch and create a pull?

**Comment by mgoulartBR** [comment]
I'm afraid to do any s*** and break your repository!
Could I send the files by another way?

Sorry!

**Comment by digitalLumberjack** [comment]
you can clone recalbox-buildroot (branch recalbox), then add your theme in board/recalbox/fsoverlay/root/.emulationstation/themes/
Don't worry i'll double check the pull request

**Comment by digitalLumberjack** [comment]
@mgoulartBR any news ? ;)

**Comment by mgoulartBR** [comment]
Struggling to push files to the fork that I made. I will try to read
another tutorial!

On Tue, Mar 17, 2015 at 4:21 AM, digitalLumberjack <notifications@github.com

**Comment by digitalLumberjack** [comment]
Send me a zip file if want :)

Le mar. 17 mars 2015 à 11:18, mgoulartBR <notifications@github.com> a
écrit :

**Comment by mgoulartBR** [comment]
I would like to bring more themes to recalboxOS. Is it something that you would like to see on future releases?

**Comment by digitalLumberjack** [comment]
Yes of course we would appreciate this Marcelo

Le jeu. 19 mars 2015 à 01:18, mgoulartBR <notifications@github.com> a
écrit :

**Comment by digitalLumberjack** [comment]
I'm working on your theme today ;) 3.3.0 will be a nice release

**Comment by digitalLumberjack** [comment]
Isn't this issue already closed ?

**Comment by spriggan59** [comment]
the theme works.
very nice
