### ISSUE TITLE
No network, but network working in NOOBS

### ISSUE THREAD

**Issue by C-Fu** [digitalLumberjack/recalbox-os#110]
History:
1. plugged into my office network via LAN cable and a few secs after, "Update Available" dialog pops up.
2. Proceed to update (most likely from my current 3.2.4 to 3.2.5 at that time). Update failed, and system rebooted.
3. Tried again, same. Tried a few times, same.
4. Turned off/on, and now no network. But if I hold Shift during boot to enter NOOBS and click Online Help, I get to browse the internet.

Entering CLI and typing ifconfig doesn't show anything, just another command line input.

**Comment by digitalLumberjack** [comment]
Hi,
can you tell me your current version (menu -> system settings)

**Comment by C-Fu** [comment]
As I said, version is 3.2.4.

I could just format the sd card, install 3.2.7. Problem is I have many roms already transferred to the 64GB card, and it would take quite a while to transfer back the roms (small problem) and scrape again one by one (big problem). Honestly, I don't mind copying the roms & scraping again. But just want to inform you of this problem, and any possible solution.

**Comment by digitalLumberjack** [comment]
Yes i understand :)
The real issue is that if the system made an half update and broke the network, you're stuck.
Can you connect https://github.com/digitalLumberjack/recalbox-os/wiki/Root-access-on-terminal-%28EN%29 and give me the result of `ifconfig -a` please ?

**Comment by C-Fu** [comment]
This is from NOOBS terminal
![58h9som](https://cloud.githubusercontent.com/assets/6426597/6524113/331e2314-c431-11e4-968b-5ab2c2b5b224.jpg)

And this is from RecalboxOS terminal
![xbpseoc](https://cloud.githubusercontent.com/assets/6426597/6524022/3f23cdb8-c430-11e4-9a77-f372417b0d45.jpg)

I attach my usb wifi (even if I know it doesn't work on 3.2.4 :laughing:

**Comment by digitalLumberjack** [comment]
`ifdown eth0` 
`ifup eth0`
What does ifup do ? 
Sending discover… ?

**Comment by C-Fu** [comment]
ifdown: ignoring unknown interface eth0
ifup eth0: interface eth0 already configured
ping google.com
ping: bad address 'google.com'
ping 127.0.0.1
ping: sendto: Network is unreachable

**Comment by digitalLumberjack** [comment]
/etc/network/interfaces ?

**Comment by C-Fu** [comment]
sh: /etc/network/interfaces: Permission denied. I thought I'm root? Hmm.

**Comment by digitalLumberjack** [comment]
just cat it :)

**Comment by C-Fu** [comment]
It's empty! I thought I did something wrong for a while :laughing:

**Comment by digitalLumberjack** [comment]
ok that' why.
So, here it is http://archive2.recalbox.com/recalbox/root/etc/network/interfaces
Just `cd /etc/network && wget http://archive2.recalbox.com/recalbox/root/etc/network/interfaces`

**Comment by C-Fu** [comment]
I can't wget, because of no network but no problem, I can retype. Network works, and I tried to update.... and update failed again. Tried a 2nd time, and still the same problem. Rebooted, and now interfaces is empty again.

If there is a log that I can get, I'll gladly find it and post it here.

**Comment by digitalLumberjack** [comment]
Lol yes wget won't work.

**Comment by digitalLumberjack** [comment]
yes the update log is in /root/update.log

**Comment by C-Fu** [comment]
update.log is empty. Ok I'll try inserting the interfaces content again, and update. Update error, system will reboot. before clicking OK and reboot I force close emulationstation and go to terminal and check the log.... still empty. update.done content is "v3.2.4"

I guess it's much easier to just simply format everything and start 3.2.7 fresh :laughing: thanks for the help though!

**Comment by digitalLumberjack** [comment]
Just to be sure try to execute : /recalbox/scripts/rsync-update/rsync-update.sh
