### ISSUE TITLE
Add cifs support for network mount

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#115]

**Comment by Yamakaky** [comment]
cifs == smb, no ?

**Comment by agenttank** [comment]
yes

**Comment by digitalLumberjack** [comment]
Yes it now works : mount -t cifs //mafreebox.freebox.fr/Disque\ dur/Vidéos  /media/usb6 -o user=freebox,password=password,uid=1000,gid=1000,rw
