### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by Yamakaky** [digitalLumberjack/recalbox-os#121]
It doesn't seem to be enabled. It should be, I don't know why so many people seems to disable it. Example of it's usefullness : you plug your computer to the raspberry pi using ethernet, then you simply ssh to it using its fe80::... local address (you should see it using `ip -6 neigh`). No DHCP server needed.

**Comment by digitalLumberjack** [comment]
Hi, I didn't disabled it, I just didn't enabled it. I will.

**Comment by Yamakaky** [comment]
Cool. I wasn't talking about you specifically.

**Comment by digitalLumberjack** [comment]
Yep I know ;)

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/1581d26466a0a88487b50553c787ab16bfbb2686
