### ISSUE TITLE
recalbox share using samba

### ISSUE THREAD

**Issue by Yamakaky** [digitalLumberjack/recalbox-os#123]
On the wiki, there is only a mention about windows. HOWTO on linux (via terminal) : 
- in /etc/nsswitch.conf : add `wins` at the end on the "hosts:" line.
- in /etc/fstab : add this line : 
`    //RECALBOX/share /mnt/recalbox cifs _netdev,noauto,user,username=root 0 0`
- create the `/mnt/recalbox` directory.

You can then mount the share partition as a user : `$ mount /mnt/recalbox`

**Comment by NerosTie** [comment]
You can access the recalbox by typing: `smb://local_ip_of_your_recalbox` in Dolphin or Nautilus.

**Comment by Yamakaky** [comment]
I don't have a file manager ^^
If you modify nsswitch.conf, I think you could even type `smb://RECALBOX`. BTW, isn't the shares listed automatically by nautilus, like for windows ?

**Comment by NerosTie** [comment]
> I don't have a file manager ^^

You can use FileZilla.

> BTW, isn't the shares listed automatically by nautilus, like for windows ?

Yes, normally, but the recalbox wasn't. I don't know why :/

**Comment by Yamakaky** [comment]
why use filezilla when I can use `mount` ?

**Comment by digitalLumberjack** [comment]
Hi,
thanks i put it in the how-to : https://github.com/digitalLumberjack/recalbox-os/wiki/Mini-How-To-(EN)
