### ISSUE TITLE
timestamp in logfile /root/controllers.log & complete in english

### ISSUE THREAD

**Issue by hstampfl** [digitalLumberjack/recalbox-os#129]
# tail -10 controllers.log
     manette usb detectée  
     Current Bluetooth master: 00:1a:7d:da:71:14
     Setting master bd_addr to 00:1a:7d:da:71:14
     No controller found on USB busses.
     manette usb detectée
     Current Bluetooth master: 00:1a:7d:da:71:14
     Setting master bd_addr to 00:1a:7d:da:71:14 
     manette usb detectée
     Current Bluetooth master: 00:1a:7d:da:71:14
     Setting master bd_addr to 00:1a:7d:da:71:14

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/d68c82f8775c0173c2aa6c9df09b0797c86704f9
