### ISSUE TITLE
timestamp in logfile /root/recalbox.log

### ISSUE THREAD

**Issue by hstampfl** [digitalLumberjack/recalbox-os#130]
---- recalbox-config.sh ----
     loading module mk_arcade_joystick_rpi args = map=1
     systemsetting.sh - searching for enable_kodi     
     systemsetting.sh - searching for kodi_at_start
     systemsetting.sh - searching for language
     systemsetting.sh - searching for kb_layout
     essetting.sh - searching for Lang
     setting keyboard layout to en
     essetting.sh - searching for Lang
     starting emulationstation with lang = en_US
     Starting emulationstation with command :
     HOME=/root LANG="en_US.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation
---- recalbox-config.sh ----

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/d68c82f8775c0173c2aa6c9df09b0797c86704f9
