### ISSUE TITLE
timestamp in logfile /root/generateconfig.log

### ISSUE THREAD

**Issue by hstampfl** [digitalLumberjack/recalbox-os#131]
# tail -10 generateconfig.log
             I have for player 3 : index=-1 for joystick DEFAULTDONOTFINDMEINCOMMAND
             I have for player 4 : index=-1 for joystick DEFAULTDONOTFINDMEINCOMMAND
     writing given config for player 1
     Finishing config
     So it will be default configuration for player 2
     pad 1 is free , writing in config
     So it will be default configuration for player 3
     pad 2 is free , writing in config
     So it will be default configuration for player 4
     pad 3 is free , writing in config

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/d68c82f8775c0173c2aa6c9df09b0797c86704f9
