### ISSUE TITLE
Add mgd extension for SNES

### ISSUE THREAD

**Issue by skitoo** [digitalLumberjack/recalbox-os#132]
Can you add .mgd extension for SNES system ? 

Thank you

**Comment by digitalLumberjack** [comment]
Why do they complicate things like that :P

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/ac33d6a9d661d63b385c36f180942b3e4a8ae7ef

**Comment by skitoo** [comment]
Indeed ! :)

Thank you

**Comment by polux400** [comment]
Hello, in 4.0.0 beta 2, .mgd are still refused for SuperNes for me ?

**Comment by rockaddicted** [comment]
Weird, .mgd files are presents in ES https://github.com/recalbox/recalbox-buildroot/blob/rb-4.0.X/board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_systems.cfg#L7
