### ISSUE TITLE
`git submodule` for releases

### ISSUE THREAD

**Issue by Yamakaky** [digitalLumberjack/recalbox-os#133]
Currently, there isn't a simple way to relate a release with it's source code. I suggest that in this repo you use `git submodule` to aggregate the others repos. With each release, you could then update this repo to point towards the commits you use for the build. recalbox-os/master could then be used to rebuild the latest release.

**Comment by digitalLumberjack** [comment]
That's a good idea. I'll learn how to do that i never used submodules ;)

**Comment by Yamakaky** [comment]
See http://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by Yamakaky** [comment]
tl;dr :
init :  
```
git submodule add <url>
git commit -m 'Add submodules'
```
update : 
```
cd <submodule>
git checkout <commit>
cd ..
git add <submodule>
git commit -m 'Merge submodules for 1.2.3'
git tag -a -m 'Release 1.2.3'
```

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-os/commit/a3ebf3793cf324bd208684236e692d25e05964a0
