### ISSUE TITLE
Add an IRC channel for Recalbox

### ISSUE THREAD

**Issue by skitoo** [digitalLumberjack/recalbox-os#134]
It's a proposal: I think it would be good to create a chan IRC.
Maybe on Freenode ?

**Comment by digitalLumberjack** [comment]
Yes that could be good, but the issue with irc is that you do not create knowledge like you can do on a forum. Discussions are transient. We could do a test and see :)

**Comment by digitalLumberjack** [comment]
#recalbox@freenode.net

**Comment by digitalLumberjack** [comment]
Need to change the website according to that.

**Comment by Energizing** [comment]
what happened?

**Comment by digitalLumberjack** [comment]
Reopened
