### ISSUE TITLE
add custom ratio option to frontend menu

### ISSUE THREAD

**Issue by Energizing** [digitalLumberjack/recalbox-os#136]
for people having problems with 4/3 and 16/9 or getting pixels cropped

**Comment by digitalLumberjack** [comment]
Corrected in 3.2.8, you can try to redownload the beta on the forums

**Comment by Energizing** [comment]
working great but is there a way to put piFBA with the same custom ratio? or is there a retroarch core for it so that it launches with retroarch settings?

**Comment by digitalLumberjack** [comment]
for now pifba accept only a switch in the configuration that stretch the image.
If you have a rpi2, libretro fba core is coming soon.
