### ISSUE TITLE
config.txt doesn't work on 1366x768

### ISSUE THREAD

**Issue by C-Fu** [digitalLumberjack/recalbox-os#137]
I believe there are a few settings in config.txt that's causing the issue.

In 3.2.7, there are a few settings that "clashes" against each other:

disable_overscan=1
disable_overscan=0
avoid_safe_mode=1
config_hdmi_boost=0
hdmi_force_hotplug=0
hdmi_force_hotplug=1
config_hdmi_boost=4

when I comment on everything except 
hdmi_force_hotplug=1
config_hdmi_boost=4

It works on my 1366x768. Note that on my 1080p lcd monitor default setting works.

**Comment by digitalLumberjack** [comment]
Yes i know, it's because noobs add some info on installation, i have overridden them by adding mine.

The first one is taken in account.

**Comment by digitalLumberjack** [comment]
Are you in hdmi or dvi ?
Sometimes the only thing to comment is hdmi_drive=2.

**Comment by digitalLumberjack** [comment]
As it worked on my TV with the same resolution, and as it is a noob issue, i'll close this one.
