### ISSUE TITLE
Kodi issues with 3.2.7

### ISSUE THREAD

**Issue by C-Fu** [digitalLumberjack/recalbox-os#139]
IPTV Simple + IsraeLIVE doesn't work. Here's my log, truncated to show just errors:

00:00:31 T:1950876512 WARNING: JSONRPC: Could not parse type "PVR.Details.Channel"
00:00:31 T:1950876512 WARNING: JSONRPC: Could not parse type "PVR.Details.ChannelGroup.Extended"
00:00:31 T:1950876512 WARNING: JSONRPC: Could not parse type "GUI.Property.Value"
00:00:31 T:1950876512 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
.
.
00:00:32 T:1950876512   ERROR: JSONRPC Server: Failed to connect to sdpd
.
.
00:00:34 T:1801585680  NOTICE: -->Python Interpreter Initialized<--
00:00:34 T:1556083728   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                              File "/usr/lib/python2.7/threading.py", line 763, in run
                                              File "/root/.kodi/addons/script.module.axel.downloader/lib/axelproxy.py", line 579, in start_proxy_internal
                                                httpd = server_class((host_name, port), myhandler)
                                              File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
                                              File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
                                              File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
                                              File "/usr/lib/python2.7/socket.py", line 224, in meth
                                            error: [Errno 99] Cannot assign requested address
.
.
08:36:32 T:1801585680  NOTICE: Thread BackgroundLoader start, auto delete: false
08:36:32 T:1801585680 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-poster.jpg
08:36:32 T:1801585680 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-poster.png
08:36:32 T:1801585680 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-banner.jpg
08:36:32 T:1801585680 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-banner.png
08:36:32 T:1801585680 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-fanart.jpg
08:36:32 T:1801585680 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/fanart.jpg
08:36:32 T:1495528464   ERROR: GetDirectory - Error getting /root/.kodi/userdata/addon_data/plugin.video.genesis/TVShows/
08:36:32 T:1801585680 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-fanart.png
08:36:32 T:1801585680 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/fanart.png
08:36:34 T:1793197072   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/plugin.video.israelive/service.py", line 4, in <module>
                                                repoCheck.UpdateRepo()
                                              File "/root/.kodi/addons/plugin.video.israelive/repoCheck.py", line 22, in UpdateRepo
                                                urllib.urlretrieve(url, packageFile)
                                              File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
                                              File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
                                              File "/usr/lib/python2.7/urllib.py", line 213, in open
                                              File "/usr/lib/python2.7/urllib.py", line 443, in open_https
                                              File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
                                              File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
                                              File "/usr/lib/python2.7/httplib.py", line 812, in send
                                              File "/usr/lib/python2.7/httplib.py", line 1212, in connect
                                              File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
                                              File "/usr/lib/python2.7/ssl.py", line 566, in __init__
                                              File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
                                            IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
                                            -->End of Python script error report<--
08:36:40 T:1793197072  NOTICE: Thread LanguageInvoker start, auto delete: false
08:36:40 T:1793197072  NOTICE: -->Python Interpreter Initialized<--
08:36:41 T:1793197072  NOTICE: [Errno 2] No such file or directory: u'/root/.kodi/userdata/addon_data/plugin.video.israelive/remoteSettings.txt'
08:36:47 T:1793197072  NOTICE: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
08:36:47 T:1793197072  NOTICE: [Errno 2] No such file or directory: u'/root/.kodi/userdata/addon_data/plugin.video.israelive/remoteSettings.txt'
08:36:47 T:1950876512   ERROR: GetDirectory - Error getting plugin://plugin.video.israelive/
08:36:47 T:1950876512   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.israelive/) failed
08:36:47 T:1793197072  NOTICE: Thread BackgroundLoader start, auto delete: false
08:36:47 T:1793197072 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-poster.jpg
08:36:47 T:1793197072 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-poster.png
08:36:47 T:1793197072 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-banner.jpg
08:36:47 T:1793197072 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-banner.png
08:36:47 T:1793197072 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-fanart.jpg
08:36:47 T:1793197072 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/fanart.jpg
08:36:47 T:1793197072 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-fanart.png
08:36:47 T:1793197072 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/fanart.png

Also, if I try to play from Youtube, and then exit, recalbox would exit Kodi, and hangs at Main Menu.
Full kodi.log: http://pastebin.com/94X0naVw

Kodi.log after playing youtube, exit, and hangs:  http://pastebin.com/LBwJx9Zu

**Comment by mrpollif** [comment]
Is this a restored backup from another Kodi/xbmc installation or were all components and dependencies installed specifically for this version of Kodi? ...It reminds me of issues I had restoring a backup of an older version of xbmc on a newer version of Kodi. ...either way, you may be better off raising the question on Kodi or Navi-x forums etc as this will need expert Kodi knowledge whereas the main expertise here is Recalbox itself, emulstation and the emulators that come with it.

**Comment by digitalLumberjack** [comment]
Hi, someone has the same issue as you (or was it you). The thing is 
`[Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed `
ssl cannot verify the certificate. But ssl works with other modules as youtube etc. 
So what could be different with this one...

**Comment by C-Fu** [comment]
mrpollif, my kodi setup for every recalboxos version is fresh.
reason I posted the issue here is I want to highlight the issue to digitalLumberjack himself, much like how me and others highlight the issue that PVR function wasn't working on recalbox before. At least to me, I would like recalbox to grow to be kinda like a one-stop centre for total emulation gaming & media consumption. 
Anyway just a brief info on how IsraeLIVE video addon work:

1. Run addon for the first time -> IsraeLIVE initializes (something), and asks to restart Kodi
2. Run addon for the 2nd time, and wait < 1 min -> IsraeLIVE asks to allow it to auto-update IPTV Simple with updated channels list, EPG, and channel icons every few hours
3. Live TV & Radio + EPG + Channel icons work

BTW, I can confirm that copying israeLIVE & IPTV Simple's .m3u & EPG data into recalbox's Kodi IPTV Simple settings work. Just a guess, maybe this issue has something to do with uninstalled Kodi package with Recalbox-OS.

**Comment by digitalLumberjack** [comment]
Hi, very weird as everything works except this plugin. I will check the options for python ssl.

**Comment by C-Fu** [comment]
Happy to announce that IsraeLIVE is working on 3.2.9! :dancers: appreciate it very much!!

**Comment by digitalLumberjack** [comment]
Nice !
