### ISSUE TITLE
Joypad configured but not working when launching games using shell script.

### ISSUE THREAD

**Issue by mrpollif** [digitalLumberjack/recalbox-os#141]
Although the joypad and games worked when launched in emulationstation (es), using the game launch script (together with %rom% and "system name" parameters) results in the games being launched correctly but the joypad is not responding.

I was wondering if es does any additional, initial, joypad or input related configuration before games are run - for example, is es updating a temporary retroarch config file with keycode information etc. that the shell script then references when games are launched. I would like to replicate this process outside of es.

For background information, I am setting up advanced launcher add-on in kodi so that I can use that as a games front-end rather than using es. This will work much better in my living room, my wife and kids as they already use Kodi for tv and movies. I will publish a mini-howto on the Recalbox website once I get it working.

**Comment by digitalLumberjack** [comment]
Hi,
the script you're looking for is located at /recalbox/scripts/generateEmuConfigs/generateEmuConfigs.sh

Looking forward to see the howto :)

**Comment by digitalLumberjack** [comment]
I was thinking the script takes many arguments the you won't have in kodi...

**Comment by digitalLumberjack** [comment]
But if you launched a game once, the retroarch configuration will be present, so it should work without calling generateEmuConfigs.sh

**Comment by mrpollif** [comment]
Thank you. I will look further into it. I may be doing something stupid! :-)

**Comment by digitalLumberjack** [comment]
No your laucnher will work, but you'll have to play a game at least one time (just one time not at every boot) from emulationstation before switching to kodi. Then the emulatorLauncher.sh will launch a game with the correct retroarch config.
You just have to launch a game for all retroarch emulators, and one from fba. Then you will have the configurated controlelrs and can launch directly from emulatorLauncher.

**Comment by mrpollif** [comment]
Thanks for checking. Will this also be so if I boot directly into Kodi?

**Comment by digitalLumberjack** [comment]
Yes the files are persistent, just rewritten on game launch

**Comment by mrpollif** [comment]
I double checked everything again and still can not determine why this is not working.

Although all emulators launch ok from Kodi (using launcher script), the joystick does not respond as it does when the emulator is launched via emulationstation.

I have run jstest via ssh for device js0 and it is found there ok. I have also disabled the autodetect option and hardcoded the joystick keys in the retroarch configuration file. I am beginning to wonder if I might need to do something in udev (or such) to get the input working when the launcher script is launched from something other than emulationstation.

Any thoughts on this?

**Comment by digitalLumberjack** [comment]
Could kodi have blocked the js event file? During the game,  try a jstest
and see if it respond

**Comment by mrpollif** [comment]
I will try this tonight. I also found the following which may be worth looking into:

https://steamcommunity.com/app/221410/discussions/0/864959809809029907/?l=french

I will let you know how I get on.

**Comment by mrpollif** [comment]
Checked last night. jstest via ssh works fine whether kodi is running or not. Also tried it in the background when a game launched via Kodi was running. Was fine then too (even though I could not control the game with the joypad). Also tried giving input 666 permissions in udev. That did not do anything.

I don't know if it could be something environmental that EmulationStation configures/sets before the script can be run which I have not replicated in my Kodi/AdvancedLauncher setup. Will try direct retroarch commands tonight. Will let you know how I get on.
