### ISSUE TITLE
Add catsfc and snes9x-next in recalbox.conf emulator choices

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#143]

**Comment by frthery** [comment]
Hi, do you plan to integrate gpsp libretro core ? Or it is already integrated ?

It works very well before some last changes.

**Comment by digitalLumberjack** [comment]
Hi, it's already the gpsp libretro core that runs gba games.

**Comment by frthery** [comment]
Nice, so you use a build made before 1 Feb ? 

Since this change: https://github.com/libretro/gpsp/commit/fb984fcaeffe8fd99c801738d4b238f1e99e131c
There is some sounds issues, and poor performances :/

**Comment by digitalLumberjack** [comment]
Yep check that : https://github.com/digitalLumberjack/recalbox-buildroot/blob/recalbox/package/libretro-gpsp/libretro-gpsp-0001-enabledynarec.patch i just reenabled it.

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/fd201772b6f8124bee1a8e198e397952c1340726

**Comment by frthery** [comment]
Thanks, i have commented this problem on libretro repository https://github.com/libretro/gpsp/issues/11
