### ISSUE TITLE
Bug : xbox 360 wireless controller flashing lights

### ISSUE THREAD

**Issue by RomainOdeval** [digitalLumberjack/recalbox-os#145]
Well, you can see the title : when i used a XBox 360 Wireless controller, it works fine (thanks v3.2.8) but saw an annoying bug.
The lights of controller flashing, like if is not connected (it is and works, indeed).
You can't know which controller is (if you have controller 1, 2 ...)

I searched a little and found this. Maybe a solution ?
http://www.libregeek.org/2014/01/26/fix-fixing-xbox-360-flashing-lights-xpad-kernel-driver/

**Comment by RomainOdeval** [comment]
Or maybe this, too.
http://www.webupd8.org/2014/04/get-xbox-gamepads-properly-configured.html

**Comment by digitalLumberjack** [comment]
You can enable the xboxdrv in recalbox.conf https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf-%28EN%29 that is recommended for xbox controllers.
Not enabled by default as it create devices even if no controller is connected.

**Comment by rockaddicted** [comment]
Hello, did you activate the xboxdrv driver's support? You can enable the option by modifying the file `/share/system/recalbox.conf` Look the wiki for more informations : https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf-%28EN%29

**Comment by rockaddicted** [comment]
mdr pas assez rapide

**Comment by digitalLumberjack** [comment]
:)

**Comment by RomainOdeval** [comment]
Oh ... ok ... sorry for this.
I ckecked that this at lunchtime.
