### ISSUE TITLE
Compatiblité du clavier iClever ?

### ISSUE THREAD

**Issue by eldoncoy** [digitalLumberjack/recalbox-os#146]
Est ce que ce clavier (iClever) est compatible avec la recalbox ? (avec ou sans modif de votre part)
S'il ne l'est pas, est ce que cela le pourra être dans une futur version ?
Une personne a testé ?

http://www.amazon.fr/iclever%C2%AERii-fran%C3%A7aise-compatible-lithium-ion-rechargeable/dp/B008JBSTUA/ref=sr_1_1?s=computers&ie=UTF8&qid=1425981843&sr=1-1&keywords=iClever 

---------

Is this keyboard ( iClever ) is compatible with recalbox ? (with or without mod on your part)
If it is not, it is what it will be in a future version?
Someone has tested ?

**Comment by eldoncoy** [comment]
J'ai craqué, je l'ai acheté, je vous tiens au courant car je connais pas le modèle du dongle
On verra bien :)
Au pire, il me servira pour autre chose lol

**Comment by digitalLumberjack** [comment]
Il devrait fonctionner t'inquiete pas, cependant il y a toujours un bug qui
pose problème dans emulationstation avec tous les claviers.

**Comment by eldoncoy** [comment]
c'est surtout pour kodi :) c galere la recherche à la télécommande
la manette suffit pour emulationstation. même si je galère légèrement pour les boutons suivant les consoles, mais bon, pas encore mis dedans correctement par manque de temps

Rien à voir, j'arrive pas à mettre kodi au démarrage, j'ai bien enlevé le ; dans le recalbox.conf et mis à 1 et testé aussi à 0 mais cela n'a pas fonctionné, j'ai loupé un truc ?

**Comment by digitalLumberjack** [comment]
Non tu n'as rien loupé, ca l'as fait a plusieurs personnes, je ne sais pas
pourquoi il ne le prend pas en compte...

**Comment by eldoncoy** [comment]
Pour info, depuis le partage samba sous windows, tout le fichier de conf est à la suite, j'ai remis tous les # et ; à la ligne et cela n'a rien changé également.
Tu peux me filer le chemin pour le modif en ssh, je testerais ce soir

**Comment by digitalLumberjack** [comment]
/recalbox/share/system

**Comment by eldoncoy** [comment]
Le fichier vue en ssh, avait plein de caractère ^M sur presque chaque fin de ligne
Je pense que cela est du à la modif via le partage SAMBA sous Windows
Modif effectué en SSH, Kodi se lance bien au démarrage. Cool

Je tiens au courant demain pour le clavier :)

**Comment by eldoncoy** [comment]
Clavier. Fonctionnel. C top :)

**Comment by digitalLumberjack** [comment]
Cool nikel :)
