### ISSUE TITLE
createRecalboxOS.sh

### ISSUE THREAD

**Issue by MarcoBorrini** [digitalLumberjack/recalbox-os#15]
On Ubuntu 14.10 64but, simply executing the script for me appears the "make menuconfig" menu with a  default x86 configuration... Is it possible to execute a "make recalbox-rpi2_defconfig" before "make"?

ps
obviously doing everything manually... everything works like a charm!

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-os/releases/download/v3.2.1/createRecalboxOS.sh

**Comment by digitalLumberjack** [comment]
I corrected your issue and added the checkout to the corresponding branch of recalbox-rescue

Thanks for the feedback, tell me if it's ok, i'll let you close this issue when you managed to build the system.

**Comment by MarcoBorrini** [comment]
I'll let you know when I'll finish to watch my extended Lords of the Ring trilogy!

**Comment by digitalLumberjack** [comment]
:D

Le Thu Feb 19 2015 at 15:21:19, MarcoBorrini <notifications@github.com> a
écrit :

**Comment by MarcoBorrini** [comment]
Everything seems to be ok, I only need to find a not faulty card. TY very much!
