### ISSUE TITLE
Kodi not booting on 3.2.8

### ISSUE THREAD

**Issue by Rubenvd** [digitalLumberjack/recalbox-os#150]
When booting kodi, I get the startup screen for a very short time, and then it shut down.
I went to look for the log files, and found this in /root/.kodi/temp/kodi.log:

...
...
19:06:40 T:1951081312  NOTICE: Running database version Addons16
19:06:40 T:1951081312  NOTICE: Running database version ViewModes6
19:06:40 T:1951081312  NOTICE: Running database version Textures13
19:06:40 T:1951081312  NOTICE: Running database version MyMusic48
19:06:40 T:1951081312  NOTICE: Running database version MyVideos90
19:06:40 T:1951081312  NOTICE: Running database version TV26
19:06:40 T:1951081312   ERROR: SQL: SQL error or missing database
                                            Query: SELECT idVersion FROM version

This is the last entry in the log.
Also, I tried to boot kodi from commandline. First, got an error message that there is a library missing (libmysqlclient.so.16), but I found it in /usr/lib/mysql/...
So I copied the content of that folder to /usr/lib and again booted from command line. This time I just get a black screen, and when I stop the process I can see the error message:

terminate called after throwing an instance of 'dbiplus::DbErrors'
Aborted
Crash report available at /root/kodi_crashlog-19700101_010449.log

This crash report contains the same error as the one mentioned above (ERROR: SQL: SQL error or missing database)

**Comment by digitalLumberjack** [comment]
Super weird. Seems like your system is corrupt. Did it work on this same version ? Did you update ?

**Comment by digitalLumberjack** [comment]
Could you try to force an update : 
```
/recalbox/scripts/rsync-update/rsync-update.sh
```

**Comment by Rubenvd** [comment]
Thanks for your fast reaction.
I reinstalled the system, and didn't get the error anymore.
However, it did give some errors when I changed the Kodi skin to reFocus.
This I did not do when I previously had the error.
It would seem more of a Kodi or skin implementation failure, and not your fault/problem.
