### ISSUE TITLE
Can't mount any usb device

### ISSUE THREAD

**Issue by Raulval82** [digitalLumberjack/recalbox-os#151]
Hi! Im trying to follow the tutorial to have all roms in an external usb device, but mount command is not showing any usb device. I tryed with an 1Tb hdd in ext4 and fat32, and with some pendrives in fat and fat32. 

Any ideas?

EDIT: SOLVED with version 3.2.9 beta 2 fresh install. I have roms in an 1Tb ext4 hdd.

**Comment by digitalLumberjack** [comment]
Good ;)
