### ISSUE TITLE
xboxdrv - does not work with more than two controllers

### ISSUE THREAD

**Issue by hackgrid** [digitalLumberjack/recalbox-os#152]
hi,

i own 3 xbox controllers. this is my recallbox.conf

# ------------ D - XBOX Controllers ------------ #
## Disable this if you use ps3 controllers
enable_xbox_drv=1
## set the amount of controllers to use with xboxdrv
xboxdrv_nb_controls=3

Only 2 controllers get recognized by the system (also indicated by the LED) but the LED of the third controller just cycles endlessly and won't show up in the system. The controller is not the problem, if I change the order of "power uping" the controllers, another one does not work.

**Comment by NerosTie** [comment]
What happen if you restart?
What happen if you set `xboxdrv_nb_controls=1` and have 2 controllers?

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/40cca8488d562ec6c7dbde754c1687f2d1499dde

**Comment by hackgrid** [comment]
Great thanks, will try it soon!

**Comment by digitalLumberjack** [comment]
wait the 3.2.9-beta5

**Comment by hackgrid** [comment]
Works now, thank you very much!
