### ISSUE TITLE
xboxdrv - only the first controller works in the SNES emu

### ISSUE THREAD

**Issue by hackgrid** [digitalLumberjack/recalbox-os#153]
Hi,

only controller 1 works with the SNES emu, my controller 2 won't accept any input in the SNES emu. 
Works fine in the emulationstation menu.

**Comment by Energizing** [comment]
did you change default to #0 x360 controller for player 1 and #1 x360 controller for player 2 in the controller settings in emulationstation? is this on 3.2.8 or 3.2.9 beta?

**Comment by hackgrid** [comment]
Yes, i did configure controller #1 to xbox #0 and controller #2 to xbox #1

this is the current version 3.2.8

**Comment by Energizing** [comment]
rpi1 or 2? maybe it has been fixed in 3.2.9, try the beta if you have a spare sd card, gives you the possibility to change snes emulator too, lot of issues for 2 players in pocketsnes

**Comment by hackgrid** [comment]
I use a rpi2. Thanks I will try it

**Comment by Energizing** [comment]
i'd recommend snes9x-next as your snes emulator as catsfc seems to have multiplayer problems too

**Comment by hackgrid** [comment]
Okay, but two player games worked fine with one xbox controller (without xboxdrv) and another cable usb controller.

**Comment by digitalLumberjack** [comment]
What game are you testing ?
Can i have  : 
```
cat /recalbox/configs/retroarch/retroarchcustom.cfg
cat /recalbox/configs/retroarch/inputs/*
cat /root/generateconfig.log
cat /proc/bus/input/devices
```
All of that after you launched a game that doesn't work thanks.

**Comment by Energizing** [comment]
some games have problems with 2 players on pocketsnes, not all of them, but i don't think wireless + wired will change that bug, you just didnt come across one of those games i guess

**Comment by hackgrid** [comment]
I only tried Super Bomberman 5 yet. Worked with wirless+usb, did not work with 2 wireless controllers. (can't connect more than 2 wireless controllers because of the other bug I submitted. Will post the files later, thanks!

**Comment by digitalLumberjack** [comment]
Could you try street fighter 2 with the same configuration ?

**Comment by hackgrid** [comment]
Still the same problem with 3.2.9.
Your requested files:

http://pastebin.com/YPvWHRfQ

**Comment by hackgrid** [comment]
Street Fighter 2 works though, I am sorry, must be the emu then :-(

Tried snes9x, Super Bomberman 5 (original japanese [!] dump) freezes after selecting the game mode, SF2 works.

catsfc works, can't select 2 player mode for some reason, but pressing start while in 1 player mode works and I can control the second player.

Tricky stuff ;-)

**Comment by digitalLumberjack** [comment]
That's because of the 4 player mode.
So i'll close this one :)

**Comment by hackgrid** [comment]
Sorry, could you elaborate that? SB5 has no 4 player mode and snes9x should not freeze on start, it works on the desktop. Which version are you using?

**Comment by digitalLumberjack** [comment]
Super bomberman 5 has the multitap support for 5 player modo.
That what is bugging the controllers. I can't tell you more as i just know it bugs because i have had the same issue.

**Comment by hackgrid** [comment]
Ah okay, sorry, thought only 2 players were supported because I only entered "Normal Mode" but not Battle Mode. Thanks for pointing out!
