### ISSUE TITLE
Terrible sound output with Jack

### ISSUE THREAD

**Issue by NerosTie** [digitalLumberjack/recalbox-os#159]
The audio output with Jack is terrible, there is a lot of noise.
Tested with a Raspi B and a Raspi 2.
Maybe it's the Raspis' fault...

**Comment by agenttank** [comment]
i think it is the rpis fault. at least the rpi2 had this problem

**Comment by agenttank** [comment]
errrm rpi1

**Comment by NerosTie** [comment]
I have Raspi1 & Raspi2.
It's a really bad thing if it's rpis' fault :/

**Comment by frica** [comment]
It's the Pi's fault indeed, see http://www.crazy-audio.com/2014/07/sound-quality-of-the-raspberry-pi-b/
RPiB & RPi2 have the same audio component so having the last generation of Pi doesn't help. You can buy additional components called DAC to improve the sound quality.

**Comment by NerosTie** [comment]
Thank you @frica.
Well, nothing can be done!
