### ISSUE TITLE
GameGear Emulator

### ISSUE THREAD

**Issue by mgoulartBR** [digitalLumberjack/recalbox-os#16]
Hi again,

I think it's possible to emulate GameGear through Genesis-Plus-GX or Osmose. Is it possible to include it on next update?

**Comment by digitalLumberjack** [comment]
Yep possible. But game gear games are copy of master system ones. That's why it was not included yet. I'll put it in next release, one more system can only bee good for the recalbox :)

**Comment by digitalLumberjack** [comment]
Will be in 3.2.2, added by https://github.com/digitalLumberjack/recalbox-buildroot/commit/94086b6f436098bb0e07a63154120fce997a5647
