### ISSUE TITLE
Autoswitch Jack Hdmi

### ISSUE THREAD

**Issue by NerosTie** [digitalLumberjack/recalbox-os#160]
In EmulationStation, audio output is set on "Auto" but it doesn't work if I plug in a Jack.
An autoswitch could be a great thing!

**Comment by dem1980** [comment]
I am using Jack too.
I have no sound at RPI boot in emulationstation menu, then i go in a game, i have sound in game, i left the game and i have sound in emulationstation menu.
Could you try this please ?

**Comment by digitalLumberjack** [comment]
I don't think it's possible, as the auto mode on raspberry pi always uses the hdmi if present, and the jack if no hdmi is detected.
