### ISSUE TITLE
Add libretro-lutro

### ISSUE THREAD

**Issue by NerosTie** [digitalLumberjack/recalbox-os#161]
>Lutro is a new libretro core. It was started by enygmata one year ago. It embeds a lua interpreter and tries to be compatible with the love2d API.

>With this core, you can develop your own games for Lakka in Lua. Lua is a very easy programming language, so it lowers the barrier and let you focus on your game. And once your game runs on Lutro, you will be able to test it on the wide variety of platforms supported by RetroArch.

>This video shows a sample platformer game running on lutro in RetroArch:

>https://www.youtube.com/watch?v=n6eLX_GPXGg

>Lutro is still experimental and lacks ogg/vorbis support to play background music, but all the other features to develop a small retro games are there, and we provide some demo games to get you started on the libretro github page.

[source](http://www.lakka.tv/articles/2015/03/08/release-for-raspberry-pi-2-and-odroid-c1-and-more/)
[repo github](https://github.com/libretro/libretro-lutro)

**Comment by rockaddicted** [comment]
system added : https://github.com/rockaddicted/recalbox-buildroot/commit/1bcaa47240b865054f91f512764d0d7e6c8397f2
