### ISSUE TITLE
Doom (PrBoom or Crispy Doom)

### ISSUE THREAD

**Issue by mgoulartBR** [digitalLumberjack/recalbox-os#162]
Hi!

It will be awesome to play Doom on RecalboxOS. Is it possible to include PrBoom or Crispy Doom on RecalboxOS?

http://misapuntesde.com/post.php?id=531 (Crispy Doom)

**Comment by C-Fu** [comment]
+1, but I think those games (and others) need a lot of packages, which goes against the purpose of recalbox OS.

**Comment by Bluelightcrew** [comment]
+1 i miss the complete Ports sektion with Doom,Quake and Quake 3!!!

**Comment by Jace37** [comment]
adding these games will make recalbox-os way to havy.....

**Comment by rockaddicted** [comment]
PrBoom added : https://github.com/digitalLumberjack/recalbox-buildroot/commit/f8bef0da8f353c46a5109ba54c01d2ad36a54dd1

**Comment by rockaddicted** [comment]
Ok on RPI1 & RPI2.

**Comment by spriggan59** [comment]
works great 
doom 1 / doom 2 / plutonia / tnt
