### ISSUE TITLE
Please add Genesis plus GX.

### ISSUE THREAD

**Issue by slowmo310** [digitalLumberjack/recalbox-os#164]
It runs flawlessly on retropie with a pi2. It also has better compatibility and is more accurate.

**Comment by digitalLumberjack** [comment]
I'll add a switch in recalbox.conf as it is already compiled and used for some cores.

**Comment by spriggan59** [comment]
it's works add megadrive.core=genesisplusgx at recalbox.conf

**Comment by digitalLumberjack** [comment]
good
