### ISSUE TITLE
Kodi possibly missing crucial files?

### ISSUE THREAD

**Issue by lmacky** [digitalLumberjack/recalbox-os#17]
Hi
when trying to follow the tutorial for rasp pi from http://www.tvaddons.ag/ the install gives an error in kodi on your distro when I try to run it, unsure if im doing something wrong though?
Thanks 
Les

**Comment by C-Fu** [comment]
Yeah, a number of addons can be installed but doesn't work.

PVR function is missing, and I suspect package kodi-pvr-iptvsimple wasn't installed as well.

**Comment by digitalLumberjack** [comment]
OK I'll build the full package in next release :)

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/e9e5719583100d97f4e71775c01238a6ebe3867f
