### ISSUE TITLE
Mame aspect ratio confusion

### ISSUE THREAD

**Issue by mezzb** [digitalLumberjack/recalbox-os#170]
Most mame (even retroarch) default to getting the aspect ratio correct on rotated (3:4) games (classics from Donkey Kong, Space Invaders, Pac Man, and many new shmups).  The build in 3.2.8 always displays them stretched to 4:3.

I can individually set it per-session within the menu, but the default behavior should (I think) show the correct ratio.

**Comment by rockaddicted** [comment]
Tu veux conserver la table de ratio propre à certains jeux et mettre un réglage classique (comme les autres émus) pour les autres jeux? Ou bien virer également les ratios et mettre le même réglage de config que pour les autres émus?

**Comment by digitalLumberjack** [comment]
Je sais pas comment je vais faire. Je pense qu'il faut attendre que j'ai terminé le nouveau systeme de configuration des emulateurs.
