### ISSUE TITLE
add mednafen NeoGeo Pocket

### ISSUE THREAD

**Issue by Energizing** [digitalLumberjack/recalbox-os#172]

**Comment by RomainOdeval** [comment]
aaahhh .. Street of Rage ... ;)

**Comment by digitalLumberjack** [comment]
Would you find a good music, a nice background and the neo geo pocket logo in svg ?

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/tree/recalbox/board/recalbox/fsoverlay/root/.emulationstation/themes/simplesvgs/ngpc i see simple theme already contains the ngpc. I just need a good music ;)

**Comment by RomainOdeval** [comment]
This one ?

http://en.wikipedia.org/wiki/File:Streets_of_Rage_2_-_Go_Straight.ogg

**Comment by Energizing** [comment]
street of rage on NGP? aren't you thinking about Game Gear Romain? ahah

**Comment by RomainOdeval** [comment]
ah yes, sorry ... 
Well, Fatal Fury ? NGP well-known for fight games, no ?

**Comment by Energizing** [comment]
i was thinking about this one:

http://vgmrips.net/packs/vgm/SvC_MoTM/23%20-%2005%20Rumbling%20on%20the%20City.ogg

full OST here (downloadable as ogg) :

http://vgmrips.net/packs/pack/svc-motm

**Comment by Energizing** [comment]
or the bios music, but it's really short:

http://vgmrips.net/packs/pack/ngp-bios

**Comment by digitalLumberjack** [comment]
closed by rockaddicted thanks dude : https://github.com/digitalLumberjack/recalbox-buildroot/commit/961dc260dbd1ebe57001424e33fdeb97fb235006

**Comment by rockaddicted** [comment]
This core start on RPI1 B+ and RPI2, but the framerate is not full speed on RPI1 B+ overclocked in extrem mode.
