### ISSUE TITLE
Don't reset the hostname after update

### ISSUE THREAD

**Issue by dem1980** [digitalLumberjack/recalbox-os#173]
I have modify the hostname of the system and after the update, it is back to RECALBOX.

**Comment by hstampfl** [comment]
it's the way it goes today :( 
 there is no custom_recalbox.conf for holding settings which are not touched during upgarde ...

**Comment by hstampfl** [comment]
I hope this helps - to go a step forward to the custom configs ;)
https://github.com/digitalLumberjack/recalbox-buildroot/pull/11

Open: Hostname need to be added to the recalbox.conf.
