### ISSUE TITLE
Don't overwrite recalbox.config no more

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#178]

**Comment by eldoncoy** [comment]
C'est étrange
Le fichier recalbox.conf est revenu par défaut après la maj, ma config était Kodi au démarrage avant cette maj

Après la maj, le recalbox.conf commente la ligne pour kodi au démarrage (normal vu qu'il a était modifier par la maj), par contre Kodi se lance bien par défaut !!! je comprend pas :/

**Comment by digitalLumberjack** [comment]
oui c'est parceque si il n'est pas spécifié de ne pas le lancer dans recalbox.conf, il garde la dernière configuration connue.

**Comment by eldoncoy** [comment]
tout s'explique alors :)

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/8b8beca614d3f94280993a9ff46be97e82e8e151
