### ISSUE TITLE
"Nano" editor doesn't work under SSH

### ISSUE THREAD

**Issue by fmaida** [digitalLumberjack/recalbox-os#180]
Each time I try to use the Nano editor under SSH, I'm getting this error message:

```
# nano
Error opening terminal: xterm-256color.
```

Looking on the internet I found a way to make it work, by using these two commands:

```
export TERMINFO=/etc/terminfo
export TERM=linux
```

**Comment by NerosTie** [comment]
I can confirm. Using vi instead.

**Comment by agenttank** [comment]
nano is working on fresh install 3.2.9-beta2

**Comment by hstampfl** [comment]
nano is working on 3.2.10

**Comment by digitalLumberjack** [comment]
It's related to the ssh client terminal. Closed.

**Comment by NerosTie** [comment]
But, there is certainly a solution to fix this issue on the recalbox.
Not "closed" for me. I will try something on my free time.
