### ISSUE TITLE
Add Neo Geo as a separated emulator

### ISSUE THREAD

**Issue by Raulval82** [digitalLumberjack/recalbox-os#183]
Hi!

Please can you add permanently Neo Geo as a separated emulator? Not needed to add more cores, fba libretro runs perfect, it's only that in each update all files that I need to modify are overwriten... 

Thank you in advance!

**Comment by rockaddicted** [comment]
it is done : https://github.com/rockaddicted/recalbox-buildroot/commit/3ac212dadbd7efb38c5ad19ce1f26143a3e1ddc1

**Comment by rockaddicted** [comment]
When I try to start a game from the new separated system, neogeo, I come back to ES.

**Comment by rockaddicted** [comment]
the defaut switch used in recalbox.conf don't work, I must use this one to start neogeo : 
`neogeo.emulator=libretro
neogeo.core=imame4all/fba`

**Comment by lordtaki** [comment]
Works well on a few tested roms with 3.3.0 beta 1
