### ISSUE TITLE
[Bug] Multiple Wireless XBox 360 controllers not recognized

### ISSUE THREAD

**Issue by RomainOdeval** [digitalLumberjack/recalbox-os#184]
Since v 3.2.10 (maybe since 3.2.9), my wireless XBox 360 controllers are not recognized.
I set "enable_xbox_drv=1" and "xboxdrv_nb_controls=2" (and remove ; of course) but still have flashy green leds on controllers.

In game, two controllers are recognized like only one.

With controller interface, if i set #0 and #1 controller for pad 1 and 2, Raspberry Pi 2 crashed (when i select "Done").

For your information, i formatted and reinstalled completly recalbox and have same problem.

**Comment by digitalLumberjack** [comment]
Ok... I'll check that

**Comment by RomainOdeval** [comment]
i said it previously : RPi2 ;)

For ps -e, i check that this afternoon.

**Comment by RomainOdeval** [comment]
One line :
428      grep    xboxdrv

**Comment by digitalLumberjack** [comment]
Ok your xboxdrv is not loaded.
Try to edit the recalbox.conf file directly with nano if it's not what you did, chech that you have no char before variable names, and please give me the /root/recalbox.log content after a boot.

**Comment by digitalLumberjack** [comment]
the issue of black screen has been corrected and will be in 3.3.0 release. But what i don't understand is why both controllers are considered as only one... Did you tried with many emulators ? piFBA ?

**Comment by RomainOdeval** [comment]
With recalbox.log, i found problem : 

i have "enable_xboxdrv" and not "enable_xbox_drv".
But quite strange ... i'm pretty sure i have not delete this underscore ... is it possible that they have a mistake in recalbox.conf ?

**Comment by hackgrid** [comment]
The default recalbox.conf file was fine for me.

**Comment by RomainOdeval** [comment]
Ok, good to know.

**Comment by digitalLumberjack** [comment]
Is this issue still significant ?

**Comment by RomainOdeval** [comment]
i don't think so.
recalbox.conf seems good.

**Comment by rockaddicted** [comment]
I lové when issues are revolved alone

**Comment by RomainOdeval** [comment]
ahahah
Maybe an error in a precedent update but recalbox.conf was completly rewrite recently so ... it's good.

**Comment by rockaddicted** [comment]
So I'll close it. Thank you for the report.
