### ISSUE TITLE
Some default extensions are incorrectly configured

### ISSUE THREAD

**Issue by MairusuPawa** [digitalLumberjack/recalbox-os#188]
Megadrive: readme says ".md". Megadrive roms can also use .bin, .smd, and sometimes .gen extensions.

32X: readme says .32x (which is a good default), but games can also use .smd and .bin (SMD if dumped with a Super Magic Drive back in the days).

MasterSystem: readme says ".ms" but ES isn't configured to accept that. Default should be .sms, which is usually what's expected for Sega MS.

**Comment by digitalLumberjack** [comment]
Thanks i'm on it.

**Comment by rockaddicted** [comment]
https://github.com/rockaddicted/recalbox-buildroot/commit/624a838b7b9e8705c4c21ea7efda072384b3e04f

**Comment by spriggan59** [comment]
I tested Roms megadrive bin and SMD  it's works

the mastersytem README file also been corrected .MS  to .SMS
