### ISSUE TITLE
Rom supergraphx ne passe pas .

### ISSUE THREAD

**Issue by jackygoule** [digitalLumberjack/recalbox-os#189]
Les roms supergraphx ne passe pas (écran noir),alors que les roms  pc engine passe sans problème.

**Comment by rockaddicted** [comment]
https://github.com/digitalLumberjack/recalbox-os/issues/282

**Comment by digitalLumberjack** [comment]
Assigned to 3.3.0 for testing

**Comment by Cissoubaka** [comment]
corrigé dans la 3.3.0 alpha
