### ISSUE TITLE
Virtual Boy too slow

### ISSUE THREAD

**Issue by RomainOdeval** [digitalLumberjack/recalbox-os#197]
Hi,

I have a little issue with Virtual Boy.
Emulator works fine with games, but it's very slow.

In a game with a clock, you can see that 1 second takes 3 seconds.
(With Wario game)

Any idea ?
Thanks,

**Comment by digitalLumberjack** [comment]
I just tried Mario Tennis. It was smooth. RPi 1 or 2 ?

Le lun. 23 mars 2015 à 14:47, Romain Odeval <notifications@github.com> a
écrit :

**Comment by RomainOdeval** [comment]
RPi 2.

Maybe it's just only on Virtual Boy Wario Land ...

**Comment by RomainOdeval** [comment]
I change this rom and it's ok ! Maybe a bad rom ...
Thanks !

One other thing : it seems scraping doesnt work for this emulator.
Need to configure something ?

And, if you want a special music, this is the intro music of this console : http://www.youtube-mp3.org/get?video_id=l-D5zvl5NjE&ts_create=1427318595&r=ODguMTY0LjMwLjEwOA%3D%3D&h2=e2df438218a545c102c942e4201fd59d&s=35408

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-os/issues/243
