### ISSUE TITLE
Refactor in python the scripts for emulator auto config

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#199]

**Comment by rockaddicted** [comment]
So I tried the new configen and I've seen some problems. There it is my recalbox.conf : http://pastebin.com/x1c9fq7E

With this configuration :  
- my keyboard is in querty mode and not azerty
- the global game settings are not activated. My games are still smooth, not in 4/3, my shader is not activated.
- when I start a pifba game, It start in "portrait" mode and my controller is not recognized
- when I try to start a libretro-fba game, I come back to ES
- when I try to desactivate the bg musics, that don't work.

The specific games settings work well. In this example, my snes boot in the right core and with the good settings activated.

**Comment by digitalLumberjack** [comment]
I'm on it. Bénie soit l'alpha.

**Comment by digitalLumberjack** [comment]
keyboard corrected, globals corrected, bg music corrected

**Comment by rockaddicted** [comment]
good job :+1:

**Comment by digitalLumberjack** [comment]
libretro fba corrected :)

**Comment by rockaddicted** [comment]
mode français : on
Après avoir remappé ma manette xbox 360 sans fil, mes joysticks ne sont plus reconnus.
Ne sachant pas si c'est normal (feature pas encore intégrée dans configgen). Je te passe mes fichiers de config.

http://pastebin.com/QJmM3Tzs
http://pastebin.com/si3ygDXA
http://pastebin.com/QELSEZkK

**Comment by digitalLumberjack** [comment]
Closed pour moi, j'ai ajouté les L3, R3, et un second joystick dans la configuration, pour avoir tous les boutons de la Dualshock et des FC30 pro.
