### ISSUE TITLE
VI - Network features - Not showing

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#2]
By @anthonyjclarke : 
Hi

All setup and working, but not appearing on the n/w when I plug a LAN cable in. There is lots of flashing of the LED's on the n/w port of the Pi, I check my Router and it shows as a device but is not issued an IP address.

I drop into Command line, but not familiar with command lines IFCONFIG did not work.

Any suggestions?

Do you have any Wifi Support?

Thanks

**Comment by digitalLumberjack** [comment]
there is a bug with recalboxOS < 3.1.2 on rpi2 with the network. The network init.d script is executed too quickly and the interface is not available yet on the system. So there is no DHCP, no ip, no network.

This has been corrected in 3.1.2

**Comment by JoshGelman** [comment]
I'm having a similar issue, with build 3.1.3 on an RPi2. Not only is there no network option in the menu, but when I go to update, it says "NETWORK CONNECTION NEEDED". I've checked via SSH, and I am connected and am able to receive a response from a server that I pinged. I also tried again after setting a static ip, with the same result.

**Comment by digitalLumberjack** [comment]
Hi :) 
There is no network settings in emulationstation.

**Comment by JoshGelman** [comment]
Option to disable the share, or manually configure it, as well as your connection (static). Other than that, everything is great.

**Comment by digitalLumberjack** [comment]
The issue is still here on certain RPI1, the udev persistent net rule add twice the ethernet card in /etc/udev/rules.d/70-persistent...

I created a workaround that remove the ETH1 line of this udev rule if there is, and restart udev.
I hope it will work for all configurations. In next release : 3.2.1

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-os/releases/tag/v3.2.1
