### ISSUE TITLE
Add gameboy background GB zoid

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#202]

**Comment by mgoulartBR** [comment]
Would like some help on it?

**Comment by mgoulartBR** [comment]
I sent you the missing sections! Check you email, if it's okay you can close it!

**Comment by digitalLumberjack** [comment]
Ok thanks dude

Le ven. 27 mars 2015 à 02:40, mgoulartBR <notifications@github.com> a
écrit :

**Comment by digitalLumberjack** [comment]
fixed with https://github.com/digitalLumberjack/recalbox-buildroot/commit/c03c7a3f50b6294e5b545042a5a0fbd67a5d5e2e

**Comment by Cissoubaka** [comment]
corrected in the 3.3.0 alpha
