### ISSUE TITLE
use keyboard as second controller?

### ISSUE THREAD

**Issue by niekverw** [digitalLumberjack/recalbox-os#204]
i have one ps3 controller and a usb keyboard, is it possible to use the keyboard as a second controller? emulationstation does not recognize the keyboard as a controller.

**Comment by RomainOdeval** [comment]
Did you try to connect your keyboard before switch on your RPi ?

Can you give the name of this keyboard ?

**Comment by niekverw** [comment]
Yes, i did. its a logitech K400. It recognises the keyboard, but i cannot set it up as a second controller in the controller menu, is that normal?

**Comment by RomainOdeval** [comment]
Very strange ... because you have a menu to specify controller 1, controller 2, etc ...

Maybe digitalLumberjack will explain that ...

**Comment by niekverw** [comment]
Yea strange i cannot select the keyboard as 'controller', only the ps3 controller >.< . It is also not detected as a controller (but it works...), but maybe i'm overlooking things. Thanks!

**Comment by niekverw** [comment]
When i setup the ps3 controller as second controller and 'default' as first, it works. so there is no issue..

**Comment by digitalLumberjack** [comment]
Sorry i won't spend time on that.
