### ISSUE TITLE
Vectrex Libretro Core!

### ISSUE THREAD

**Issue by mgoulartBR** [digitalLumberjack/recalbox-os#205]
Lumberjack,

A new core was released for RetroArch.
https://github.com/libretro/libretro-vecx

Could be good to have on recalboxOS!

**Comment by digitalLumberjack** [comment]
That's good :)

**Comment by hstampfl** [comment]
i have a real one @home. Wish to have it on recalbox too

**Comment by mgoulartBR** [comment]
OMG! Is it working?!

**Comment by hstampfl** [comment]
Of course, it is working fine.

**Comment by rockaddicted** [comment]
system added : https://github.com/digitalLumberjack/recalbox-buildroot/commit/3a796fa187c49ffcf15f4e477944267d83dad32

**Comment by rockaddicted** [comment]
ok on RPI1 and Rpi2
