### ISSUE TITLE
4NES4SNES kernel patch

### ISSUE THREAD

**Issue by MairusuPawa** [digitalLumberjack/recalbox-os#206]
Hello,

I've been in touch with raphnet lately, who designed an interesting USB device called the "4NES4NES". This board provides an interface to connect Nintendo gamepads to a USB port, which is sometimes more practical than using a Pi's GPIOs.

Quoting:

> Under Linux, the device has always worked as a single joystick
> with 8 axes and 32 buttons, but after a specific (unknown to me)
> kernel version, it became 2 axes and 32 buttons.
> 
> Instead of fixing it to revert the old single-joystick behaviour,
> I found that I could simply enable a quirk which makes it
> appear as four controllers. I posted the patch this weekend so
> I don't know when (and if) it will be accepted, but if you
> want you can apply it and recompile your kernel:
> http://www.spinics.net/lists/linux-usb/msg123190.html
> 
> If you do use the patch and it does not apply to the source
> tree you use for the pie, I'll be happy to rebase it for you. Just
> let me know the git repository you build from.

4nes4snes: http://www.raphnet-tech.com/products/4nes4snes/index.php

I'm currently building a Recalbox-based project and want to use a 4nes4snes for a bunch of practical reasons. Could this patch be implemented as a default?

**Comment by digitalLumberjack** [comment]
Hi yep I will integrate the patch. I'm curious what's the project? :)

Le jeu. 26 mars 2015 à 17:14, MairusuPawa <notifications@github.com> a
écrit :

**Comment by MairusuPawa** [comment]
Le projet est pour le moment une suite d'échec documentée. :p

**Comment by leberrem** [comment]
Un gros merci aussi. J'avais ouvert une question différemment mais sur le même sujet.

A great thanks. I opened an issue differently, but on the same subject.

[lissue #67 ](https://github.com/digitalLumberjack/recalbox-os/issues/67)

**Comment by digitalLumberjack** [comment]
Corrected by https://github.com/digitalLumberjack/recalbox-buildroot/commit/808f72a5cbefc6c72ceaf6e73539f1118ad3206e
