### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by hackgrid** [digitalLumberjack/recalbox-os#208]
hi,

i use v3.2.10 on my rp2. The system tells me that a update is available (3.2.11 i guess) but after I start the update it immediately cancels and displays an "update failed restart system" error. 

Do I have to reinstall?

**Comment by digitalLumberjack** [comment]
Ouch. Can you give me the  /root/update.log and /root/recalbox.log after the update fails .

**Comment by hackgrid** [comment]
I tried updating again to get you the logs and it worked now - I tried it three times before opening the issue, i am sorry. Maybe a temporary problem with the server or my network - though transfering files to the rp2 worked. If it should happen again I know now which files i should provide!

**Comment by digitalLumberjack** [comment]
Ok i prefer that :)

**Comment by hackgrid** [comment]
I guess the problem was the ongoing github DDoS attack (see the news) ;-)

**Comment by digitalLumberjack** [comment]
Sadly it cannot be, as github does not serves update files :)
