### ISSUE TITLE
iso images for pc-engine do not load anymore

### ISSUE THREAD

**Issue by aefish** [digitalLumberjack/recalbox-os#209]
.cue/iso files which did load correctly on 3.2.10 do not load anymore on 3.2.11

**Comment by Vidi0t** [comment]
I am new to recalbox so I am starting with 3.2.11. I couldn't get ISO files to run either and so I found this thread. If the CUE file is with the ISO file then it will show up in the list of games, however, when I launch the game it goes to a black screen and looks like it will run but then it just goes back to the game list. Hope someone can get this working. I want to play Lords of Thunder. :)

**Comment by digitalLumberjack** [comment]
Hi, you should add pc engine bios in the bios folder : https://github.com/digitalLumberjack/recalbox-os/wiki/Add-system-bios-%28EN%29

**Comment by Vidi0t** [comment]
Thanks. I tried putting syscard3.pce into the bios folder but it still didn't work. I'm wondering now if I should have left the file in all caps. I renamed it from SYSCARD3.PCE to syscard3.pce
I'll try it again tomorrow.

**Comment by Vidi0t** [comment]
I tried putting the syscard3.pce file in the bios folder as well as the pcengine folder and it will still not run iso files. I also remnamed the file with all caps and still no joy. Anyone get pcengine iso files running on 3.2.1.1?

**Comment by Vidi0t** [comment]
I downloaded the iso files again from a different source and my games are working now. :)
