### ISSUE TITLE
Buildroot compilation fails with HTTP 404 error when downloading a Linux snapshot

### ISSUE THREAD

**Issue by LeRiton** [digitalLumberjack/recalbox-os#211]
Hi,

I'm trying to compile buildroot module and after hours, it fails on downloading some Linux archive, 404 URL is http://sources.buildroot.net/linux-2dae3c6d94c9c7823b78fb4c73d9313251462c1a.tar.gz which is truly unreachable.

Full trace is 
```
>>> linux 2dae3c6d94c9c7823b78fb4c73d9313251462c1a Downloading
Doing full clone
Clonage dans le dépôt nu 'linux-2dae3c6d94c9c7823b78fb4c73d9313251462c1a'
POST git-upload-pack (gzip 1102 to 595 bytes)
fatal: not a tree object
--2015-03-28 19:22:30--  http://sources.buildroot.net/linux-2dae3c6d94c9c7823b78fb4c73d9313251462c1a.tar.gz
Résolution de sources.buildroot.net (sources.buildroot.net)… 176.9.16.109
Connexion à sources.buildroot.net (sources.buildroot.net)|176.9.16.109|:80… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2015-03-28 19:22:30 erreur 404 : Not Found.

package/pkg-generic.mk:73: recipe for target '/home/leriton/recalbox/recalbox-buildroot-recalbox-rpi2/output/build/linux-2dae3c6d94c9c7823b78fb4c73d9313251462c1a/.stamp_downloaded' failed
make: *** [/home/leriton/recalbox/recalbox-buildroot-recalbox-rpi2/output/build/linux-2dae3c6d94c9c7823b78fb4c73d9313251462c1a/.stamp_downloaded] Error 1
```

The only change I made before launching `make` is commenting flag `BR2_PACKAGE_QTSIXA_SHANWAN` in favor of `BR2_PACKAGE_QTSIXA_GASIA`, I dont know if it's relevant.

This seems to be related to https://github.com/raspberrypi/linux/issues/891
Usage of hashes from Linux branch 3.19 is sayed to be unsafe...

Do you have this issue when compiling Recalbox release? Any idea of how I can fix this?

Thanks in advance!

**Comment by digitalLumberjack** [comment]
Hi, yep the 3.19 branch is unstable, as the rebase every time they merge, commits hash won't be usable. For now you just take the last commit of the branch and change it in the buildroot configuration.

**Comment by digitalLumberjack** [comment]
corrected with https://github.com/digitalLumberjack/recalbox-buildroot/commit/a74a9e3d93edacc7f465a03ac07bc8e7e47b8d2b

**Comment by rockaddicted** [comment]
correction ok
