### ISSUE TITLE
Game & Watch emulator

### ISSUE THREAD

**Issue by mgoulartBR** [digitalLumberjack/recalbox-os#214]
Hi,

Today, it was released a libretro core for Game & Watch (https://github.com/libretro/gw-libretro)
Could be so cool to have it on Recalbox!

**Comment by digitalLumberjack** [comment]
+1

**Comment by bbouko** [comment]
+1 too :) i wan't to play to "ball" :)

**Comment by RomainOdeval** [comment]
+1000 !

**Comment by rockaddicted** [comment]
system added : https://github.com/digitalLumberjack/recalbox-buildroot/commit/6512778e66d610ac4ee121fb34ef6ab2e850297

**Comment by rockaddicted** [comment]
Don't start with last master commit.
I reopen it and I'll corrected that.

**Comment by digitalLumberjack** [comment]
might be me ? Is the configgen well configured for the core ?

**Comment by rockaddicted** [comment]
Yeah the problem come from the last commit.
I tried with the version used in my test before update (73e19687954bb14466105ac2bba72aa8f66c4500) and there no problem. The core run well on the alpha.

I will looking that and if I don't find the problem, we'll stay in the previous commit version.

**Comment by rockaddicted** [comment]
Can't build a working version with the latest commits... I'll rolling back to the previous commit ok ?

**Comment by digitalLumberjack** [comment]
yep, can you add a comment in the .mk file with the issue (for us in the next version to be aware of this issue directly before updating the core)

**Comment by rockaddicted** [comment]
yep I'll

**Comment by rockaddicted** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/92a878fdf23df6e820bc177c1a503a9fe72dfc9c

**Comment by rockaddicted** [comment]
Ok on RPI1 & RPI2 with the last commit version.
