### ISSUE TITLE
MAnque émulateur suite l'instalaltion de RecalBox sur Raspberry Pi 2

### ISSUE THREAD

**Issue by JAC666** [digitalLumberjack/recalbox-os#215]
Bonjour,
Après avoir essayé Recalbox sur mon Raspberry Pi B+, je me suis acheté un Raspberry Pi 2.
Suite à l'installation de Recalbox sur mon Pi 2, je n'ai que les émulateurs Super Nintendo, PC Engine, Nes, Master System et Gameboy Advance.
Je voudrai savoir pourquoi les autres émulateus ne sont pas là et comment faire pour tout avoir.

Merci d'avance.

Raspberry Pi 2 avec carte mémoire 64Go fat32 (parce que exFat ne fonctionne pas...).

**Comment by digitalLumberjack** [comment]
Les systèmes ne s'affichent pas si les dossiers sont vides.

**Comment by JAC666** [comment]
Merci beaucoup.
