### ISSUE TITLE
Boot first kodi no effect

### ISSUE THREAD

**Issue by Bluelightcrew** [digitalLumberjack/recalbox-os#225]
I want to Boot Kodi first,so i edit the recalbox.conf and change the line to kodi_at_start=1. But this has no effect.Version is 3.2.11 on Raspberry 1B

**Comment by eldoncoy** [comment]
Hi, I had the same problem, try to modify the file directly in ssh
It's work for me :)

**Comment by Bluelightcrew** [comment]
Ok, I have it done over nano. Works too. Thanks for the hint!

**Comment by eldoncoy** [comment]
cool
