### ISSUE TITLE
Problème Emulateur GBA

### ISSUE THREAD

**Issue by BluTree** [digitalLumberjack/recalbox-os#226]
Bonjour,
Je poste ceci pour vous dire que la version de recalboxos 3.2.11 a un problème.
Lorsque je veux lancer un jeu GameBoy Advance, l'animation du lancement de jeu s'active, je remarque un changement de résolution sur mon écran, puis on me ramène vers le choix des jeux GBA
L'avez-vous déjà remarqué ? Si oui, une correction est elle possible ?

**Comment by rockaddicted** [comment]
Bonjour, depuis la version 3.2.1, recalbox ne fournis plus les différents bios systèmes nécessaires aux émulateurs. Merci de te référer à ce wiki pour plus d'informations https://github.com/digitalLumberjack/recalbox-os/wiki/Ajoutez-des-bios-%28FR%29
