### ISSUE TITLE
Dual Analog Controls

### ISSUE THREAD

**Issue by addicted131** [digitalLumberjack/recalbox-os#229]
Retroarch supports dual analog controls, including the pcsx-rearmed core. The inability to use the right thumb stick makes many newer generation PSX games unplayable (Ape Escape, Resident Evil Dualshock Edition). If possible it would be nice to have a work around to this issue, i noticed that createRetroarchconfig only contains one joystick, is it possible to add a second joystick to this configuration? I greatly enjoy this OS and appreciate all the work that has been put into it. I am looking forward to the 3.3.0 release as well. 

Thank You.

**Comment by digitalLumberjack** [comment]
Yep that goes with the recalbox-configgen new project

**Comment by addicted131** [comment]
I would just like to say that i greatly enjoy this operating system. With that being said, i have developed and found a solution to the dual analog stick issue. Solution to this was within retroarch configuration. It involved chowning the config files in terminal and editing the parameters of saving on exit and core specific configs. This was done with gedit. Then from within the retroarch GUI on the running RecalBox i configured the controller using the mapping tool in input settings and then edited the settings of the PCSX-ReARMed core for pad type digital to pad type dualshock. Within retroarch input settings i also changed control type to retropad and set digital to analog to none. Having discovered these things, i developed a very good understanding of the system and how its built. Finding this solution took alot of time and extensive debugging but i am pleased with the end result. Perhaps, it maybe possible to add this information into a PSX section of the user manual, however it will need to be better written and explained and i have since found a new method which doesnt involve gediting of the config files. Thank you for your response to my message and i hope that this information will be of some assistance to you.

**Comment by Diskutant** [comment]
> and i have since found a new method which doesnt involve gediting of the config files.

What is that new method?

**Comment by addicted131** [comment]
Upon a fresh install of the OS. Do a Emulation Station controller configuration. After this. Place a PSX game and bios into appropriate files. Enter the game. Press Horkey + B. This will take you to the retroarch RGUI. Go into general settings. Set core specific config to ON. Then set Save on exit to ON. Exit retroarch from the main menu of the RGUI. This takes you back to Emulation Station. Reopen the game. After this reopen the RGUI. Go to core options and change controller type to dualshock/analog. Retrurn to main menu. Enter input options. Go to Player 1 controls. Change controller type to retropad. Set digital to analog to none(so directional keys are not mapped to a joystick). Run the input settings auto mapping tool. The option is just below the joystick setting. This will prompt you too push the appropriate buttons and map them as they are pressed. Exit emulation from RGUI menu. This completes the setup of the right joystick. This will also give
 function to the L3 and R3 buttons. I used Ape Escape to test functionality and reliability of this method and it has proven to be stable as well effective.

**Comment by Diskutant** [comment]
Thanks! Got the Analog Sticks to work. :)
Do you know if it's possible to add the vibration feature too?

It seems like you are not using the english gui, or wrote the options down by memory. So just in case someone else wants to do this I wrote down the actual setting names on my system:
Hotkey + B does nothing at all.
Hotkey + F1 brings me into the RGUI menu.
I went to Settings -> General Settings  and turned "Configuration Per-Core" and "Configuration Save on Exit" on
Then Quit RetroArch from the main menu, start the game again, go to RGUI then to 
Options -> Core Options and set Pad 1 Type to "analog" (had no "dualshock" option)
Then back to main menu Settings -> Input Settings
There I changed "User 1 Device Type from "RetroPad" to "RetroPad w/ Analog" 
and then "User 1 Bind All" where I had to press the appropiate buttons. 
After that Ape Escape worked fine with both Analog Sticks and Left Thumb button. I think right Thumb Button will work too, but is not used in that game.

**Comment by addicted131** [comment]
I just hadnt really taken the time to write proper instructions. I got caught up in life for a little while. Also. Both L3 and R3 are used in Ape Escape. L3 is to go prone and crawl as well as dive in water. R3 is to walk/sneak. If they are not mapped you can go to input settings and scroll to bottom. There will be input 1 with each key mapping set. Find input R3. Then set the mapping to the key on your controller. I apologize for the confusion with dualshock. Its a setting option but only available if its typed into the config file on a linux computer. As far as vibration goes. I have no had the option to test this as I dont know what game to use to properly trigger it on demand. I was very happy at successfully getting full functionality out of the controller. I am glad that I could help you. I plan to write an in depth tutorial with correct instructions and possibly include it in the manual if digitalLumberjack allows.

**Comment by digitalLumberjack** [comment]
I'm trying to make these a defaut comportement if you have almost 1 stick on your controller. I'll let you know

**Comment by digitalLumberjack** [comment]
Note to myself, add R3 L3 in configuration

**Comment by n00b314pi** [comment]
Hey guys. thanks for the help on fixing the controls for the games!! i found if you just go into ra menu and then edit the input from analog to standard that also works. less steps for me. One thing I cant figure out though is the camera angles in ape escape? anyone else? every time i walk around the camera goes all wonky behind me.

**Comment by paradadf** [comment]
@n00b314pi please, use the forum for support.
For the record, some games need the input to be set as analog. That is the case for Ape Escape.
And for that game, the camera issue can be corrected going to Quick Menu -> Controls -> User 1 Analog to Digital Type -> Change it from "Left Analog" to "None".
