### ISSUE TITLE
Sega Saturn Libretro core (Yabause)

### ISSUE THREAD

**Issue by mgoulartBR** [digitalLumberjack/recalbox-os#231]
Hi,

I saw this libretro core for Yabause today, did you test it before?

https://github.com/libretro/yabause

**Comment by rockaddicted** [comment]
very low framerate... Saturn is very hard to emulate with a good pc, so with a rpi2, I don't think it is possible.
I close this issue and if in the futur there is a miracle and this core become usable, we'll add it.
