### ISSUE TITLE
PS3 Sixaxis leds stay in blinking state after pairing

### ISSUE THREAD

**Issue by Arduingo** [digitalLumberjack/recalbox-os#237]
After pairing sixaxis controller following the WIKI instructions, the controller instead of stop blinking and set the led to 1 indicating player one keeps all 4 blinking, this was tested with original Sony PS3 six axis controllers (Not dual shock 3).

**Comment by Jace37** [comment]
First reset your ps3 controller then Sinc your controller with à USb-cabel with recalbox on your pi. After that Every thing ahould word fine

Verstuurd vanaf mijn iPhone

**Comment by Arduingo** [comment]
Thanks for your suggestion Jace37, but it didm´t fixed the issue, I think this is related with the controller driver, same controller configured manually in another emulators distro works perfect without any blinking light and with the light indicating what controller number is in use.

**Comment by digitalLumberjack** [comment]
corrected with the recalbo.conf ps3 driver selection

**Comment by rockaddicted** [comment]
I cant connect my ps3 shanwan controllers to the recalbox in the version 3.3.0 alpha.
No problem to use them with my recalbox in 3.2.11

**Comment by rockaddicted** [comment]
When I start manualy the service S31sixad, the binary `/usr/sixad/$settings_version/sixad-bin` is looking for sixad-sixaxis in `/usr/sbin` and not in `/usr/sixad/$settings_version/`

**Comment by digitalLumberjack** [comment]
https://github.com/falkTX/qtsixa/blob/master/sixad/bluetooth.cpp#L236 damn

**Comment by digitalLumberjack** [comment]
quick and dirty https://github.com/digitalLumberjack/recalbox-buildroot/commit/ced75545bf3e8d38536d911de2d5024b2c969140

**Comment by digitalLumberjack** [comment]
I close but still need feedback on gasia and rpi1

**Comment by reivaax** [comment]
Feedback in alpha 3.3.0 mika 5 with official driver and official dualshock 3 in bluetooth with pi2 :
The leds stay doesn't blinking state after pairing. That is good. the led is fix.
But they have a problem if the pad is turning off when recalbox is loached. When i restart my pad, the fix of led is good but no reaction insight emulationstation.

**Comment by rockaddicted** [comment]
Fixed with PS3 Shanwan controlers.

**Comment by lordtaki** [comment]
Gasia controller is ok with 3.3.0 beta 2
