### ISSUE TITLE
Patch to fix blinking Xbox360 LEDs

### ISSUE THREAD

**Issue by pierrrrrrre** [digitalLumberjack/recalbox-os#240]
First of all, thanks for Recalbox, it's a really good project and the fact that it works more or less out of the box is really amazing!

I noticed an issue with my Xbox360 Wireless controller: the LEDs keep blinking even after it's started and synced with the USB dongle. Apparently it's a known issue in the Linux World for a long time...

I found [a thread from a dew weeks ago claiming to provide a patch in xpad to fix the issue.](http://permalink.gmane.org/gmane.linux.kernel/1938160) Do you think that could be included in Recalbox OS?

Thanks!

**Comment by digitalLumberjack** [comment]
fixed on rpi2 by https://github.com/digitalLumberjack/recalbox-buildroot/commit/9e17bce9b6bfc2ccf9ad0b62fedb544cd82cf101

**Comment by rockaddicted** [comment]
No more blinking leds with xpad driver
