### ISSUE TITLE
recalbox.conf issue when ssid string contains "_" character

### ISSUE THREAD

**Issue by el-Salmon** [digitalLumberjack/recalbox-os#241]
Manually configuring WiFi ssid and password in recalbox.conf file fails when ssid string contains _ character. In this case, the second part after _ is shown in the psk variable in wpa_supplicant.conf

**Comment by rockaddicted** [comment]
My SSID freebox contain a "_" and there is no connection problem...

**Comment by digitalLumberjack** [comment]
cool
