### ISSUE TITLE
add libretto cheats database

### ISSUE THREAD

**Issue by rockaddicted** [digitalLumberjack/recalbox-os#242]
https://github.com/libretro/libretro-database/tree/master/cht

**Comment by bbouko** [comment]
cool :)

**Comment by Laddyacris** [comment]
Oh oui cool :D

**Comment by digitalLumberjack** [comment]
closed with  https://github.com/digitalLumberjack/recalbox-buildroot/commit/32f124d47f22b9333c427839e27119cafdfb00aa

**Comment by Cissoubaka** [comment]
tested on psone and super nes, working but we need to change the path to the correct one in the retroarch config file.

**Comment by Dragda** [comment]
But the number of users who gonna use this is low. 

This isn't a priority, better for the 3.0.1

**Comment by digitalLumberjack** [comment]
as it already has been added, i'll just fix it for the 3.3.0

**Comment by digitalLumberjack** [comment]
@Cissoubaka 

+cheat_database_path = /recalbox/share/cheats/cht/
+cheat_settings_path = /recalbox/share/cheats/saves/

Does it work ? Should i let /cht/ ?

**Comment by digitalLumberjack** [comment]
So it does work .
