### ISSUE TITLE
Xin-mo driver (tht arcade console 2p usb player)

### ISSUE THREAD

**Issue by RyYo** [digitalLumberjack/recalbox-os#247]
Bonjour,
Ce module (http://www.xin-mo.com/?page_id=34) permet de contrôler 2 manettes (10 et 12 boutons) avec 1 seul contrôleur USB. Hélas il possède un comportement particulier sous linux : il est vu comme un seul joystick comportant 4 axes et 22 boutons alors que sous windows il est vu comme 2 joysticks différents. De ce fait, la plupart des émulateurs ne verront pas les commandes du second joueur.

Heureusement quelqu'un a réussi à le faire fonctionner en patchant le noyau linux pour corriger cela :
http://ithink.ch/blog/2013/09/08/

Les émulateurs suivants ont été patché pour accepter correctement ce contrôleur : 
- piFBA : https://github.com/petrockblog/RetroPie-Setup/wiki/Troubles-with-the-Xin-Mo-Controller
- pisnes : http://pimame.org/forum/discussion/comment/2367#Comment_2367
- Picodrive : https://github.com/ian57/Raspicade-pibfa-xinmo

N'ayant pas les compétences pour inclure toutes ces modifs dans la recalbox, j'espère que quelqu'un pourra le faire :)

Merci.

EDIT : mise à jour des liens

**Comment by jeanmitchoum** [comment]
Bonjour,
Je possède ce module (Xin-Mo 2 joueurs), connecté sur deux pads arcade "maison" achetté sur le site ebay. Tout Fonctionne correctement de mon côté depuis la Bete2  3.3.0 de recalbox. Seul l'émulateur N64 ne reconnait toujours pas les commandes.
Test fait avec 18 boutons, 2 pads arcades, raspberry pi 2. et deux gamepads USB traditionnel en simultané.
Beau travail ! Merci :)

**Comment by digitalLumberjack** [comment]
Ca fait plaisir de voir que ca fonctionne :)

**Comment by rockaddicted** [comment]
Bonne nouvelle, on attendait justement un retour concernant les xin-mo.
Pour la N64, c'est normal il faut passer par une configuration à la mano.
Te serait il possible faire la config en suivant ce post, et nous filer le fichier stp ? http://blog.recalbox.com/forums/topic/configuration-manette-mupen64plus/

On pourra alors intégrer la config xin-mo dans la config de base de mupen64 ^^

**Comment by digitalLumberjack** [comment]
le soucis est que tout dépend du mapping du xinmo.
Il faudrait implémenter le configgen pour mupen maintenant si vous pensez que ça vaut le coup...

**Comment by rockaddicted** [comment]
Quelques bon jeux de la N64 sont jouables, mais on reste très loin d'une émulation parfaite.
Après c'est clair que le configgen pour mupen64 serait un plus et éviterait un grand nombre de retours de manettes non reconnues. Les gens ne pigent pas trop le pourquoi du comment étant donné que tout le reste sur la recalbox c'est du plug&play.
A toi de voir en fonction du taff que ça représente ;)

**Comment by jeanmitchoum** [comment]
Je pensais ne pas y arriver, mais j'ai tout de même réussi a faire fonctionner les joysticks arcades connectés sur le Xin-Mo avec mupen64, testé ok avec super mario 64 et mario kart 64. Voici les lignes que j'ai rajouttées dans le fichier /usr/share/mupen64plus/InputAutoCfg.ini : 

[THT THT Arcade console 2P USB Player]
plugged = True
plugin = 2
mouse = False
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(6)
Z Trig = button(2)
B Button = button(0)
A Button = button(1)
C Button R = axis(1+)
C Button L = axis(1-)
C Button D = axis(2+)
C Button U = axis(2-)
R Trig = button(4)
L Trig = button(3)
Mempak switch = button(7)
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)


En revenche, je n'ai pas réussi a faire fonctionner correctement les gamepads USB normaux.

**Comment by easyfrance** [comment]
@jeanmitchoum , peux-tu nous en dire plus sur la configuration du xinmo, car je rame.
Je fait le paramétrage de chaque joystick via l'interface mais cela n'a aucune incidence dans FBA 
bref comment as-tu fait pour arriver à paramétrer tes 2 joysticks ? (merci)

**Comment by rockaddicted** [comment]
Pour les xin-mo, tu ne dois mapper **uniquement** ton "player1" .
Si tu mappes ton player2 ça fou la merde.
De plus il faut être en version bêta.

**Comment by easyfrance** [comment]
Je suis bien sous la beta 3.3.0, mais est-ce à dire que je ne peux jouer qu'a 1 ?!

**Comment by rockaddicted** [comment]
non non, je ne vais entrer dans les détails, mais le mapping de ton joueur 1 sera utilisé à la fois pour le joueur 1 et le joueur 2. Par contre si tu mappes ton joueur 2 après avoir mappé ton joueur 1, tu te retrouvera avec un mapping foireux qui sera utilisé pour les 2 joueurs.

**Comment by jeanmitchoum** [comment]
Je confirme les dire de rockaddicted, je n'ai mappé que le joueur 1 via l'interface, et les deux joueurs fonctionnent correctement depuis la beta 3.3.0.

**Comment by easyfrance** [comment]
merci pour vos réponses. cela semble en effet fonctionner pour le frontend mais pas sous fba. je vais me faire un petit fba2x.cfg pour essayer.
