### ISSUE TITLE
Manette PS3 DS3 Sixaxis Modèle N° CECHZC2U

### ISSUE THREAD

**Issue by myke94** [digitalLumberjack/recalbox-os#249]
Bonjour,

La prise en charge de ce modèle de manette n'est semble-t-il pas intégré.
(Modèle US)
Impossible de la synchroniser, que ce soit en USB ou Bluetooth.

Il est impossible de récupérer quoi que ce soit en faisant un scan avec le bluetooth.
En revanche le modèle Européen (CECHZC2E), ça ne pose aucun problème.
Et malheureusement, en France, on trouve les 2 modèles.

Merci.
Version de Recalbox : 3.2.11

---------------------------------------------------------------------------------------------------------------------
Hello,

The management of this model seems he is not integrated.
(US model)
Unable to synchronize, either USB or Bluetooth.

It is impossible to recover anything by making a scan with bluetooth.
However the European model (CECHZC2E), it is no problem.
And unfortunately, in France, there are the 2 models.

Version Recalbox : 3.2.11

**Comment by digitalLumberjack** [comment]
corrected with sleection of sixais driver in recalbox.conf

**Comment by myke94** [comment]
J'ai bien rajouté ceci dans recalbox.conf
# ------------ J - PS3 Controllers ------------ #
ps3_sixad_version=CECHZC2U

Mais ca ne fonctionne toujours pas.
-----------------------------------------------------------------------------------------------------------------------------------------------

I have added this in recalbox.conf
J # ------------ - ------------ # PS3 Controllers
ps3_sixad_version = CECHZC2U

But this still does not.

**Comment by rockaddicted** [comment]
Ce sera effectif dans la prochaine release la 3.3.0
Patience la bêta est proche.

**Comment by myke94** [comment]
Merci ;)

**Comment by johanpoirier** [comment]
Ca marche nickel avec la ligne de conf en plus, merci !

**Comment by myke94** [comment]
@johanpoirier : tu peux préciser? parce que la nouvelle release n'est pas encore sortie!
Donc ca ne devrait pas fonctionner encore!

**Comment by myke94** [comment]
J'avais pas vu qu'il y avait les beta en telechargement!
je vais tester ça ;)

**Comment by johanpoirier** [comment]
Oui, j'ai testé avec la beta 3.3.0-beta-8 et j'ai pu jouer tranquillement à Gran Turismo comme à l'époque ;)

**Comment by caverna** [comment]
Hi! I have this exact joystick model and testing with 3.3.0-beta-9 doesn't work.

**Comment by digitalLumberjack** [comment]
Hi carlos, did you tried to change the ps3 driver in recalbox.conf ?
