### ISSUE TITLE
Typo in createRecalboxOS.sh

### ISSUE THREAD

**Issue by lurch** [digitalLumberjack/recalbox-os#25]
Line 12 says `recalboc-buildroot` when I'm *guessing* it should be `recalbox-buildroot` :)
(I couldn't find `createRecalboxOS.sh` in a repo to issue a PR against?)

**Comment by digitalLumberjack** [comment]
Hi, yeah it's not a file in sources i just put in automatically in releases. Thank you i corrected that ;) Will be in the next release.
