### ISSUE TITLE
Emulation Station, theme Zoid: fichiers GameBoy manquants

### ISSUE THREAD

**Issue by dginhoux** [digitalLumberjack/recalbox-os#250]
Il faut telecharger le theme Zoid complet (http://blog.petrockblock.com/forums/topic/theme-zoid/).
Puis recuperer seulement le dossier gb.
Puis placer ce dossier dans /root/.emulationstation/themes/zoid.

**Comment by rockaddicted** [comment]
Le bug est déjà corrigé dans la 3.3.0 qui va sortir prochainement.
Mais merci de donner la marche à suivre pour les impatients =)
https://github.com/digitalLumberjack/recalbox-buildroot/commit/c03c7a3f50b6294e5b545042a5a0fbd67a5d5e2e

**Comment by Cissoubaka** [comment]
c'est bon, corrigé dans l'alpha
