### ISSUE TITLE
PSP it is Possible ?

### ISSUE THREAD

**Issue by lordkane** [digitalLumberjack/recalbox-os#256]
Hi it is Possible to run PsP Playstation Portable emu ?
https://www.youtube.com/watch?v=O8juShfoJtE ? in this video it work ?

**Comment by rockaddicted** [comment]
Yes indeed it is possible, and it should be added in the next recalbox versions.
Be patient =)
I close this this issue because there is an other issue opened about the psp.

https://github.com/digitalLumberjack/recalbox-os/issues/119
