### ISSUE TITLE
ATARI 7800 Emulator (Libretro core)

### ISSUE THREAD

**Issue by dalecoop** [digitalLumberjack/recalbox-os#257]
Hi,

Would it be possible to have the ATARI 7800 (ProSystem) libretro core on Recalbox?
https://github.com/libretro/prosystem-libretro

**Comment by mgoulartBR** [comment]
+1

**Comment by rockaddicted** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/pull/22

**Comment by digitalLumberjack** [comment]
:+1:

**Comment by rockaddicted** [comment]
theme to add in the new template

**Comment by Cissoubaka** [comment]
I tested 2/3 games, everything seems to be ok

**Comment by rockaddicted** [comment]
OK with a RPI2 but not a RPI1 B+, I'll corrected that.

**Comment by rockaddicted** [comment]
Corrected on RPI1 B+

**Comment by dalecoop** [comment]
Great job !

**Comment by digitalLumberjack** [comment]
Nice
