### ISSUE TITLE
settings control for emulator?

### ISSUE THREAD

**Issue by ricardoalvarenga101** [digitalLumberjack/recalbox-os#258]
setting control for each emulator?

**Comment by Laddyacris** [comment]
Why ?

**Comment by ricardoalvarenga101** [comment]
For example, to play pinball use a different configuration fighting games and also for playstation or n64 We have more buttons. like much of a different configuration for each emulator.

**Comment by Laddyacris** [comment]
you play pinball with what emulator ?
 i see this : https://github.com/digitalLumberjack/recalbox-os/issues/39

but you can create a different configuration manually  /recalbox/configs/retroarch/retroarch_psx.cfg 

use command --appendconfig

if [[ "$emulator" == "psx" ]]; then
/recalbox/scripts/runcommand.sh 4 "$retroarchbin -L $retroarchcores/pcsx_rearmed_libretro.so --config /recalbox/configs/retroarch/retroarchcustom.cfg --appendconfig /recalbox/configs/retroarch/retroarch_psx.cfg \"$1\""
fi

see : http://blog.recalbox.com/forums/topic/tuto-configurer-manette-pour-emulateur-dedie/ (in french sorry)

**Comment by ricardoalvarenga101** [comment]
Perfect! Tks!

**Comment by ricardoalvarenga101** [comment]
yes I play pinball, but there is still no specific emulator for it in recalbox

**Comment by ricardoalvarenga101** [comment]
problema resolvido.
