### ISSUE TITLE
RTL8191S WLAN Driver missing

### ISSUE THREAD

**Issue by Asmod4n** [digitalLumberjack/recalbox-os#26]
A normal raspbian setup has this driver included, raspi-config is also missing, could you add those?

**Comment by digitalLumberjack** [comment]
Hi,
As you know recalboxOS is not a raspbian distrib. I'll add of course the driver for the wireless dongle, but i will not add raspi-config as the system is not the same at all.

**Comment by Asmod4n** [comment]
yay :+1:

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/e9e5719583100d97f4e71775c01238a6ebe3867f
