### ISSUE TITLE
add supergrapfx libretro core

### ISSUE THREAD

**Issue by reivaax** [digitalLumberjack/recalbox-os#282]
grg123 in IRC channel want to load sgx rom in recalbox.

they have a libretro core for this machine :
https://github.com/libretro/beetle-supergrafx-libretro

Have a nice day ! :D

**Comment by mgoulartBR** [comment]
+1

**Comment by digitalLumberjack** [comment]
And it will be really fast to download the fullset, with the 5 or 6 games release on the platform :)

**Comment by rockaddicted** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/da1466e127820fcbd3f1705ec4a64903a59f15a6

**Comment by Cissoubaka** [comment]
It's working with the new core, I didn't see any error

**Comment by digitalLumberjack** [comment]
Yeah ! First Verified✔ by community !

**Comment by rockaddicted** [comment]
I'll try it on raspberry 1 B+ today and I'll come back to give my feeback.
