### ISSUE TITLE
Virtual Jaguar Libretro core

### ISSUE THREAD

**Issue by mgoulartBR** [digitalLumberjack/recalbox-os#297]
Guys,

I'm here again! I saw an update on Virtual Jaguar libretro core. Is there any plan to test it on future Recalbox releases?

https://github.com/libretro/virtualjaguar-libretro

**Comment by rockaddicted** [comment]
Hello this update is about a ps3 build fix. https://github.com/libretro/virtualjaguar-libretro/commit/534b1644825e22d858367581292ae2ae19155d55
So I don't think there will be significant changes for the rpi.
