### ISSUE TITLE
Ps3 controller issue

### ISSUE THREAD

**Issue by Raulval82** [digitalLumberjack/recalbox-os#30]
Hi! I have two ps3 controllers paired with the system, leds 1 and 2 are blinking in the controllers, and emulation station says that there are 2 controllers detected, but when I press any button nothing happens. Any help?

**Comment by digitalLumberjack** [comment]
Hi,
Sony PS3 ? DualShock 3 or sixaxis ? Chinese clones ?
USB or Bluetooth ?

**Comment by Raulval82** [comment]
Hi! Both are original sisaxis controllers, and I'm using a bluetooth dongle that was working under retropie. 

Thanks in advance.

**Comment by digitalLumberjack** [comment]
If you go in input settings and try to configure them ?

**Comment by Raulval82** [comment]
I tried, it says that controllers are detected, but when I press a button the message of hold button to configure is not shown, nothing happens.

**Comment by digitalLumberjack** [comment]
Ok
Try F4 to quit emulationstation , then ALT+F2 to get the prompt. 
"root" and "recalboxroot"
jstest /dev/input/js0 and jstest /dev/input/js1 and tell me if it respond well.

**Comment by Raulval82** [comment]
The controller is detected properly, the matrix with the buttons is showed, but nothing happens...

**Comment by digitalLumberjack** [comment]
Ok that's not good. I hope that is not a compatibility issue with the sixad driver. 
Is is Sixaxis or DualShock 3 ? My sixaxis works but i have never tester a dualshock 3...

**Comment by Raulval82** [comment]
In the rear of the controller says dualshock 3 and sisaxis, I don't really know the version.

**Comment by digitalLumberjack** [comment]
Hum, i'm afraid the sixad driver modified for the compatibility of chinese clones is not working with your dualshocks. 
I will have to get a dualshock and test that.

**Comment by Raulval82** [comment]
I will try this afternoon two more bluetooth adapters, maybe the issue is there...

**Comment by digitalLumberjack** [comment]
I don't think so but it's good you can test.

Le mer. 25 févr. 2015 à 10:27, Raulval82 <notifications@github.com> a
écrit :

**Comment by Raulval82** [comment]
Is working! Finally I found one that works! Two not compatible, but the last one worked fine!

**Comment by digitalLumberjack** [comment]
Nice,
But i wonder why the two other don't work.
Could you edit the wiki to tell us wich one work and don't ?
https://github.com/digitalLumberjack/recalbox-os/wiki/Compatibility-%28EN%29

**Comment by colking** [comment]
I'm trying to configure a wireless PS3 Dualshock3 SIXAXIS with recalbox on rasp pi2 and no luck.  I'm using an Asus BT400 dongle.  No controller found.

**Comment by kryptto** [comment]
I use SIXASIS DShock and without DShock without issues.  When pressing the PlayStation button it should sync on its own, is the controller charged?  Otherwise use a USB cord and plug it into the RPI directly then hit the sync button, disconnect and try the sync button again it should work.  The Asus BT controller you use is compatible so it should work.  

Kryptto

**Comment by colking** [comment]
Thanks dude!

The thing is, I don't have a PS3 so I'm not sure if the controller is actually charged/charging... I have it plugged into a pc USB port.  It only flashes when I push the home (PS) button.  Maybe it's not charging? And that's why it won't sync?

Colin Kingsmore
416-562-9467
www.colinkingsmore.com

**Comment by kryptto** [comment]
I charge my PS3 controllers from the RPI USB ports.  When you hit the PS3 button, ALL lights should all simultaneously blink, then when it detects the RPI, it will start blinking the lights in order back and forth one at a time, then stop on the channel it configures too.  

The controllers only need an hour to charge, BUT the battery inside might not be holding a charge anymore.  It happens...  I bought both of mine here in the US at Game Stop as used.  I assume the buttons or batteries will die on me.  Just a thought is a GS is near you.  DONT buy them off eBay or Amazon.  Too many of the suppliers are shipping knock offs that look like the real PS3 controllers.

**Comment by colking** [comment]
I bought it used at an EB games in Toronto here. Maybe that's the prob.... So when I plug the PS3 controller into the pi all 4 lights flash fast then eventually all flash a little slower... Then they turn off.  I think I had #1 solid red at one point but then it turned off.

Colin Kingsmore
416-562-9467
www.colinkingsmore.com

**Comment by colking** [comment]
It's now solid red on player 1 but I have to have the USB plugged into the pi or they start to flags again... Still not pairing even with the solid light. Maybe it's charging now... Had it plugged in for a few hours but lights were off.  They only flashed for the first few mins of initial charge. 

Thanks again

Colin Kingsmore
416-562-9467
www.colinkingsmore.com

**Comment by kryptto** [comment]
https://www.playstation.com/manual/pdf/CECHK01-2.30_2.pdf

Pages 16/17 have descriptions of the PS3 controllers lights etc.  Obviously the guide doesn't apply to the use with the Recalbox, just helpful.

Kryptto

**Comment by kryptto** [comment]
So while plugged into the RaspPI hit the Sony button on the controller.  Then wait for the lights to settle.  Then disconnect the cord hit the Sony button on the controller, it SHOULD sync.  Then play away, if still not working then post the exact model number here.  Sony also has a part of their site that identifies Sony official controllers.

**Comment by colking** [comment]
So it's solid red on #1 but still will not configure or pair in settings.  When I unplug the USB, all lights flash again.

I'm using a recalbox/openelec dual boot.  Will that effect this issue?


Colin Kingsmore
416-562-9467
www.colinkingsmore.com

**Comment by colking** [comment]
Plugged it back into pi and hit the Sony button and the lights continue to flash slowly now.  The model NO. says:
CECHZC2U A1

Another #:
8021076600461

Thanks!

Colin Kingsmore
416-562-9467
www.colinkingsmore.com

**Comment by kryptto** [comment]
Let's have the dev team respond, I have read posts including this thread stating their might be issues.  Your controller should be working.  Something else might be wrong.

**Comment by colking** [comment]
Thanks! 

Colin Kingsmore
416-562-9467
www.colinkingsmore.com

**Comment by colking** [comment]
I actually did a fresh install of the recalbox/openelec and both the PS3 dual shock and wii u pro controllers are working! 
That's good news.  The bad news is I have to setup up all of my roms... Scraping... Etc. lol
Plus setup kodi again. Oh well. Thanks again

Colin Kingsmore
416-562-9467
www.colinkingsmore.com

**Comment by kryptto** [comment]
Excellent news, also use Wimimage32 free SD Windows based utility to make images of your SD card as a great strategy to have backups.

**Comment by colking** [comment]
Yes!  I have so many backups!  I've learned to have not too many different brands of sd cards... Have about 4 different brands and some  are like  .1 kb smaller which makes it impossible to restore. Lol 




Colin Kingsmore
416-562-9467
www.colinkingsmore.com
