### ISSUE TITLE
Add WonderSwan (color) emulator

### ISSUE THREAD

**Issue by nekomania** [digitalLumberjack/recalbox-os#304]
Please consider adding this little handheld into Recalbox, thank you. :)

https://www.youtube.com/watch?v=VhZ3ESHJobk

**Comment by rockaddicted** [comment]
Added to the 3.3.0 version.
https://github.com/digitalLumberjack/recalbox-buildroot/commit/72f2226e3e568f1af496f040fbc1377389111a99

**Comment by mfwhite** [comment]
Its available the beta version 3.3.0 for testing ?

**Comment by Cissoubaka** [comment]
working on a Rpi2

**Comment by spriggan59** [comment]
it's work Rpi2

**Comment by rockaddicted** [comment]
It's working too on RPI1.

**Comment by nekomania** [comment]
Thanks for filling my request. The wonderswan core works, but I think the display aspect ratio is not correct. It should be something like 16:10 (224x144), definitely not 4:3.

**Comment by digitalLumberjack** [comment]
Thanks @nekomania for this information

**Comment by digitalLumberjack** [comment]
Reopen for the ratio

**Comment by digitalLumberjack** [comment]
Added default 16/10 for wonderswan. Will be in next beta

**Comment by nekomania** [comment]
I did an online update to beta3, the wswan ratio remains 4:3. Then I reformat my sdcard and did a fresh install, still can't get 16:10. Did I missed something? :-/

**Comment by digitalLumberjack** [comment]
let's see in beta 4 :P

**Comment by lordtaki** [comment]
3.3.0 beta 4 seems fine to me concerning the ratio.

**Comment by digitalLumberjack** [comment]
super cool
