### ISSUE TITLE
wonderswan - check the strip process

### ISSUE THREAD

**Issue by rockaddicted** [digitalLumberjack/recalbox-os#308]
The core don't start in the alpha version. Check the strip process.

**Comment by digitalLumberjack** [comment]
I'll do that

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/bf01b3bdfd8ce7662307ab00477c60108c2108a7

**Comment by Cissoubaka** [comment]
testé sur Rpi2 et fonctionnel

**Comment by digitalLumberjack** [comment]
rpi1 anyone ?

**Comment by rockaddicted** [comment]
Work on RPI1 too.
