### ISSUE TITLE
Option menu / Sound / Interface background music

### ISSUE THREAD

**Issue by MaxCorpEnjoy** [digitalLumberjack/recalbox-os#314]
To enable/disable background music in the game selection interface, a switch is available in "OPTIONS DU SON/ACTIVER LES SONS". I think it is not a good definition since it does not disable the ingame audio.
It could also be a good idea to add a variable to adjust this background music independtly of the ingame volume.

**Comment by digitalLumberjack** [comment]
I was on it, excatly when you created the issue : https://github.com/digitalLumberjack/recalbox-emulationstation/commit/c27047c73ece93abb5fe5652c1816706c3917ce0#diff-541ba91e3cc7e25fa77616efdcf65245R391

**Comment by spriggan59** [comment]
does not work when we lower the volume below 70% of its
sound to work only 75% to 100%

**Comment by Soullimb** [comment]
On peut désactiver le son, j'ai redemarrer recalbox et impossible de le réactiver.

**Comment by Soullimb** [comment]
Le son fonctionne en fait, mais ne revient pas si on en fait rien. Il faut faire défiler les emulateurs pour initialiser le son. Je me suis fait avoir.

Surak
