### ISSUE TITLE
kernel panic when enable controlles.gpio.args with "map=1" during next boot

### ISSUE THREAD

**Issue by hstampfl** [digitalLumberjack/recalbox-os#318]
setting controlles.gpio.args=map=1 produces a kernel panic during next boot.
booting with the setting controllers.gpio.args=map=1,2 works fine.

used alpha-hstampfl-3.
------------ D3 - GPIO Controllers ------------
...
mk_gpio arguments, map=1 for one controller, map=1,2 for 2 (map=1,map=1,2)
controllers.gpio.args=map=1

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/mk_arcade_joystick_rpi/commit/816cc585662a376fd652e4565eeb37f4d4d057ec

**Comment by hstampfl** [comment]
the new driver works now with both args settings fine. 
thanks for your fast support.
