### ISSUE TITLE
Include latest version of Kodi (v15.0)

### ISSUE THREAD

**Issue by pierrrrrrre** [digitalLumberjack/recalbox-os#325]
[Kodi v15](http://kodi.tv/kodi-15-0-isengard-one-release-to-rule-them-all/) has been released a few days ago. Could it be possible to include it in the next release of Recalbox?

I can help, but I don't really know where to start :) If someone can point me to some documentation on how to do, I'll try my best!

**Comment by digitalLumberjack** [comment]
We'll have to wait for the buildroot update, that should be out soon :)

**Comment by pierrrrrrre** [comment]
OK I see!

I'm not familiar with buildroot. I checked the website but I'm not sure to understand how/when are the packages available for this built. Do you have more info on this?

**Comment by digitalLumberjack** [comment]
Yes you have the buildroot git : http://buildroot.uclibc.org/git.html http://git.buildroot.net/buildroot/

**Comment by Haris1977** [comment]
Kodi update should be done under "main menu=>update" button?

**Comment by JanBaunooo** [comment]
Buildroot 2015.08 is out

**Comment by rockaddicted** [comment]
planned to the 3.3.1 and an issue is open. I close this one.
https://github.com/digitalLumberjack/recalbox-os/issues/280
