### ISSUE TITLE
On an old raspberry pi, having gpu_mem=256 as default makes emulationStation crashes oom

### ISSUE THREAD

**Issue by arthurlutz** [digitalLumberjack/recalbox-os#329]
When launching a scraping operation recalbox, emulationStation crashes.  A quick look at dmesg shows : 

```
[ 103.534477] Out of memory: Kill process 252 (emulationstatio) score 547 or sacrifice child 
```

60M of RAM is clearly not enough. After setting ```gpu_mem=128``` in config.txt scraping seems to be working. This maybe disables some emulators that need more memory for the GPU I guess. 

I would recommend setting a lower default to start of with and maybe one can configure bigger GPU memory for certain use cases.

**Comment by rockaddicted** [comment]
already corrected in the 3.3.0 https://github.com/digitalLumberjack/recalbox-os/issues/181
