### ISSUE TITLE
Make command (Problem with mt7601 wifi driver)

### ISSUE THREAD

**Issue by Fuhrmann** [digitalLumberjack/recalbox-os#335]
Is there a way to run the 'make' command? I have a Ralink 5370 wifi dongle but its not working. Already found a solution but involves runnning the 'make'  command to compile the drivers, but I cant because the command its not installed (not found).

Any other alternatives? 

Thanks in advance.

**Comment by fschaefer** [comment]
IIRC Ralink 5370 uses the `rt2800usb.ko` kernel module, which is already there:
```
# find / -name "rt2800usb.ko"
/lib/modules/3.19.2-v7/kernel/drivers/net/wireless/rt2x00/rt2800usb.ko
# strings /lib/modules/3.19.2-v7/kernel/drivers/net/wireless/rt2x00/rt2800usb.ko  | grep firmware=
firmware=rt2870.bin
# find / -name rt2870.bin
/lib/firmware/rt2870.bin
```

Check `lsmod` if the module is loaded.

**Comment by Fuhrmann** [comment]
Thanks, will try that ASAP. Is there a way I can confirm the model of my wifi dongle? In the site I bought it says RT5370 but I can't confirm that.

**Comment by fschaefer** [comment]
`lsusb` should give something like:
``` 
# lsusb | grep Ralink
Bus 001 Device 007: ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter
```

**Comment by Fuhrmann** [comment]
I got this as output:

`Bus 001 Device 003: ID 148f:7601 Ralink Technology, Corp. `

In my linux installation I did install a MT7601 driver because the rt5370 drivers did not worked. So I  guess my model is not the RT53070 as the seller told me...

**Comment by Fuhrmann** [comment]
Allright, I discovered that my Wifi dongle needs mt7601 driver to work. How do I proceed to install it in recalbox? It works great in RetroPie after I installed and compiled the driver, but I want to use Recalbox :(

**Comment by Fuhrmann** [comment]
@digitalLumberjack is there a possibility to include MT7601 driver for the next version of recalbox? Thanks.

**Comment by Fuhrmann** [comment]
We can close this issue since it was stated in issue #356 this project will receive support for the MT7601 driver in the 3.3.0 release.
