### ISSUE TITLE
Place files in places that are FHS compliant

### ISSUE THREAD

**Issue by arthurlutz** [digitalLumberjack/recalbox-os#340]
https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

For example /recalbox/ is not FHS compliant. /opt/recalbox/ would be fine I guess.

**Comment by digitalLumberjack** [comment]
Hi, i know it's a good practice, but in an embbeded system destined to be a read only, i don't think it is a great deal. As it would mean change all the path in all scripts and configuration system, i think we will keep /recalbox.
Sorry :(

**Comment by arthurlutz** [comment]
Shame. 

I think these little details will be looked at by people when they try out or choose recalbox over another retro emulation system (right now I'm trying out / going back to retropie which has a cleaner feel to it when debuging and hacking it). See the comment about customizing your system once it's installed (sshd vs dropbear, nano vs vim, no discovery vs avahi-daemon). But I understand your point, be careful about technical dept and build on it.

**Comment by digitalLumberjack** [comment]
Yep, recalbox is not meant to be hacked or debbuged, and for power users, linux hackers etc i think it's better to use retropie :)
