### ISSUE TITLE
More Emulators?

### ISSUE THREAD

**Issue by Haris1977** [digitalLumberjack/recalbox-os#342]
Any thoughts about adding new emulators like

AMIGA (uae4all), C64 (vice), TYRQUAKE, PRBOOM, DOUKUTSU, DINOTHAWR??

This would be great:)

**Comment by Guzilli** [comment]
Amiga and C64 would really be epic. Love those systems

**Comment by lordtaki** [comment]
Looks like a duplicate of https://github.com/digitalLumberjack/recalbox-os/issues/190 ?

**Comment by kryptto** [comment]
Intellivision +
