### ISSUE TITLE
Add default config with new buttons for controllers

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#346]
* ps3 wireless
* freebox
* 8bitdo joystick usb
* nes30 usb
* nes30 bt
* nes30 pro usb
* nes30 pro bt
* xbox360 usb
* xbox360 wireless

**Comment by Laddyacris** [comment]
Hello
	<inputConfig type="joystick" deviceName="Broadcom Bluetooth Wireless  Joystick                        " deviceGUID="0500000042726f6164636f6d20426c00">
		<input name="a" type="button" id="2" value="1" />
		<input name="b" type="button" id="1" value="1" />
		<input name="down" type="hat" id="0" value="4" />
		<input name="hotkey" type="button" id="8" value="1" />
		<input name="joystick1left" type="axis" id="0" value="-1" />
		<input name="joystick1up" type="axis" id="1" value="-1" />
		<input name="joystick2left" type="axis" id="2" value="-1" />
		<input name="joystick2up" type="axis" id="3" value="-1" />
		<input name="l2" type="button" id="6" value="1" />
		<input name="left" type="hat" id="0" value="8" />
		<input name="pagedown" type="button" id="5" value="1" />
		<input name="pageup" type="button" id="4" value="1" />
		<input name="r2" type="button" id="7" value="1" />
		<input name="right" type="hat" id="0" value="2" />
		<input name="select" type="button" id="8" value="1" />
		<input name="start" type="button" id="9" value="1" />
		<input name="up" type="hat" id="0" value="1" />
		<input name="x" type="button" id="3" value="1" />
		<input name="y" type="button" id="0" value="1" />
	</inputConfig>

**Comment by rockaddicted** [comment]
controlers added : 
- Xbox360 USB xboxdrv/no-xboxdrv
- Xbox360 Wireless xboxdrv/no-xboxdrv
- PS4 USB
- Freebox USB
- PS3 Shanwan
- Old Trustmaster than I use sometimes.

**Comment by digitalLumberjack** [comment]
Ok closed. need feedback

**Comment by digitalLumberjack** [comment]
Works with freebox + fc30 pro

**Comment by rubencm** [comment]
Xiaomi Bluetooth controller:

	<inputConfig type="joystick" deviceName="XiaoMi Bluetooth Wireless GameController" deviceGUID="05000000172700004431000029010000">
		<input name="a" type="button" id="0" value="1" />
		<input name="b" type="button" id="1" value="1" />
		<input name="down" type="hat" id="0" value="4" />
		<input name="joystick1left" type="axis" id="0" value="-1" />
		<input name="joystick1up" type="axis" id="1" value="-1" />
		<input name="joystick2left" type="axis" id="2" value="-1" />
		<input name="joystick2up" type="axis" id="5" value="-1" />
		<input name="l2" type="button" id="8" value="1" />
		<input name="left" type="hat" id="0" value="8" />
		<input name="pagedown" type="button" id="7" value="1" />
		<input name="pageup" type="button" id="6" value="1" />
		<input name="r2" type="button" id="9" value="1" />
		<input name="right" type="hat" id="0" value="2" />
		<input name="select" type="button" id="10" value="1" />
		<input name="start" type="button" id="11" value="1" />
		<input name="up" type="hat" id="0" value="1" />
		<input name="x" type="button" id="3" value="1" />
		<input name="y" type="button" id="4" value="1" />
	</inputConfig>

**Comment by Laddyacris** [comment]
Mise à jour, ajout de L3 et R3 qui ne passent pas sous emulationstation, obliger de le faire manuellement
la hotkey est déplacé en L3
```
  <inputConfig type="joystick" deviceName="Broadcom Bluetooth Wireless  Joystick                        " deviceGUID="0500000042726f6164636f6d20426c00">
        <input name="a" type="button" id="2" value="1" />
        <input name="b" type="button" id="1" value="1" />
        <input name="down" type="hat" id="0" value="4" />
        <input name="hotkey" type="button" id="10" value="1" />
        <input name="joystick1left" type="axis" id="0" value="-1" />
        <input name="joystick1up" type="axis" id="1" value="-1" />
        <input name="joystick2left" type="axis" id="2" value="-1" />
        <input name="joystick2up" type="axis" id="3" value="-1" />
        <input name="l2" type="button" id="6" value="1" />
<input name="l3" type="button" id="10" value="1" />
        <input name="left" type="hat" id="0" value="8" />
        <input name="pagedown" type="button" id="5" value="1" />
        <input name="pageup" type="button" id="4" value="1" />
        <input name="r2" type="button" id="7" value="1" />
<input name="r3" type="button" id="11" value="1" />
        <input name="right" type="hat" id="0" value="2" />
        <input name="select" type="button" id="8" value="1" />
        <input name="start" type="button" id="9" value="1" />
        <input name="up" type="hat" id="0" value="1" />
        <input name="x" type="button" id="3" value="1" />
        <input name="y" type="button" id="0" value="1" />
    </inputConfig>
```

**Comment by rockaddicted** [comment]
added
