### ISSUE TITLE
Game Reload doesn't work

### ISSUE THREAD

**Issue by jofett** [digitalLumberjack/recalbox-os#353]
Hello,

I played Tekken 3 on PSX with a character the storymode to unlock a new character. After i won against the last enemy, the game showed me the typcal final credits.

Now the game SHOULD restart to the main menu and the unlocked character should appear in the shortlist.

BUT I only saw a black screen and had to restart the rpi2. After I started the game again, there was no new character in the shortlist..

Is it a general mistake or is it perhaps the game?

**Comment by Didlith** [comment]
hello 

what is your game version Please 
US, JAP, PAL

thanks

**Comment by Didlith** [comment]
hello 

i test Tekken 3 in Jap version i Finish arcade Mode and i have Unlock Kuma 
idem For Julia when i finished 2 Arcade mode with 2 diferent caracters

for me its OK 

Cdlt

**Comment by rockaddicted** [comment]
The problem must be your game. Try to download/ripp another one.
I close this issue.
