### ISSUE TITLE
Berryboot Squash Image

### ISSUE THREAD

**Issue by symbios24** [digitalLumberjack/recalbox-os#355]
Hello can you Please make a Berryboot Squash Image for recalbox os if it`s possible?

Thanks

**Comment by starmagoo** [comment]
Please, I would also welcome that.

I tried some things like these: http://tldp.org/HOWTO/SquashFS-HOWTO/creatingandusing.html
and recalboxos starts but GUI start failed.

many thanks in advance!

**Comment by kvlado80** [comment]
Yes, that would be great!

**Comment by rockaddicted** [comment]
An other issue is opened about berryboot image. I close this on.
https://github.com/digitalLumberjack/recalbox-os/issues/259
