### ISSUE TITLE
Create a script that reconnect automatically the bluetooth controllers

### ISSUE THREAD

**Issue by MiguelAngelLV** [digitalLumberjack/recalbox-os#361]
I have a FC30 bluetooth gamepad. Works fine. I pair the gamepad and I play, but, when I reboot the recalbox, it not autoconnect with the gamepad I have use a keyboard to pair the gamepad again.

**Comment by digitalLumberjack** [comment]
That's why it's still a beta :D My FC30 pro reconnects automatically. What's your controller firmware version ?

**Comment by MiguelAngelLV** [comment]
I use 2.52, the last firmware. I use a FC30 and Wii U Pro Controller. Both connect ok using pair menu, when after reboot any don't reconnect

**Comment by digitalLumberjack** [comment]
Wii U pro is working in BT ?

**Comment by rockaddicted** [comment]
and wiimotes? :-p

**Comment by MiguelAngelLV** [comment]
Wii U Pro works fine, I don't try wiimotes...

2015-08-26 16:37 GMT+02:00 rockaddicted <notifications@github.com>:

> and wiimotes? :-p
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalLumberjack/recalbox-os/issues/361#issuecomment-135042685>
> .
>



-- 
Miguel Ángel López

**Comment by digitalLumberjack** [comment]
That's a good news. For the auto reconnect, i'll make a script, that will try to reconnect the X last paired bluetooth controller, for X minute at the recalbox boot.

**Comment by rockaddicted** [comment]
For information, I tried a wiimote motion plus + nunchuck. I can pair it with the bluetooth manager, but I can't map it in ES.

**Comment by Guzilli** [comment]
Good thing you are making a reconect script! That will drastically improve my experience with recalbox :)
I can confirm that Wiiu Pro Controller works perfect. Its the perfect controller imho for this project. 
Like rockaddicted i can pair a wiimote but not map it. tried it with wiimote + Classic Controller Pro.

**Comment by digitalLumberjack** [comment]
the script is working with the option : controllers.bluetooth.enabled=1 enabled

**Comment by colking** [comment]
I'm having trouble pairing wii u pro controller to recalbox with raspberry pi 2.  I'm using th asus bt400 dongle and to bluetooth devices are found.  What am I doing wrong?
