### ISSUE TITLE
aspect ratio in n64 (rice) (v3.3)

### ISSUE THREAD

**Issue by sturze** [digitalLumberjack/recalbox-os#362]
Hello!

tried to force 16/9 aspect ratio somehow... nothing worked!
tried almost every videomode (n64.videomode) and also tried to force it with
n64.ratio=16/9

any help?

**Comment by rockaddicted** [comment]
Hello sorry but you can't.
Mupen64plus is a standalone emulator, not a retroarch/libretro one, and it is configured to run in vga mode, so 640x480, a ratio 4/3 (original ratio of the n64)

**Comment by sturze** [comment]
ah.... thx!
didn't knew that...

**Comment by Seppo007** [comment]
Hi, you can achieve stretching the emulators dimensions to fit to your screen by setting following line inside of mupen64plus.cfg:

#VI Settings:
video stretch=1

you can use putty via windows to access the file
it is located in /recalbox/configs/mupen64/
