### ISSUE TITLE
écho et ralentissement sur psx (recalbox 3.3.0)

### ISSUE THREAD

**Issue by pecou** [digitalLumberjack/recalbox-os#363]
Bonjour à tous.
Depuis que je suis passé de 3.2.11 à la 3.3.0, mes jeux psx ont :
- un son double (comme un écho) très énervant, surtout dans les vidéos.
- un ralentissement sur certains jeux (metal slug x)
J'ai le fichier SCPH1001.bin dans le dossier bios.
Sur la version 3.2.11 je n'avais pas de problème.

**Comment by rockaddicted** [comment]
hello, as tu l'option rewind activée ?

**Comment by digitalLumberjack** [comment]
J'allais faire la même @rockaddicted

**Comment by pecou** [comment]
Bonjour, merci de la réponse rapide!
J'ai désactivé l'option rewind et tout est rentré dans l'ordre :)
Bon courage à l’équipe de dév.

**Comment by rockaddicted** [comment]
bonne nouvelle =)
Pour info, en 3.3.0 via recalbox.conf tu peux sélectionner les sytèmes sur lesquels activer l'option rewind.
Je t'invite à jeter un œil à la doc associée : https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf-%28EN%29

**Comment by digitalLumberjack** [comment]
Je vais quand meme ajouter ca dans la notice.
