### ISSUE TITLE
cant connect to ssh for filecopy (sftp/winscp)

### ISSUE THREAD

**Issue by sturze** [digitalLumberjack/recalbox-os#368]
is there any chance to connect to the system? (i mean NOT the smb-shares)
tried to connect via Filezilla client on port 22, no success....

the wiki-link, which should describe how to do that seems to be broken...

i need it for restoring my settings (scraped images/gamelist.xml) 
no passion to do this all over again ;)

maybe worth to add to the shares?!

**Comment by lordtaki** [comment]
SSH is handled by dropbear on recalbox.
I'm not sure there is an ftp server running.

But you can use scp (copy over ssh), it will copy and do the task fine. Or even better rsync.

If you are running windows => WinSCP

**Comment by rubencm** [comment]
With winSCP, use SCP as protocol.

**Comment by RudyProme** [comment]
I got problem to use SCP protocole to on Mac OS. An sftp server or larger samba share with password access from / could be a solution.

**Comment by BrainSlugs83** [comment]
@lordtaki -- WinSCP fails saying that there is no sftp running on the raspberry pi. -- I can ssh in just fine. -- I've used WinSCP before for other file transfers (rpi, modded consoles, etc.) -- But, I've never seen this message before -- do I have to turn something on, or launch a daemon or something to make it work?
