### ISSUE TITLE
Error on install Recalbox 3.3 beta 2 (mke2fs failed)

### ISSUE THREAD

**Issue by n4n15** [digitalLumberjack/recalbox-os#370]
French ============================================
Erreur lors de l'installation de RecalBox 3.3 beta 2 sur RPI2.

Message d'erreur:
Error creating file system
mke2fs 10.42.12 (29-Aug-2014)
Found a dos partition table in /dev/mmcblk0p6
Proceed anyway? (y,n)

C'est une boite de dialogue donc impossible de sélectionner taper y ou n.
Voir pièces jointes.

Autre informations utiles :
- Installation sur carte microSD lexar x300 64Go.
- Recalbox fonctionne sur la dernière realase stable.
- MicroSD formater en extFAT via SDformater (Quick + Format Size ajustement) puis via Gparted pour avoir du FAT32. (Procédure OK pour recalbox stable)
- La carte SD est récente.
- J'ai réessayer 3 fois sans succès.
- Retour en 3.2.11 OK.

English ===========================================

When I install Recalbox 3.3 BETA 2 on RPI2, I get an error :

Error creating file system
mke2fs 10.42.12 (29-Aug-2014)
Found a dos partition table in /dev/mmcblk0p6
Proceed anyway? (y,n)

No inputs (y nor n) are possible at this point.
See attachments.

Other useful information:
- MicroSD card is a lexar x300 64GB.
- My SD works with the latest stable realase.
- BAsicly I just format in extFAT with SDformater (Quick Format Size + adjustment) then with Gparted to got and FAT32 partition. (works with stable realese. No on beta)
- The SD card is recent.
- I try again 3 times without any success.
- Reroll in 3.2.11 OK.

![img_20150824_181449](https://cloud.githubusercontent.com/assets/996164/9447064/9032752e-4a95-11e5-991c-37eafbc602d4.jpg)
![img_20150824_180452](https://cloud.githubusercontent.com/assets/996164/9447065/9038057a-4a95-11e5-866b-e2c034def0ee.jpg)

**Comment by digitalLumberjack** [comment]
Salut, tu as quelle carte SD ?

**Comment by digitalLumberjack** [comment]
A oui essaie de formatter avec un autre logiciel. Il faut que la carte soit en fat 32

**Comment by n4n15** [comment]
Salut,

Alors comme indiqué dans le rapport, j'ai une carte MicroSDxc Lexar x300 64GB.
Elle fonctionne bien avec la version stable et les autres distro noobs
en général.
Peut-être un soucis du faite que c'est une 64GB et que le FAT gère mal
les grosses partitions?


2015-08-24 19:27 UTC+02:00, digitalLumberjack <notifications@github.com>:

**Comment by n4n15** [comment]
Pour le formatage, elle est en FAT32 quand je copie Recalbox avec noobs dessus.
En faite je la formate en 2 temps en général. Un première fois en ExtFAT (pas le choix depuis windows)
Puis en FAT32 via linux (Gparted). J'ai bien une seul partition et je copie Recalbox uniquement une fois qu'elle est en FAT32.
Le soucis est que la procédure fonctionne bien avec la version stable, mais pas avec la beta.

**Comment by digitalLumberjack** [comment]
Pourquoi tu la formatte depuis windows en premier. Si sous gparted tu fait "device" "create partition table" "msdos" et ensuite tu ajoute ta partition fat32 en primary ?

**Comment by n4n15** [comment]
En général c'est pour gagné du temps.
Sous Gparted ça m'oblige à démonter les 4 ou 5 partitions une par une. (Mon
système linux à l'auto-mount)

Je ne pense pas que ça vienne de la car ça marche avec recalbox stable /
raspian etc.

Dans le doute j'ai essayé à l'instant et ça n'avait rien changé.

Par contre après j'ai re-téléchargé la beta au cas ou l'archive serait
corrompue, et la ça à fonctionné.
Du coup je suis vraiment désolé de t'avoir dérangé, je pense juste que
l'archive était corrompue :S

Petit truc étrange que j'ai noté, je ne sais pas si c'est fait exprès mais
noobs lance l'installation directement sans rien me demander et redémarre à
la fin tout seul.
C'est pas un problème car c'est bien la version RPi2 qui s'installe mais au
cas oû je te fait remonter.

Du coup, merci bien dans tous les cas pour ton aide et recalbox en général
! T'es vraiment au top.
Désolé encore une fois pour t'avoir dérangé pour rien. #boulet

J'espère pouvoir filé un coup de main un peut plus utile avec les bugs à
l'avenir, en tout cas je n'y manquerais pas.
Passe une bonne soirée.

2015-08-24 19:43 GMT+02:00 digitalLumberjack <notifications@github.com>:

**Comment by digitalLumberjack** [comment]
Oui c'est une feature l'auto install, pour les habitué ca fait bizard, mais plus besoin de clavier pour installer :P
COntent que ca mrche :D
