### ISSUE TITLE
Multiplayer doesn´t work at N64

### ISSUE THREAD

**Issue by Reick** [digitalLumberjack/recalbox-os#371]
Hello,
I have a Big Problem that two original N64 doesn´t work at a multiplayer game.
I use a Mayflash Adapter from N64 to USB.
In singleuser games works the first controller perfectly. The second controller works in EmuStation Menu. 
Have somebody a idea? Thanks for help

**Comment by sturze** [comment]
did you initialize both controller (press all the buttons stuff... )?

**Comment by Reick** [comment]
Yes, I configure both controller.

**Comment by sturze** [comment]
Also selected both configurations for each Controller in The menu? (Not default! Controllername and #2)?

**Comment by Reick** [comment]
Of Course, I selected in the Emustation both Controller. A picture of that cooming in the next few minutes.

**Comment by digitalLumberjack** [comment]
Hi @Reick, the n64 emulator is still in beta mode, and is not a retroarch libretro. It's a standalone emulator, mupen64plus. The autoconfiguration from ES has not been implemented yet so it has only the controller config of it's own autoconfig system. You should take a look at it.

**Comment by sturze** [comment]
just to get it right... it works in other emulators?
is your paste of retroarchcustom complete?
found:
input_player1_joypad_index = 0
but no
input_player2_joypad_index = 1

**Comment by rockaddicted** [comment]
Hi in french forum section, you have a tuto about "how to configure your n64 controler".
Try with google translator, I won't have time to translate it today....
Give a look in english forum, maybe you will find these informations.

http://blog.recalbox.com/forums/topic/configuration-manette-mupen64plus/

**Comment by Reick** [comment]
Thank you so much guys. I have try something last night and it works now.  The config file HuiJai ...USB is now duplicated in Hui...USB2.cfg. Then in mupen64 config i have change the names of Controller. Restart and it works now with two Controllers. Sorry for my English. 
@rockaddicted I read the information later.

**Comment by rockaddicted** [comment]
good news, so I close the issue.

**Comment by Reick** [comment]
Hello Guys, 
The good news are gone. Since yesterday i try to configure 4 original n64 Controller. Three Controller works in the Games, but der third doesn´t work in games. In Emulation Station frontend is no problem with control.
Here my mupen64.cfg

# cat mupen64plus.cfg
# Mupen64Plus Configuration File
# This file is automatically read and written by the Mupen64Plus Core library

[Audio-SDL]

# Mupen64Plus SDL Audio Plugin config parameter version number
Version = 1
# Frequency which is used if rom doesn't want to change it
DEFAULT_FREQUENCY = 33600
# Swaps left and right channels
SWAP_CHANNELS = False
# Size of primary buffer in output samples. This is where audio is loaded after it's extracted from n64's memory.
PRIMARY_BUFFER_SIZE = 16384
# Fullness level target for Primary audio buffer, in equivalent output samples
PRIMARY_BUFFER_TARGET = 10240
# Size of secondary buffer in output samples. This is SDL's hardware buffer.
SECONDARY_BUFFER_SIZE = 2048
# Audio resampling algorithm. src-sinc-best-quality, src-sinc-medium-quality, src-sinc-fastest, src-zero-order-hold, src-linear, speex-fixed-{10-0}, trivial
RESAMPLE = "trivial"
# Volume control type: 1 = SDL (only affects Mupen64Plus output)  2 = OSS mixer (adjusts master PC volume)
VOLUME_CONTROL_TYPE = 1
# Percentage change each time the volume is increased or decreased
VOLUME_ADJUST = 5
# Default volume when a game is started.  Only used if VOLUME_CONTROL_TYPE is 1
VOLUME_DEFAULT = 80


[AutoConfig1]

device = 1
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = "100,100"
AnalogPeak = "20000,20000"
DPad R = "button(29)"
DPad L = "button(31)"
DPad D = "button(30)"
DPad U = "button(28)"
Start = "button(25)"
Z Trig = "button(24)"
B Button = "button(18)"
A Button = "button(17)"
C Button R = "axis(7-)"
C Button L = "axis(7+)"
C Button D = "axis(6+)"
C Button U = "axis(6-)"
R Trig = "button(23)"
L Trig = "button(22)"
Mempak switch = "key(109)"
Rumblepak switch = "key(114)"
X Axis = "axis(4-,4+)"
Y Axis = "axis(5-,5+)"


[Core]

# Mupen64Plus Core config parameter set version number.  Please don't change this version number.
Version = 1.010000
# Draw on-screen display if True, otherwise don't draw OSD
OnScreenDisplay = True
# Use Pure Interpreter if 0, Cached Interpreter if 1, or Dynamic Recompiler if 2 or more
R4300Emulator = 2
# Disable compiled jump commands in dynamic recompiler (should be set to False)
NoCompiledJump = False
# Disable 4MB expansion RAM pack. May be necessary for some games
DisableExtraMem = False
# Increment the save state slot after each save operation
AutoStateSlotIncrement = False
# Activate the R4300 debugger when ROM execution begins, if core was built with Debugger support
EnableDebugger = False
# Save state slot (0-9) to use when saving/loading the emulator state
CurrentStateSlot = 0
# Path to directory where screenshots are saved. If this is blank, the default value of ${UserConfigPath}/screenshot will be used
ScreenshotPath = ""
# Path to directory where emulator save states (snapshots) are saved. If this is blank, the default value of ${UserConfigPath}/save will be used
SaveStatePath = ""
# Path to directory where SRAM/EEPROM data (in-game saves) are stored. If this is blank, the default value of ${UserConfigPath}/save will be used
SaveSRAMPath = ""
# Path to a directory to search when looking for shared data files
SharedDataPath = "/recalbox/configs/mupen64/"
# Delay interrupt after DMA SI read/write
DelaySI = True
# Force number of cycles per emulated instruction
CountPerOp = 0


[CoreEvents]

# Mupen64Plus CoreEvents config parameter set version number.  Please don't change this version number.
Version = 1
# SDL keysym for stopping the emulator
Kbd Mapping Stop = 27
# SDL keysym for switching between fullscreen/windowed modes
Kbd Mapping Fullscreen = 0
# SDL keysym for saving the emulator state
Kbd Mapping Save State = 286
# SDL keysym for loading the emulator state
Kbd Mapping Load State = 288
# SDL keysym for advancing the save state slot
Kbd Mapping Increment Slot = 0
# SDL keysym for resetting the emulator
Kbd Mapping Reset = 290
# SDL keysym for slowing down the emulator
Kbd Mapping Speed Down = 291
# SDL keysym for speeding up the emulator
Kbd Mapping Speed Up = 292
# SDL keysym for taking a screenshot
Kbd Mapping Screenshot = 293
# SDL keysym for pausing the emulator
Kbd Mapping Pause = 112
# SDL keysym for muting/unmuting the sound
Kbd Mapping Mute = 109
# SDL keysym for increasing the volume
Kbd Mapping Increase Volume = 93
# SDL keysym for decreasing the volume
Kbd Mapping Decrease Volume = 91
# SDL keysym for temporarily going really fast
Kbd Mapping Fast Forward = 102
# SDL keysym for advancing by one frame when paused
Kbd Mapping Frame Advance = 47
# SDL keysym for pressing the game shark button
Kbd Mapping Gameshark = 103
# Joystick event string for stopping the emulator
Joy Mapping Stop = "J1B0"
# Joystick event string for switching between fullscreen/windowed modes
Joy Mapping Fullscreen = ""
# Joystick event string for saving the emulator state
Joy Mapping Save State = ""
# Joystick event string for loading the emulator state
Joy Mapping Load State = ""
# Joystick event string for advancing the save state slot
Joy Mapping Increment Slot = ""
# Joystick event string for taking a screenshot
Joy Mapping Screenshot = ""
# Joystick event string for pausing the emulator
Joy Mapping Pause = ""
# Joystick event string for muting/unmuting the sound
Joy Mapping Mute = ""
# Joystick event string for increasing the volume
Joy Mapping Increase Volume = ""
# Joystick event string for decreasing the volume
Joy Mapping Decrease Volume = ""
# Joystick event string for fast-forward
Joy Mapping Fast Forward = ""
# Joystick event string for pressing the game shark button
Joy Mapping Gameshark = ""


[Input-SDL-Control1]

# Mupen64Plus SDL Input Plugin config parameter version number.  Please don't change this version number.
version = 2
# Controller configuration mode: 0=Fully Manual, 1=Auto with named SDL Device, 2=Fully automatic
mode = 1
# Specifies which joystick is bound to this controller: -1=No joystick, 0 or more= SDL Joystick number
device = 0
# SDL joystick name (or Keyboard)
name = "HuiJia  USB GamePad"
# Specifies whether this controller is 'plugged in' to the simulated N64
plugged = True
# Specifies which type of expansion pak is in the controller: 1=None, 2=Mem pak, 5=Rumble pak
plugin = 2
# If True, then mouse buttons may be used with this controller
mouse = False
# Scaling factor for mouse movements.  For X, Y axes.
MouseSensitivity = "2.00,2.00"
# The minimum absolute value of the SDL analog joystick axis to move the N64 controller axis value from 0.  For X, Y axes.
AnalogDeadzone = "100,100"
# An absolute value of the SDL joystick axis >= AnalogPeak will saturate the N64 controller axis value (at 80).  For X, Y axes. For each axis, this must be greater than the corresponding AnalogDeadzone value
AnalogPeak = "20000,20000"
# Digital button configuration mappings
DPad R = "button(13)"
DPad L = "button(15)"
DPad D = "button(14)"
DPad U = "button(12)"
Start = "button(9)"
Z Trig = "button(8)"
B Button = "button(2)"
A Button = "button(1)"
C Button R = "axis(3-)"
C Button L = "axis(3+)"
C Button D = "axis(2+)"
C Button U = "axis(2-)"
R Trig = "button(7)"
L Trig = "button(6)"
Mempak switch = "key(109)"
Rumblepak switch = "key(114)"
# Analog axis configuration mappings
X Axis = "axis(0-,0+)"
Y Axis = "axis(1-,1+)"


[Input-SDL-Control2]

# Mupen64Plus SDL Input Plugin config parameter version number.  Please don't change this version number.
version = 2
# Controller configuration mode: 0=Fully Manual, 1=Auto with named SDL Device, 2=Fully automatic
mode = 1
# Specifies which joystick is bound to this controller: -1=No joystick, 0 or more= SDL Joystick number
device = 1
# SDL joystick name (or Keyboard)
name = "HuiJia  USB GamePad 2"
# Specifies whether this controller is 'plugged in' to the simulated N64
plugged = True
# Specifies which type of expansion pak is in the controller: 1=None, 2=Mem pak, 5=Rumble pak
plugin = 2
# If True, then mouse buttons may be used with this controller
mouse = False
# Scaling factor for mouse movements.  For X, Y axes.
MouseSensitivity = "2.00,2.00"
# The minimum absolute value of the SDL analog joystick axis to move the N64 controller axis value from 0.  For X, Y axes.
AnalogDeadzone = "100,100"
# An absolute value of the SDL joystick axis >= AnalogPeak will saturate the N64 controller axis value (at 80).  For X, Y axes. For each axis, this must be greater than the corresponding AnalogDeadzone value
AnalogPeak = "20000,20000"
# Digital button configuration mappings
DPad R = "button(13)"
DPad L = "button(15)"
DPad D = "button(14)"
DPad U = "button(12)"
Start = "button(9)"
Z Trig = "button(8)"
B Button = "button(2)"
A Button = "button(1)"
C Button R = "axis(3-)"
C Button L = "axis(3+)"
C Button D = "axis(2+)"
C Button U = "axis(2-)"
R Trig = "button(7)"
L Trig = "button(6)"
Mempak switch = "key(109)"
Rumblepak switch = "key(114)"
# Analog axis configuration mappings
X Axis = "axis(0-,0+)"
Y Axis = "axis(1-,1+)"


[Input-SDL-Control3]

# Mupen64Plus SDL Input Plugin config parameter version number.  Please don't change this version number.
version = 2
# Controller configuration mode: 0=Fully Manual, 1=Auto with named SDL Device, 2=Fully automatic
mode = 0
# Specifies which joystick is bound to this controller: -1=No joystick, 0 or more= SDL Joystick number
device = 2
# SDL joystick name (or Keyboard)
name = "HuiJia  USB GamePad 3"
# Specifies whether this controller is 'plugged in' to the simulated N64
plugged = True
# Specifies which type of expansion pak is in the controller: 1=None, 2=Mem pak, 5=Rumble pak
plugin = 2
# If True, then mouse buttons may be used with this controller
mouse = False
# Scaling factor for mouse movements.  For X, Y axes.
MouseSensitivity = "2.00,2.00"
# The minimum absolute value of the SDL analog joystick axis to move the N64 controller axis value from 0.  For X, Y axes.
AnalogDeadzone = "100,100"
# An absolute value of the SDL joystick axis >= AnalogPeak will saturate the N64 controller axis value (at 80).  For X, Y axes. For each axis, this must be greater than the corresponding AnalogDeadzone value
AnalogPeak = "20000,20000"
# Digital button configuration mappings
DPad R = "button(29)"
DPad L = "button(31)"
DPad D = "button(30)"
DPad U = "button(28)"
Start = "button(25)"
Z Trig = "button(24)"
B Button = "button(18)"
A Button = "button(17)"
C Button R = "axis(7-)"
C Button L = "axis(7+)"
C Button D = "axis(6+)"
C Button U = "axis(6-)"
R Trig = "button(23)"
L Trig = "button(22)"
Mempak switch = "key(109)"
Rumblepak switch = "key(114)"
# Analog axis configuration mappings
X Axis = "axis(4-,4+)"
Y Axis = "axis(5-,5+)"


[Input-SDL-Control4]

# Mupen64Plus SDL Input Plugin config parameter version number.  Please don't change this version number.
version = 2
# Controller configuration mode: 0=Fully Manual, 1=Auto with named SDL Device, 2=Fully automatic
mode = 0
# Specifies which joystick is bound to this controller: -1=No joystick, 0 or more= SDL Joystick number
device = 3
# SDL joystick name (or Keyboard)
name = "HuiJia  USB GamePad 4"
# Specifies whether this controller is 'plugged in' to the simulated N64
plugged = True
# Specifies which type of expansion pak is in the controller: 1=None, 2=Mem pak, 5=Rumble pak
plugin = 2
# If True, then mouse buttons may be used with this controller
mouse = False
# Scaling factor for mouse movements.  For X, Y axes.
MouseSensitivity = "2.00,2.00"
# The minimum absolute value of the SDL analog joystick axis to move the N64 controller axis value from 0.  For X, Y axes.
AnalogDeadzone = "100,100"
# An absolute value of the SDL joystick axis >= AnalogPeak will saturate the N64 controller axis value (at 80).  For X, Y axes. For each axis, this must be greater than the corresponding AnalogDeadzone value
AnalogPeak = "20000,20000"
# Digital button configuration mappings
DPad R = "button(13)"
DPad L = "button(15)"
DPad D = "button(14)"
DPad U = "button(12)"
Start = "button(9)"
Z Trig = "button(8)"
B Button = "button(2)"
A Button = "button(1)"
C Button R = "axis(3-)"
C Button L = "axis(3+)"
C Button D = "axis(2+)"
C Button U = "axis(2-)"
R Trig = "button(7)"
L Trig = "button(6)"
Mempak switch = "key(109)"
Rumblepak switch = "key(114)"
# Analog axis configuration mappings
X Axis = "axis(0-,0+)"
Y Axis = "axis(1-,1+)"


[UI-Console]

# Mupen64Plus UI-Console config parameter set version number.  Please don't change this version number.
Version = 1
# Directory in which to search for plugins
PluginDir = "./"
# Filename of video plugin
VideoPlugin = "/usr/lib/mupen64plus/mupen64plus-video-n64.so"
# Filename of audio plugin
AudioPlugin = "mupen64plus-audio-sdl.so"
# Filename of input plugin
InputPlugin = "mupen64plus-input-sdl.so"
# Filename of RSP plugin
RspPlugin = "mupen64plus-rsp-hle.so"


[Video-General]
