### ISSUE TITLE
Add default shader system

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#372]
Add an option in ES that will activate the default shader for all systems.
The default shaders will be the best settings for a system, defined by the community.

**Comment by digitalLumberjack** [comment]
After some discussions : 
Let user choose between shaders sets : 
None, Bestset (a choosen shader per emulator), Scanlines (just scanlines for all emulators), Other ???

- None is default, it will use recalbox.conf shaders configuration
- Bestset will use a set of shaders predefinied, and choosen by the community as the "best solution" for having an image corresponding to the original one.
- Scanlines will set only scanlines for all emulators

**Comment by rockaddicted** [comment]
To do : 
- add this pack to the root of ```/recalbox/share/shaders``` :    
https://mega.nz/#!iI1lHRhD!VXEzYGhz_JFXpGWIXgZauP2z72zOf8b4_6xEXkYZ0Pg
- select "the best shader" for each system
- add to configgen the mapping of this, to switch in-game between presets :   
```input_shader_next_btn = ""```   
```input_shader_prev_btn = ""```

**Comment by rockaddicted** [comment]
After testing shaders on my TV, here is my list of presets for the "best shaders" :  
- **SNES** : crt-caligari_gamma_115
- **NES** : crt-caligari_gamma_115
- **GBA** : lcd3x_gamma_115
- **GBC** : dot ou lcd3x_gamma_115
- **GB** : dot-green2
- **Mégadrive** : crt-caligari
- **Master System** : crt-caligari_gamma_115
- **Game Gear** : scanline_gamma_115
- **PC-Engine** : crt-caligari
- **FBA_Libretro** : crt-caligari_gamma_115
- **MAME** : crt-caligari_gamma_115
- **NeoGeo** : crt-caligari_gamma_125
- **Lynx** : lcd3x_gamma_125
- **NGP** : lcd3x
- **WSWAN** : lcd3x_gamma_115
- **PRBoom** : crt-caligari_gamma_115

**Comment by digitalLumberjack** [comment]
done with beta 5
The mastersystem retro shader will be corrected in beta6

**Comment by rockaddicted** [comment]
I can't switch in game shader using the special command HK+R3/L3.
