### ISSUE TITLE
Switch defaut webserver port in Kodi

### ISSUE THREAD

**Issue by rockaddicted** [digitalLumberjack/recalbox-os#375]
Defaut webserver port is 80, we need to switch it in 8081.

**Comment by Didlith** [comment]
hello 

i'm try to modify the file guisettings.xml in /root/.kodi/userdata/
for attributed 8081 to the Kodi Webserver

however when i go on settings in Kodi the port for the Webserver cannot change whit my manual modification

cdly

**Comment by digitalLumberjack** [comment]
Isn't it ok now ?

**Comment by digitalLumberjack** [comment]
@rockaddicted ?

**Comment by digitalLumberjack** [comment]
Verified, all is ok. 
https://github.com/digitalLumberjack/recalbox-os/wiki/Kodi-on-recalbox-%28EN%29
