### ISSUE TITLE
Share (smb) emulationstation gamelists and themes folder's

### ISSUE THREAD

**Issue by Dany21000** [digitalLumberjack/recalbox-os#381]
This request for easily ad/remove themes for emulationstation.

And gamelist, for put content directly scrapped from a computer, or replace an image, etc ...

**Comment by rockaddicted** [comment]
Yep indeed it is in the todo list.
But not for the 3.3.0 ^^

**Comment by rockaddicted** [comment]
This will be done in the same time than this issue : https://github.com/digitalLumberjack/recalbox-os/issues/381
So I close this one.
