### ISSUE TITLE
3rd joypad PS3 not detected on rpi2

### ISSUE THREAD

**Issue by enpix** [digitalLumberjack/recalbox-os#384]
When you connect the 3rd PS3 joypad (sixasis) with bluetooth. On Rpi 1, the third joypad is ok, but on rpi 2 the third joypad still blinking. The bug was present on 3.3 and 3.2.11.

**Comment by rockaddicted** [comment]
Hi you have already opened an issue about that. So I close this one.
https://github.com/digitalLumberjack/recalbox-os/issues/224

**Comment by rockaddicted** [comment]
this issue too is opened https://github.com/digitalLumberjack/recalbox-os/issues/345
