### ISSUE TITLE
Buttons in UI wrong

### ISSUE THREAD

**Issue by Nidhoegger** [digitalLumberjack/recalbox-os#389]
Hello,

i use recalbox using XBox 360 wireless controller. Detection works flawless! But the UI always states that the A-Button is used to accept. But its instead the B button, A button triggers the back action. Which is really confusing.

**Comment by rockaddicted** [comment]
Hi it not really a problem. To have a standard in the configuration generator, it was decided to use a snes layout to map controlers.
When the mapper in emulation ask you to press the A button, press the B button on you xbox pad etc...

| xbox pad | snes pad |
| :--------------: | :--------------: |
| A | B |
| A | B |
| A | B |

**Comment by digitalLumberjack** [comment]
Your table is so sexy @rockaddicted maybe we could add it to the wiki
