### ISSUE TITLE
Splash screens when restarting or stopping

### ISSUE THREAD

**Issue by lordtaki** [digitalLumberjack/recalbox-os#391]
Depending on the number of roms, emulation station can take a while before stopping.
20000+ roms => 10 minutes to stop

During this period the screen is black and an user can be tempted to think the raspberry is stopped correctly or that the reboot has a problem.

Maybe displaying, depending on the action asked, messages like:
- reboot on going please wait
- system shutting down please wait for black screen to turn off your device

Even better would be a progress bar linked to emulation station advancement.
When I monitor the action stop for ES I watch for the timestamp of the gamelist.xml files.

**Comment by digitalLumberjack** [comment]
Good idea.

**Comment by digitalLumberjack** [comment]
:+1:

**Comment by rockaddicted** [comment]
https://github.com/digitalLumberjack/recalbox-os/issues/450
I close this one.
