### ISSUE TITLE
No PVR add-ons with Recalbox Kodi install

### ISSUE THREAD

**Issue by mrpollif** [digitalLumberjack/recalbox-os#40]
It appears that the default Kodi install for Linux does not come bundled with PVR add-ons. They need to be installed separately as per the following:

http://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux

I expect that several people might be disappointed by this omission. Can we have these included in the next release?

**Comment by digitalLumberjack** [comment]
Yes i'm trying to make it work. I build the pvr support in kodi. Aren't plugins installable from the plugin menu in kodi ?

**Comment by mrpollif** [comment]
Unfortunately not. The PVR plugins are not in the Kodi repository. As far as I can see these need to be installed via apt-get install before you can enable them in Kodi.

**Comment by digitalLumberjack** [comment]
I'm compiling the last version of the pvr addons while adding the mysql support. Maybe it will help.

**Comment by mrpollif** [comment]
Yes, was looking into that myself. It seems that they just have to be in a specific libs folder for Kodi to find them and let you install them through the add add-ons menu. 

https://github.com/opdenkamp/xbmc-pvr-addons

Thank you for doing this.

**Comment by digitalLumberjack** [comment]
if i ls /usr/share/kodi/addons/ i see all addons i compiled.
Then how do you enable them with a standard kodi ?

**Comment by mrpollif** [comment]
From instructions I have read about compiling and installing the PVR add-ons, Kodi first needs a restart after adding them to the kodi directory. After this you should have two choices (as long as kodi recognises the pvr add-ons).

1) you should see a PVR category in the section where you normally install standard Kodi add-ons from. You should be able to add from there. Vu-plus is the one I am most interested in as that is my back-end.

2) the other option is to go to live-tv in settings page and enabling live-tv there. Kodi should then prompt you to select the pvr add-on you need from there.

If you can now see the add-on listed and would like me to retest, let me know and send me a link to download disk image from. I will then install on my spare sd card. Note that I am using a raspberry pi2, not 1.

On 4 March 2015 16:48:24 GMT+00:00, digitalLumberjack <notifications@github.com> wrote:
>if i ls /usr/share/kodi/addons/ i see all addons i compiled.
>Then how do you enable them with a standard kodi ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/digitalLumberjack/recalbox-os/issues/40#issuecomment-77195334

Regards, 

--Paul.

**Comment by digitalLumberjack** [comment]
I managed to enable pvr addons they are all in DISABLED addons. Could you
give it a try ?

**Comment by mrpollif** [comment]
Great news. Thank you. I will give it a try. ...where can I download the update from? ...It was not in disabled add-ons before so look forward to trying with updated image.

**Comment by digitalLumberjack** [comment]
You just update from the menu

**Comment by mrpollif** [comment]
I tried this last night and am very happy to report that it worked exactly as it should (for VuPlus PVR addon at least). Thank you very much for doing this.

On a separate topic... I would prefer to boot into Kodi and launch emulationstation from in there. I know how to launch it from within kodi and know - at least for Raspbian - how to make kodi auto start. Is there anything different about how I should do this in Recalbox? ...can I just Ssh in and change configs in normal way?

**Comment by digitalLumberjack** [comment]
That is a really good news.
You can use the recalbox.conf https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf-(EN) to start kodi automatically.
