### ISSUE TITLE
Raspbian install

### ISSUE THREAD

**Issue by jaumard** [digitalLumberjack/recalbox-os#411]
Is there any possibility to have this by "apt-get install" or something to install it on raspbian OS ?? 

Because I want to use raspbian for basic computing and launch recalbox to make play some retro games.

Thanks

**Comment by digitalLumberjack** [comment]
Hi. No never. It's like asking if you can install debian on fedora. There is the dual boot solution though

**Comment by jaumard** [comment]
Thanks! I understand, another question before closing this post. Do RecalBox have an API (HTTP or from command line) ? For launching console and game from external interface ? That would be nice.

**Comment by digitalLumberjack** [comment]
No there is nothing like that :)

**Comment by jaumard** [comment]
That's a pity ^^ think about it it can be cool ;) thanks for your time.
