### ISSUE TITLE
Add psutil Python library into the next beta release

### ISSUE THREAD

**Issue by sveetch** [digitalLumberjack/recalbox-os#413]
Like i said to @digitalLumberjack it would be nice to have the psutil lib available into the next beta so the recalbox-manager can display some system infos like cpu/memory/disk usage on homepage.

http://git.buildroot.net/buildroot/commit/?id=5be4d61943ce283da75dabb684a13fcc039c2faa

**Comment by digitalLumberjack** [comment]
Will be.

**Comment by digitalLumberjack** [comment]
It is. 3.3.0 beta 5
