### ISSUE TITLE
4:3 screen

### ISSUE THREAD

**Issue by tchernobil** [digitalLumberjack/recalbox-os#414]
I try to set a 4:3 screen in recal.conf:

global.videomode=DMT 35 HDMI
audio.device=jack

The audio work, but the "videomode" is not recognize. I try number 16 (1024X768) and it does'nt work. Recalbox box boot in 16:9.

**Comment by digitalLumberjack** [comment]
THis is the video mode for games. You should edit the config.txt to set the boot video mode : https://github.com/digitalLumberjack/recalbox-os/wiki/Edit-the-config.txt-file-(EN)

**Comment by tchernobil** [comment]
I put in config.txt:

hdmi_group=2
hdmi_mode=35
audio_output=jack

And it works fine. Thank you.

**Comment by digitalLumberjack** [comment]
Great news !
