### ISSUE TITLE
Second Player Atari 2600 Emulator

### ISSUE THREAD

**Issue by DarthNeo2** [digitalLumberjack/recalbox-os#417]
Fix the second player in atari 2600 emulator, i have tested the new beta and this bug stil there, the second control simply dont work. Thanks.

**Comment by digitalLumberjack** [comment]
I think the emulator is in cause here. Do you have two player game titles for the community to test ?

**Comment by DarthNeo2** [comment]
Boxing and tennis are examples of two player games for the test.

**Comment by rockaddicted** [comment]
I upgraded the core and the problem should be fixed.
So wait the futur beta 9 and test it.
I close this issue. Don't hesitate to reopen ot if the problem was not fixed.

Another issue about this problem : 
https://github.com/digitalLumberjack/recalbox-os/issues/448
