### ISSUE TITLE
Hide/disable Overclock settings

### ISSUE THREAD

**Issue by DarthNeo2** [digitalLumberjack/recalbox-os#418]
Sorry my bad english, i use google translate.

I would like to be able to hide the overclocking option in the new version of Recalbox, this is very important because several users without technical knowledge will use this option without knowing if have any sink or cooler inside your raspberry pi,i made a test without the sink and I had problems after with my SD card.  I think the most correct would be the option to hide the overclocking as is done with Kodi, the option would be available only for those who want and know what you're doing, in my view it fits better in the proposal of Recalbox, its very important.

**Comment by digitalLumberjack** [comment]
Hi @DarthNeo2. First i would like to ask you what is "the proposal of Recalbox" you mean in your message ?

**Comment by DarthNeo2** [comment]
I think it would be as a system for home console, the common User friendly and deep for advanced users, if not this just sincerely apologize for the inconvenience, but I believe that putting this option would be very useful. Thank you and Congratulations for your excellent work

**Comment by digitalLumberjack** [comment]
The common user want to be able to overclock the rpi without having to modify config.txt. I'll let the overclock option. We may slow down the ram clock a little bit to make the rpi2 more stable.
