### ISSUE TITLE
 Problems with App Yatse

### ISSUE THREAD

**Issue by bogi1102** [digitalLumberjack/recalbox-os#420]
Problems with App Yatse. The app does not find a host even though everything is on the same network. Handy and Recalbox.

**Comment by rockaddicted** [comment]
Which recalbox's version please? 3.2.11 or 3.3.0?
I'm using yatse with the two version ...

**Comment by bogi1102** [comment]
3.3.0

**Comment by bogi1102** [comment]
What settings you have made here in Kodi?

**Comment by Jayrayme** [comment]
Manual connection in yatse + port 8081 by default worked for me after 1h or research

**Comment by rockaddicted** [comment]
In the beta 8, the defaut server port should be automaticaly set on 8081 value.
Someone can check it please ?

**Comment by bogi1102** [comment]
Thank you so it worked.

**Comment by bogi1102** [comment]
Can not set the automatically detect Wi-Fi and you get a list to choose one? And a keypad appears to enter the Key?

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-os/wiki/Kodi-on-recalbox-%28EN%29
