### ISSUE TITLE
 Kodi upgrade to 15 Isengard?

### ISSUE THREAD

**Issue by bogi1102** [digitalLumberjack/recalbox-os#421]
It is also on the Recalbox 3.3.0 Beta 4 no new Kodi plan, you can upgrade it manually?

**Comment by rockaddicted** [comment]
If you had read the issues, you would have seen an opened issue about kodi 15.1, and seen that is planned for the 3.3.1.
https://github.com/digitalLumberjack/recalbox-os/issues/280

**Comment by bogi1102** [comment]
Thank you for this Answer
