### ISSUE TITLE
Kodi Controller Control

### ISSUE THREAD

**Issue by bogi1102** [digitalLumberjack/recalbox-os#422]
Kodi can not be controlled via controller NES30Pro

**Comment by rockaddicted** [comment]
Controlers don't work with Kodi on recalbox. An issue is already open about that.
You can get a look and help to solve this.
https://github.com/digitalLumberjack/recalbox-os/issues/12

**Comment by bogi1102** [comment]
Can be happy to help. Have good programming skills
