### ISSUE TITLE
8bit NES30Pro problem

### ISSUE THREAD

**Issue by bogi1102** [digitalLumberjack/recalbox-os#423]
8bit NES30Pro problem. but has detected no function during play.

**Comment by digitalLumberjack** [comment]
Could you check again with 3.3.0 beta 5 ?

**Comment by bogi1102** [comment]
The controller does connect. But it starts in the game, for example, in Mario Kart. Once the game no longer functional nor the hotkey.

Even Nintendo 64 games like Mortal Kombat (Europe), he finds no controller

Tested with 3.3.0 Beta 5

**Comment by digitalLumberjack** [comment]
Are you with the last firmware ? 
https://github.com/digitalLumberjack/recalbox-os/wiki/8bitdo-on-recalbox-(EN)

**Comment by bogi1102** [comment]
How do I find out the current firmware on the controller?

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-os/wiki/8bitdo-on-recalbox-(EN) here

**Comment by bogi1102** [comment]
Hello Community

So Latest Firmware at Recalbox:
3.3.0 Beta 6
NES30 Pro with firmware 1.62 (latest)

There is are 2 NES30 Pro now connected.
1 with firmware 1.61 and 1 with firmware 1.62

Both are identified with different names via Bluetooth.

If I start with 1 Controller Mario Kart works as far as the control. but when I run Super Mario World with 1 controller goes nothing.

  But if I then the controller 2 Start in Super Mario World, I can play with the 2 controller. Hotkey only works on the 1 to exit the game.

N64 is still detected no controller in Mortal Kombat Trilogy.

**Comment by rockaddicted** [comment]
Yes it is a known problem with the snes game "super mario allstar" and the defaut core "pocketsnes".
If you want to correct it, switch snes core in recalbox.conf.
snes9x_next run well with this game and the first controller.

This problem is not specific to recalbox, it is a bug on all other gaming OS on rpi using this core, and with every controllers, not only 8Bits.
This core, pockersnes, is set by defaut, because, it is the snes core that have the best framerate on rpi1.

**Comment by bogi1102** [comment]
Which settings have to be made here and just work then the other games yet? Or must then be converted back here?

**Comment by rockaddicted** [comment]
Sorry for the late answer.
Do you have ever a problem to switch on snes9x_next core an recalbox 3.3.0 beta ?

**Comment by bogi1102** [comment]
had tested it yesterday again and the problem still exists. Except when I anschliese 2 Controller then it goes. But have not yet changed the settings.

Have also the problem that he at no Mortal Kombat Controller also recognizes the Nintendo 64th
