### ISSUE TITLE
add nx-engine core to the system

### ISSUE THREAD

**Issue by rockaddicted** [digitalLumberjack/recalbox-os#426]

**Comment by rockaddicted** [comment]
Must add zoid theme.

**Comment by Dragda** [comment]
Don't work with the official spanish translation of the game. Charges the intro of The doctor, and when he goes to the menu kicks you out into emulationstation

The original seems to work (with text glitches). The pre-patched english version works well.

**Comment by rockaddicted** [comment]
Yes indeed an issue is open on the libretro github. If the problem is resolved in the futur, we'll update the core in recalbox.
For the moment, like said in the readme, you can play with the english language ^^

**Comment by rockaddicted** [comment]
zoid theme added
