### ISSUE TITLE
Test piFBA retroach core on RPi2

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#43]
Street Fighter 3 third strike ???

**Comment by digitalLumberjack** [comment]
OMG

**Comment by digitalLumberjack** [comment]
OOOOOMMMMMGGGGGG

**Comment by frthery** [comment]
Hi, i suppose you have use this repository: https://github.com/libretro/libretro-fba ?

Do you use a spécial profile to compile ? 

profile := accuracy
ifeq ($(profile),accuracy)
	PROFFLAGS := -DPROFILE_ACCURACY
	SH2_CPU_DIR := $(FBA_CPU_DIR)/sh2
else ifeq ($(profile),balanced)
	PROFFLAGS := -DPROFILE_BALANCED
	SH2_CPU_DIR := $(FBA_CPU_DIR)/sh2
else ifeq ($(profile),performance)
	PROFFLAGS := -DPROFILE_PERFORMANCE
	SH2_CPU_DIR := $(FBA_CPU_DIR)/alt/sh2
else
	$(error unknown profile.)
endif

it seems that accuracy profile is hard coded.

I have compiled core for my PI1 but i have poor performances in comparison with pifba.
I am curious to know about performances on PI2 ?

**Comment by digitalLumberjack** [comment]
Hi, i use the performance profile on rpi2, balanced and accuracy ask too much processor.
And it runs well street fighter 3 third strike and every other games i tried ;)

**Comment by frthery** [comment]
nice! Thanks for your answer.
