### ISSUE TITLE
Problems connecting to wifi in v3.3.0-beta-7 (but not v3.2.11)

### ISSUE THREAD

**Issue by gremlinPots** [digitalLumberjack/recalbox-os#439]
Having some trouble with connecting to wifi with 3.3.0 beta 7, but worked perfectly in 3.2.11. When I first go into the network settings the default IP given isn't the home network (should be 192.168.1.X).

I've tried setting the details to static in etc/network/interfaces and manually added the wifi details, which means the IP address is then correct in the menu, but wifi still refuses to connect.

**Comment by digitalLumberjack** [comment]
Hi, the avahi daemon is really annoying and fail the wifi. We're on it.

**Comment by laserline** [comment]
Same here. Cannot connect to wifi after upgrading to beta 7. Good to know it's being worked on.

**Comment by rockaddicted** [comment]
This problem should be solved in the beta 8. Can you test and confirm it, please ?

**Comment by laserline** [comment]
Yes it is working now. The new theme is also working properly (it crashed
last time for me). Recalbox is a great piece of software. Keep it up!

**Comment by rockaddicted** [comment]
Good new.
What is the new theme that you are talking about ? Zoid ?
For information, when you have a lot of systems activated in recalbox (about 25), we recommand to use as theme simplelight (the default one). It is more secure to don't have any boot/crashs problems.

So I close this issue.
