### ISSUE TITLE
GBA Save Format

### ISSUE THREAD

**Issue by Kinghoff** [digitalLumberjack/recalbox-os#440]
The GBA Emulator doesn't support games w/ 128k save format like Pokemon Emerald. When I try to start it, it turns black for a few seconds and then I get back to the "select rom page".

**Comment by MikaXII** [comment]
Check this link, there is a trick to play pokemon game : 
http://blog.recalbox.com/forums/topic/gba-cant-make-pokemon-rubinsapphire-run/
