### ISSUE TITLE
Support for Wii Remote Controller

### ISSUE THREAD

**Issue by Niehztog** [digitalLumberjack/recalbox-os#442]
Since WiiU Pro controller works fine out of the box,
would it be possible to add support for the Wii Remote controller (pointing device) aswell?

Would be cool to use it as mouse cursor to play for example scummvm games.

**Comment by rockaddicted** [comment]
Hello, an issue is already open about that. So I close this one.

https://github.com/digitalLumberjack/recalbox-os/issues/13
