### ISSUE TITLE
N64 Emulator Problems w/ controller

### ISSUE THREAD

**Issue by Kinghoff** [digitalLumberjack/recalbox-os#444]
Hey,
I did all the editing things to make N64 games run on the Recalbox OS, like changing the video plugin to rice and editing that one config file (change value from 3 to 2 or whatever) :) Now the games start and don't quit to menu, but I can't use my controller. (just watching Mario making faces sucks :D) In all other emulators it works just fine but it doesn't do anything when I start N64 games. Except for the Hotkey, which gets me back to the menu. I'd be so thankful for a solution, N64 emulation was one of my main reasons to get an RPi2 :)
Greets

**Comment by rockaddicted** [comment]
look this post please : http://blog.recalbox.com/forums/topic/n64-controls-dont-work/#post-13640

**Comment by rockaddicted** [comment]
I close this issue. Every informations to solve this problem is in my post above.
If you still encounter problems, you can reopen this ticket.
