### ISSUE TITLE
pb joystick Atari2600

### ISSUE THREAD

**Issue by Blackorchid666** [digitalLumberjack/recalbox-os#448]
Bonjour,

Sur l'emulateur de l'Atari 2600 il m'est impossible de faire fonctionner le 2ème Joystick, or cela fonctionne très bien pour tout le reste des émulateurs. Il semble bien détecté, la conf retroarch semble OK, je ne vois pas bien comment m'en sortir. Un problème directement lié à Stella?

Quelqu'un a t il déjà réussi à faire fonctionner cela?

**Comment by Laddyacris** [comment]
Bonjour
avez-vous tester sous la version 3.3.0 beta ? attention il est obigatoire de faire une installation fraîche.

**Comment by Blackorchid666** [comment]
Merci pour votre réponse je vais essayer cela de ce pas, et je vous dis si il y a du mieux.

**Comment by Blackorchid666** [comment]
Malheureusement cela n'a rien changé. Cela dit le changement de version vaut vraiment le coup quand même. En grattant un peu sur le Net J'ai trouvé un fix pour retro PIE, mais comme je ne sais pas trop comment est monté l'OS sur la recalbox je me demande bien comment l'intégrer sur cette plateforme. En effet je ne connais pas bien les arbirescence de fichiers pour y placer les éventuelles MAJ et l'outil git ne semble pas installé (pas de apt, aptitude, pacman yum ou autre pour installer à priori). Donc si jamais cela semble causer à quelqu'un ceci semble fonctionner sous retro pie:


git clone https://github.com/libretro/stella-libretro.git
cd stella-libretro
make
cd /opt/retropie/libretrocores/lr-stella
sudo cp stella_libretro.so stella_libretro.so.bak
sudo rm stella_libretro.so
sudo cp /home/pi/stella-libretro/stella_libretro.so stella_libretro.so



avec plusieurs cerveaux on va ptet y arriver :-)

**Comment by rockaddicted** [comment]
Dans la semaine je resterai un update du core et je reviendrai sur cette issue faire un feedback.

**Comment by Blackorchid666** [comment]
ok pas de pb, il ya une procédure quelque part pour updater les cores justement?

**Comment by rockaddicted** [comment]
Testé avec le dernier commit du core libretro-stella, et le multijoueur semble ok. (testé avec le jeu combat).
Le core devrait être présent dans la prochaine version beta.
Je ferme cette issue, si tu rencontres de nouveau des soucis n'hésites pas à la ré-ouvrir.
