### ISSUE TITLE
Fail at cloning buildroot repo in Windows (file names with colon)

### ISSUE THREAD

**Issue by steak3** [digitalLumberjack/recalbox-os#449]
Hello,
Is it possible to rename these files without the colons:
```
recalbox-buildroot/board/recalbox/fsoverlay/recalbox/configs/retroarch/4:3.cfg
recalbox-buildroot/board/recalbox/fsoverlay/recalbox/configs/retroarch/7:9.cfg
recalbox-buildroot/board/recalbox/fsoverlay/recalbox/configs/retroarch/8:7.cfg
```

 So we can clone the repo in Windows without bug. Windows doesn't accept ":" in the file names :/

**Comment by digitalLumberjack** [comment]
ok thoses files are not helpful anymore, i'll remove that

**Comment by steak3** [comment]
J'avais besoin de ce fix pour avancer, du coup je les ai supprimé (comme tu l'a suggéré) moi-même en avance, dans le pull (ci-dessus).
Si il y a un problème avec ça fais le moi savoir :hamster:
