### ISSUE TITLE
Excessively long reboot time in 3.3beta

### ISSUE THREAD

**Issue by nekomania** [digitalLumberjack/recalbox-os#450]
Currently I have about 10000 roms loaded in 32 systems, with all game data and covers scrapped on PC by following the wiki. The startup boot time is around 3 minutes, which I think is still acceptable.

But in the recent beta builds, it seems that the restart/shutdown routine was changed? In the GUI main menu if I press reboot the screen turns black, and it freezes there for about 3 minutes before the "rainbow square startup screen" comes up. This means I will have to wait for a total of 3+3=6 mins for a system to fully rebooted itself.

If I connect by SSH and type reboot, it does not have such kind of delay.

So here is my question, is there some way I can avoid the new reboot routine? By adding a "Quick reboot" option in the GUI? or some new switches in the recalbox.conf maybe?

**Comment by digitalLumberjack** [comment]
I'll add a splash screen when rebooting. I will not force the fill of es as it was the source of many issues before 3.3.0

**Comment by digitalLumberjack** [comment]
The splash screen should be operational in 3.3.0 beta 9, release soon
