### ISSUE TITLE
Zoid theme crash if too many systems are enabled

### ISSUE THREAD

**Issue by nekomania** [digitalLumberjack/recalbox-os#451]
Currently I have about 10000 roms loaded in 32 different systems, it works great with the default simplelight theme. But if I change to the zoid theme the screen will turns to all white and system crash. If I reduce the number of systems to around 24-25 it will works fine.

I am using a rpi2, I would like to know is there anyway to let me monitor the memory usage? Will changing the system/gpu memory allocation help? Should I reduce the size of the background jpg?

**Comment by rockaddicted** [comment]
Yep it is a known problem of emulationstation. ES bitmap the backgrounds and load informations in the vram. So only reduce size of the background (by downgrading the jpeg quality, for example) is not a solution.

When you activate too much systems... ES crash.
So the only ways to"resolve" this problem are : 
- activate less of systems in the same time
- resize the background's resolution

Actually, in the zoid theme, we resized the background from 1080p to 720p, to decrease the size avec each background in the vram. But if we go below 720, the text in the background become un readable...
So, I recommand you to use the default theme, simplelight, which use background in 480p and can accept more of activated systems in the same time.

So I close this issue =)
