### ISSUE TITLE
Impossible to type some special characters

### ISSUE THREAD

**Issue by aes92** [digitalLumberjack/recalbox-os#461]
I'm trying to set up my WiFi SSID but it has a "_" on it and it's impossible to type it. I've tried several keyboards.

**Comment by rockaddicted** [comment]
Yes indeed, it is a known problem and an issue i already opened.
https://github.com/digitalLumberjack/recalbox-os/issues/37

To configure you wifi, we recommand to use the recalbox.conf file. More informations here : 
https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf-%28EN%29
(old version, 3.2.x) https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf-3.2.x-%28EN%29

I close this issue, and we can continue to talk in the other issue.
