### ISSUE TITLE
add another MAME core with better compatibility

### ISSUE THREAD

**Issue by DarthNeo2** [digitalLumberjack/recalbox-os#463]
its possible to add the another core of mame with better compatibility? I see in another distribution cores like lr-mame2003 and lr-mame2010  wich have support to new romsets of mame. Thanks and sorry for my english.

**Comment by Laddyacris** [comment]
Hello
in test : http://blog.recalbox.com/forums/topic/mame2003-libretro/
https://github.com/digitalLumberjack/recalbox-os/issues/193

**Comment by rockaddicted** [comment]
Thanks Laddycris for the answer.
This should be added in the next release, 3.3.1.
So I close this issue. You can continue to talk about that in the links above (forum or other issue).
