### ISSUE TITLE
Tilting blackscreen on boot

### ISSUE THREAD

**Issue by bistule** [digitalLumberjack/recalbox-os#467]
Hi everybody,

I've installed the recalboxOS-v3.3.0-beta-9 on my Pi B+, the system install correctly, but at the second boot (after the installation), my screen is tilting and the system don't display anything... Same issue with the latest stable version.

My screen is an Iiyama ProLite E2207WS. 

I will try tomorrow on another screen...

**Comment by bistule** [comment]
work with my full HD Panasonic TV, but i don't know that doesn't with the other one... Probleme with resolution ?

**Comment by rockaddicted** [comment]
Your other screen is connected on DVI ?
Did you try this ? https://github.com/digitalLumberjack/recalbox-os/wiki/Connect-your-recalbox-to-a-DVI-screen-%28EN%29

**Comment by bistule** [comment]
Yes, my Iiyama is connected on DVI, i will try tomorrow ! thx !

**Comment by rockaddicted** [comment]
Did you try? Can I close this issue ?

**Comment by bistule** [comment]
yes, it works fine ! thx ;)

**Comment by rockaddicted** [comment]
nice
