### ISSUE TITLE
[Request] Add some libretro cores 

### ISSUE THREAD

**Issue by askotx** [digitalLumberjack/recalbox-os#470]
Add some extra cores will be nice, if that's not too much complicated, I'd like to request: **fceumm** -has palettes to select availables and 8 sprites limit option, also another handheld can be awesome too:  **mgba**, it runs great on older hardware like Wii and has great compatibility, I think this can be an alternative to gpsp

Hope you like this idea

**Comment by rockaddicted** [comment]
Mga is available on recalbox 3.3.0. You must edit your recalbox.conf file and add this line `gba.core=mgba` to activite it.
We didn't switch it by default because we need more feedback about perf on rpi1.

**Comment by askotx** [comment]
Thanks, I just have read that you add support for both emulators, I can close this invalid issue, thanks again!!
