### ISSUE TITLE
Fullscreen at Games

### ISSUE THREAD

**Issue by bogi1102** [digitalLumberjack/recalbox-os#484]
Fullscreen at Games

Hello Dear Community

Is there still the possibility of full screen mode when the play with install?

Main Menu and Kodi's all right.

Only playing the there is only a small screen

Have played with the conifg file but noticed no improvement.

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-os/wiki/Manual-(EN)#es-settings-games

Video ratio 16/9

**Comment by bogi1102** [comment]
I had expressed myself wrong.

And also had a flaw.

I meant at N64 games. Here's left and right even the bar.

For all other consoles (NES, SNES) I'm a light beam even though I have only up and down set on TV and Recalbox 16/9.

In what config file I put it for N64 define the image adjustment?

Mfg

**Comment by rockaddicted** [comment]
Hi @bogi1102 
So I'm not sure to understand your problem. You want to display N64 in 16/9 and not 4/3 ?

**Comment by bogi1102** [comment]
exactly I want to do

**Comment by rockaddicted** [comment]
Ok so, you need to update your recalbox in last beta version (14 when I'm writing this comment).
Once system update done, update your `recalbox.conf` file using `recalbox.conf.template` file, in the same folder, as template.
The N64 section has changed, and now we are using a new default video plugin `gliden64`.
Before update, don't forget to backup your `InputAutoCfg.ini` if you have a custom config inside.

**Comment by bogi1102** [comment]
I have read and V. 3.3.0 Beta 14
on my Recalbox.

I now understood not exactly know what to do with the recalbox.conf and recalbox.conf.template ???

Could you explain it to me again?

Thank-you

**Comment by rockaddicted** [comment]
Your recalbox.conf is not updated with the system but template yes. So you need to open the template and copy/paste info in your recalbox.conf file.

**Comment by bogi1102** [comment]
Thank you now I've got it.

Will test it after work today

**Comment by bogi1102** [comment]
Good Morning

So N64 works fine now. Also 16/9.

For all other consoles also. Only here is up and down even a black border.

**Comment by bogi1102** [comment]
If the settings are overwritten with the next update ??

File from the Racalbox.conf?

**Comment by digitalLumberjack** [comment]
Nope recalbox.conf is not updated. recalbox.conf.template is
