### ISSUE TITLE
Manage multiple usb controllers with same name in PIFBA

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#5]
Usb controllers are indexed via their name for piFBA, if two controllers have the same name, the order defined in the configuration will not be the one in piFBA.

**Comment by mgoulartBR** [comment]
http://www.freedesktop.org/software/systemd/man/udev.html

**Comment by digitalLumberjack** [comment]
I could be a solution.
Let's way a little, as retroarch fba core will replace pifba soon in RPi2, maybe it doesn't worth spending time on this one.

**Comment by digitalLumberjack** [comment]
As controllers with same names and guid are now given in the order to pifba, i cannot do better.
https://github.com/digitalLumberjack/recalbox-buildroot/commit/ae8c6a59c1a9ee32583078b67403ab94413cad4c

**Comment by digitalLumberjack** [comment]
I passed pifba to sdl2. So it's ok now.
