### ISSUE TITLE
No input after installation

### ISSUE THREAD

**Issue by Yamakaky** [digitalLumberjack/recalbox-os#53]
I just installed recalbox on my raspberry pi B. Installation went fine, but when I reboot to recalbox, I can't interact with it. I tried an USB keyboard and an USB gamepad, nothing works. Any idea ?

**Comment by digitalLumberjack** [comment]
Yeah that's blocking.
What is your usb keyboard, i'll check if it is supported.
You will need the keyboard to configure the gamepad.

**Comment by Yamakaky** [comment]
It's the A1243 wired apple keyboard. It works during installation and recovery mode.

**Comment by digitalLumberjack** [comment]
Ok someone has the same issue. Why did i think apple products would work
out of the box...

**Comment by Yamakaky** [comment]
XD
I don't think I have a non-apple keyboard at home, I will try tomorrow at my apartment.

**Comment by digitalLumberjack** [comment]
I'll try to add the support though.

**Comment by Yamakaky** [comment]
What will you do ? It's an USB keyboard, it should work OOB, no ?

**Comment by digitalLumberjack** [comment]
Nope i just realized that the apple hid support was not compiled with the kernel for the RPi1.
Added in next release.

**Comment by Yamakaky** [comment]
Oh, cool. When do you plan to release it ?

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/ab1b4ad3262b26e8c995c3c0999fe5951885064d

Maybe this weekend.

**Comment by Yamakaky** [comment]
Cool, thanks ! A reactive support !
