### ISSUE TITLE
Install error / tar: short read?

### ISSUE THREAD

**Issue by share4u** [digitalLumberjack/recalbox-os#57]
Hi, i can't install recalboxOS on my Raspberry Pi 2,

i get all the time the same error during the installation process.
What can i do?

Please help me

![img_4588](https://cloud.githubusercontent.com/assets/11243923/6426007/53433244-bf43-11e4-8b86-7d8e16aa5bd4.JPG)

**Comment by digitalLumberjack** [comment]
Hi,
What sd card are you using ?
Do you have an other sd card ?

**Comment by share4u** [comment]
Hi, i use this card:
Transcend microSDHC Card 16 GB, Speicherkarte / Class 10

https://www.alternate.de/Transcend/microSDHC-Card-16-GB-Speicherkarte/html/product/859976?event=search

**Comment by digitalLumberjack** [comment]
Is it trying to download the image ? Can you plug off ethernet and try ? Or plug in if it was not connected ?

**Comment by share4u** [comment]
No changes with or without internet connection. 
I have formatet the sd card with the tool and draged the files to thae card, i plug the card to the raspberry. I turn it on, click on install and then comes the error. i tryed it many times, i crashes during install process, every time on at a other percent. 10% or 60% or 90%. i cant make the installation to 100%.

**Comment by digitalLumberjack** [comment]
It may be a card compatibility issue. Can you try with an other card?

**Comment by share4u** [comment]
wich is the best for raspberry? sandisc? so i will buy an other..

**Comment by digitalLumberjack** [comment]
There is no rules, i have sandisk, samsung, lexxar that works well. All class 10

**Comment by share4u** [comment]
hi now its working from gosthand :) but i have a mistake at my controller and now my keyboard have the wrong keys
Is there a way to reset the keyboard keys ?

**Comment by share4u** [comment]
and i have a Original XBOX 360 Controller with The Microsoft USB Cable can you help me to add this?

**Comment by digitalLumberjack** [comment]
To reset keyboard keys : 
F4 to quit, ALT+F2 for prompt, "root" "recalboxroot" 
`rm /root/.emulationstation/es_input.cfg`and reboot

**Comment by share4u** [comment]
thank you, it works. do you have a idea, how i can use my original xbox360 wireless controller?
