### ISSUE TITLE
mame / hotkey with gpio controller not working in version 3.2.4

### ISSUE THREAD

**Issue by hstampfl** [digitalLumberjack/recalbox-os#59]
hi, i just recognized that in mame the hotkey with gpio controlleris is not working.
within nes the hotkey is working. I also remapped the controller and set input from default to GPIO Controller1, without any success.

**Comment by digitalLumberjack** [comment]
Yep the hotkey is changed to R1 on mame only if it is mapped to select. I did hat because you cannot use select to add coin in certain games if select is the hotkey : 
https://github.com/digitalLumberjack/recalbox-os/wiki/Manual-%28EN%29#b---special-commands

**Comment by hstampfl** [comment]
thank you, could be better descriped in the wiki
