### ISSUE TITLE
Add a proper changelog file

### ISSUE THREAD

**Issue by Yamakaky** [digitalLumberjack/recalbox-os#61]
http://keepachangelog.com/

**Comment by digitalLumberjack** [comment]
Nice

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/7806fe5aceafe81d8b97f1303aadbb6290f49ee5

**Comment by Yamakaky** [comment]
You should also remove the CHANGES file.
