### ISSUE TITLE
Wifi ssid with space and Uppercase character

### ISSUE THREAD

**Issue by leberrem** [digitalLumberjack/recalbox-os#62]
I found 2 little bug.

When You try to enter an ssid with uppercase you must use Caps Lock because Shit button doesn't perform.
The second is when you enter an ssid with space character, There is an error in the file /etc/wpa_supplicant/wpa_supplicant.conf. the first word is in "ssid" entry and the second in "psk" entry.

Thank you for your great job.

Mikaël

**Comment by digitalLumberjack** [comment]
Hi, thank you, the first bug is known and reported here : https://github.com/digitalLumberjack/recalbox-os/issues/37
The second bug will be corrected in next release
And the Shit button never perform on my keyboard :) ;D

**Comment by leberrem** [comment]
;-D
Thank you

**Comment by digitalLumberjack** [comment]
Second corrected by https://github.com/digitalLumberjack/recalbox-buildroot/commit/aac22ff5989069d2ab03a5eb972f2260745e28f7
I close this one.
