### ISSUE TITLE
Scrap vanishing

### ISSUE THREAD

**Issue by mentat-fr** [digitalLumberjack/recalbox-os#63]
Hello, 
first of all thanks for all your excellent work, it's a gem ^^

When I scrap game, alla work fine, but after reboot all my scrapped games vanished.
Need to do it again.

***

Tout d'abord merci beaucoup pour cet excellent projet et bravo pour ton travail.
Quand je lance le scrapping, pas de soucis mais après un redémarrage les infos et images ont disparus. A noter que j'ai passé sur certains jeux.

Merci !
F.

**Comment by digitalLumberjack** [comment]
Hello,
do you reboot with the menu entry (quit->reboot) ?

**Comment by mentat-fr** [comment]
Yes I did: 
Boot > Scrap > Select some games > OK, all the stuff appear in a new presentation.
Reboot > Old game menu is back and stuff vanished.

I didn't check the filesystem yet, I will soon for more details.

**Comment by mentat-fr** [comment]
Just bought the RPi2 and after a new fresh install with the same roms, scrapping seem to be working fine. After reboot scrap data is always present.
Thanks for support.
