### ISSUE TITLE
Samba: share the parent folder too

### ISSUE THREAD

**Issue by mentat-fr** [digitalLumberjack/recalbox-os#64]
Hi,

I haven't desktop manager on my *nix laptop with a graphical filemanager.
So when I mount smb folder from recalbox, I use cli and need to map every individual system folder (snes, nes, ...).
Can you please add the parent folder in the samba configuration, it will make my day :)
Thanks !

**Comment by digitalLumberjack** [comment]
Hi, although it must be a pain to mount each folder, i won't share the whole directory, as it could create accidents and unwanted delete and move. You could create a little script mounting all directories.

**Comment by mentat-fr** [comment]
Ok thanks, I understand the need and I'll write a script ;)
