### ISSUE TITLE
Add external HDD support for ROMS

### ISSUE THREAD

**Issue by Raulval82** [digitalLumberjack/recalbox-os#68]
Hi! Due to the lot of systems that you are adding to this great distro, will be very useful tu store the roms in an external USB. Only with few psx games my sd card is full.

Thank you in advance!

**Comment by Yamakaky** [comment]
Similar to #58

**Comment by Raulval82** [comment]
Maybe I missunderstanded sorry, but I don't want a full Recalbox installation in the Hdd, only the roms.

**Comment by Yamakaky** [comment]
Yeah, I said installation, but it can be only roms and films. Installation should be an option.

**Comment by skitoo** [comment]
:+1:

**Comment by Ranashenka** [comment]
Can i add, not just External HDD but from a NAS also? If it already possible you can delete my post :)

**Comment by nickdj** [comment]
After transferring my Final Fantasy 7 and 9 ROMs onto my memory card it's full.  I'm mostly playing PSX games and would like to be able to store the ROMs on my NAS or an external USB drive.  Is there a way of achieving this?
