### ISSUE TITLE
edimax ew-7811un | problem with sleepmode

### ISSUE THREAD

**Issue by hstampfl** [digitalLumberjack/recalbox-os#70]
Hi the wlan dongle edimax ew-7811un has a well know sleepmode issue. 

following I have added manually to solve this problem.

add following line to the file /etc/modprobe.d/8192cu.conf:
options 8192cu rtw_power_mgnt=0 rtw_enusbss=0

Here the LInk I found for this solution (it's in german, sorry): 
http://developer-blog.net/hardware/raspberry-pi-problem-mit-wlan-stick-edimax-ew-7811un/
PS: the cronjob stuff is not needed.

**Comment by digitalLumberjack** [comment]
I'll add the module configuration in the next release.

**Comment by digitalLumberjack** [comment]
Hoping that will not break other dongle compatibility, but it's just power management it should be good.
https://github.com/digitalLumberjack/recalbox-buildroot/commit/a85b99ce76600a0f11c5d63ae40786db383be89f
