### ISSUE TITLE
Support to db9_gpio_rpi

### ISSUE THREAD

**Issue by mgoulartBR** [digitalLumberjack/recalbox-os#72]
I would like to ask for db9_gpio_rpi. It maybe be activated on Input Setting through a option "Choose GPIO model" - DB9 or MK Arcade.

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/0b4ecd9e63a27404d877a8d7cc5c6ab0e479db55
https://github.com/digitalLumberjack/recalbox-buildroot/commit/3017148469bc2deb27a8418c14f20def8a42a7ba
https://github.com/digitalLumberjack/recalbox-buildroot/commit/c6131387df4444ebafa28e826629c5900dae7484

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf

**Comment by digitalLumberjack** [comment]
In 3.2.5
