### ISSUE TITLE
Add option to choose the main application

### ISSUE THREAD

**Issue by fufroma** [digitalLumberjack/recalbox-os#73]
Cf http://blog.recalbox.com/forums/topic/une-petite-suggestion/

Enhancement : add an option to choose the main application launched on boot : Kodi or Recalbox

(I saw the topic, so I thought it may be a good idea to create the issue :o) )

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/c6131387df4444ebafa28e826629c5900dae7484
