### ISSUE TITLE
Favorite roms list

### ISSUE THREAD

**Issue by skitoo** [digitalLumberjack/recalbox-os#75]
Give the possibility to add rom into a favorite list.
One list by console.

**Comment by digitalLumberjack** [comment]
favorite added with https://github.com/digitalLumberjack/recalbox-emulationstation/commit/61eafba14a145a89597207da64eac54f245a1f59 from the pr of @kaptainkia https://github.com/Aloshi/EmulationStation/pull/393 and @remeh https://github.com/Aloshi/EmulationStation/pull/344

**Comment by digitalLumberjack** [comment]
- Voir le soucis du symbole non visible en utf-8 quand on définis un jeu en favoris via Y
- Traduire le help dans les autres langues
- Afficher dans le help même en mode basic pour ceux qui n'ont pas de gamelist mais qui souhaitent utiliser les favoris tout de même.
- Au reboot du raspberry, les favoris ne sont pas concervés et nous devons à nouveau les selectionner. Surement un soucis d'enregistrement en dur... :s

**Comment by Laddyacris** [comment]
Bonjour
si on choisit de mettre des jeux en favoris puis de se rendre via hotkey vers un choix par ordre alphabétique dans la liste de jeux, aux dessus de 2 jeux en favoris , le choix va se rendre dans la liste des favoris qui possèdent une étoile au lieu de la liste des jeux sans étoiles.
Pour aller selectionner d autres jeux on est obligé de passer par les dpads et descendre dans la liste.

**Comment by lordtaki** [comment]
Adding and removing favorites works well with 3.3.0 beta 1.
Tested with several systems.

**Comment by DsChAeK** [comment]
I think maybe I have lost my favorites once after I set it up before scraping and after that they got renamed and were not in my list anymore...possible?

**Comment by digitalLumberjack** [comment]
Maybe the scrapper doesn't save the favourite back in the xml metadata...
