### ISSUE TITLE
Suppression des faux roms contenant « ._ » 

### ISSUE THREAD

**Issue by profelec** [digitalLumberjack/recalbox-os#79]
Dans le menu, avoir la possibilité de lancer un script qui efface touts les fichiers avec le "._" devant nom dans chaque répertoire des émulateurs.

find . -name "._*" -exec rm -rf {} \;

**Comment by digitalLumberjack** [comment]
Ce problème n'arrive que pour les utilisateurs de macosx. Je pense plutot ne pas afficher les fichiers cachés, qui sont les fichiers commençants par un . dans linux. Ca reglera le problème d'affichage dans emulationstation, mais tu devra toujours utiliser la commande magique.

**Comment by Nikkau** [comment]
Juste les cacher n'aura pas d'effets de bord?

Par exemple le scrapper les considère comme des ROMs à part entière, les cacher va l'empêcher de faire ça?

Accesoirement, il y a un inconvénient à ajouter cette commande dans le script de démarrage ou ne pas le faire est un choix "philosophique"?

**Comment by digitalLumberjack** [comment]
Non tu peux le faire sans soucis, je te conseille de copier un des scripts de démarrrage dans /etc/init.d, et de le renommer S23removemacosxshit pour qu'il nettoie les fichiers avant le démarrage de emulationstation.

**Comment by profelec** [comment]
je tape qu'une seul fois ce script :
find / -name "._*" -print -exec rm -rf {} \;
Il cherche tout seul dans tout le syteme (et donc dans tout les dossiers de tous les emulateurs).

Est ce qu'il y a un risque de supprimer par mégarde des choses importantes a recalboxOs où il n'y a que les fichiers appel qui commence comme ça ?
