### ISSUE TITLE
Add shaders to retroarch

### ISSUE THREAD

**Issue by SeeDborg** [digitalLumberjack/recalbox-os#80]
I tried to, but I failed every time.
I know lots of shaders are working good in Retropie, which uses the same frontend.

Maybe it would be possible to do it in a future update ?

**Comment by ga01244** [comment]
Oui très bon idée

**Comment by reivaax** [comment]
Feedback in alpha 3.3.0 mika 5 with official driver and official dualshock 3 in bluetooth with pi2 :
The individual load of shader .glsl work great with recalbox.config.

The .glslp shaders doesn't work.

**Comment by hstampfl** [comment]
are the directories inside this glslp correct?

**Comment by reivaax** [comment]
yes he is good but if you have one  glslp recommandation and you want i try it, it's good :)

**Comment by Cissoubaka** [comment]
like reivax only the .glsl working, we need also to configure the path in the retroarch config file.

**Comment by lordtaki** [comment]
By editing /recalbox/share/system/recalbox.conf works well.
