### ISSUE TITLE
Switch SNES emulator to snes9x-next

### ISSUE THREAD

**Issue by Energizing** [digitalLumberjack/recalbox-os#85]
it fixes all the multiplayer problems and more game compatibility

**Comment by digitalLumberjack** [comment]
That could be good but last time i tried snes9x-next on rpi1, it was horribly laggy...

**Comment by Energizing** [comment]
works fine on my rpi2 but i only tried super mario all stars

**Comment by digitalLumberjack** [comment]
Yes maybe we should test it on rpi2 and configure it only on rpi2 if all gams are ok.

**Comment by Energizing** [comment]
+ retroarch compatibility so that's nice

**Comment by digitalLumberjack** [comment]
The thing is that pocket snes or catsfc are really optimised for arm processors. I need to see if the snes9x-next libretro core is good enough

**Comment by Energizing** [comment]
np, or you could put both and let people choose where they want to put their roms, either in snes folder (default pocketsnes) or snes9x-next folder

**Comment by digitalLumberjack** [comment]
That could be good but that is what i want to avoid. recalboxOS must be
really simple to use for unskilled people. I you have  more thant 1
emulator per platform many people will be lost. What i can do i maybe add
the possibility to switch the retroarch core in the new recalbox.conf file.

**Comment by Energizing** [comment]
anyway maybe you're going to find it great and just replace pocketsnes ;)

**Comment by digitalLumberjack** [comment]
I hope ;)

**Comment by digitalLumberjack** [comment]
I close this one as user now have the choice in recalbox.conf
