### ISSUE TITLE
Xbox 360 wifi controller never connect to receptor

### ISSUE THREAD

**Issue by qdelettre** [digitalLumberjack/recalbox-os#86]
Hi,

Just tried to connect a new gamepad (xbox360 wifi controller for pc), the gamepad never connect to the receptor.

Works fine on a computer running windows.

**Comment by Energizing** [comment]
it will always be blinking until we get the xboxdrv, but that doesnt mean it's not working, works fine for me, you set it up in the options and you're good to go

**Comment by qdelettre** [comment]
Thx
