### ISSUE TITLE
add Mednafen VB

### ISSUE THREAD

**Issue by RomainOdeval** [digitalLumberjack/recalbox-os#87]
Hello.

First, great job. Your OS is just amazing !
No lag, lot of improvments, WiFi, Bluetooth ... very impressive !

A little enhancement : is it possible to add Mednafen VB (Virtual Boy emulator) ?
Such a great and stupid console ... must be in your project :D 
http://mednafen.sourceforge.net/documentation/vb.html

I said "Mednafen VB" because i saw it can used with libretro and the other emulators were Windows only :/ But, if you found another one, it's ok !

Thanks !

**Comment by digitalLumberjack** [comment]
Good idea.

**Comment by digitalLumberjack** [comment]
OMG MY EEEEYEEEES !

**Comment by RomainOdeval** [comment]
Yes !!!! 3D screens with 5 shades of red !!! Worst console evar ..... LOVE IT ! xD

**Comment by RomainOdeval** [comment]
FYI, you can found here some homebrew games, if you want to add a "free game".
Be careful, some used licenced things (Mario, ...).

http://www.planetvb.com/modules/games/?hfsd

**Comment by digitalLumberjack** [comment]
I'll check that !

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/3ecfb2636dee2b86fdcc9f8c25469a50ea89317d
