### ISSUE TITLE
Ajout extension v64 sur N64

### ISSUE THREAD

**Issue by ga01244** [digitalLumberjack/recalbox-os#88]

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-os/issues/31

**Comment by hstampfl** [comment]
he asked about .v64 and V64. This extension is not in. you've added at #31 the z64 extension, haven't you?

**Comment by digitalLumberjack** [comment]
Hi, sorry i just woke up :)

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/c68f75e36907a896a6964ec9ff73a8e657041e72
