### ISSUE TITLE
needed : es_input.cfg for XBOX360 wired controller

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#89]
Hi all, i would need your es_input.cfg with fully configurated xbox 360 controller.
I know there is an issue with L2, the trick is to go up with the keyboard in order to redo the affectation of missed buttons. 

It would help a lot of people ;)

**Comment by hstampfl** [comment]
here you are

# cat es_input.cfg
<?xml version="1.0"?>
<inputList>
        <inputConfig type="keyboard" deviceName="Keyboard" deviceGUID="-1">
                <input name="a" type="key" id="115" value="1" />
                <input name="b" type="key" id="97" value="1" />
                <input name="down" type="key" id="1073741905" value="1" />
                <input name="left" type="key" id="1073741904" value="1" />
                <input name="pagedown" type="key" id="1073741902" value="1" />
                <input name="pageup" type="key" id="1073741899" value="1" />
                <input name="right" type="key" id="1073741903" value="1" />
                <input name="select" type="key" id="32" value="1" />
                <input name="start" type="key" id="13" value="1" />
                <input name="up" type="key" id="1073741906" value="1" />
        </inputConfig>
        <inputConfig type="joystick" deviceName="PLAYSTATION(R)3 Controller (00:8B:F0:FA:63:25)" deviceGUID="060000004c0500006802000000010000">
                <input name="a" type="button" id="13" value="1" />
                <input name="b" type="button" id="14" value="1" />
                <input name="down" type="button" id="6" value="1" />
                <input name="hotkey" type="button" id="16" value="1" />
                <input name="joystickleft" type="axis" id="0" value="-1" />
                <input name="joystickup" type="axis" id="1" value="-1" />
                <input name="l2" type="button" id="8" value="1" />
                <input name="left" type="button" id="7" value="1" />
                <input name="pagedown" type="button" id="11" value="1" />
                <input name="pageup" type="button" id="10" value="1" />
                <input name="r2" type="button" id="9" value="1" />
                <input name="right" type="button" id="5" value="1" />
                <input name="select" type="button" id="0" value="1" />
                <input name="start" type="button" id="3" value="1" />
                <input name="up" type="button" id="4" value="1" />
                <input name="x" type="button" id="12" value="1" />
                <input name="y" type="button" id="15" value="1" />
        </inputConfig>
        <inputConfig type="joystick" deviceName="Microsoft X-Box 360 pad" deviceGUID="030000005e0400008e02000010010000">
                <input name="a" type="button" id="0" value="1" />
                <input name="b" type="button" id="1" value="1" />
                <input name="down" type="hat" id="0" value="4" />
                <input name="hotkey" type="button" id="8" value="1" />
                <input name="left" type="hat" id="0" value="8" />
                <input name="pagedown" type="button" id="5" value="1" />
                <input name="pageup" type="button" id="4" value="1" />
                <input name="right" type="hat" id="0" value="2" />
                <input name="select" type="button" id="6" value="1" />
                <input name="start" type="button" id="7" value="1" />
                <input name="up" type="hat" id="0" value="1" />
                <input name="x" type="button" id="2" value="1" />
                <input name="y" type="button" id="3" value="1" />
        </inputConfig>
        <inputConfig type="joystick" deviceName="GPIO Controller 1" deviceGUID="15000000010000000100000000010000">
                <input name="a" type="button" id="1" value="1" />
                <input name="b" type="button" id="0" value="1" />
                <input name="hotkey" type="button" id="6" value="1" />
                <input name="pagedown" type="button" id="5" value="1" />
                <input name="pageup" type="button" id="4" value="1" />
                <input name="select" type="button" id="6" value="1" />
                <input name="start" type="button" id="7" value="1" />
                <input name="x" type="button" id="2" value="1" />
                <input name="y" type="button" id="3" value="1" />
                <input name="down" type="axis" id="1" value="1" />
                <input name="left" type="axis" id="0" value="-1" />
                <input name="right" type="axis" id="0" value="1" />
                <input name="up" type="axis" id="1" value="-1" />
        </inputConfig>
        <inputConfig type="joystick" deviceName="GPIO Controller 2" deviceGUID="15000000010000000200000000010000">
                <input name="a" type="button" id="1" value="1" />
                <input name="b" type="button" id="0" value="1" />
                <input name="hotkey" type="button" id="6" value="1" />
                <input name="pagedown" type="button" id="5" value="1" />
                <input name="pageup" type="button" id="4" value="1" />
                <input name="select" type="button" id="6" value="1" />
                <input name="start" type="button" id="7" value="1" />
                <input name="x" type="button" id="2" value="1" />
                <input name="y" type="button" id="3" value="1" />
                <input name="down" type="axis" id="1" value="1" />
                <input name="left" type="axis" id="0" value="-1" />
                <input name="right" type="axis" id="0" value="1" />
                <input name="up" type="axis" id="1" value="-1" />
        </inputConfig>
        <inputConfig type="joystick" deviceName="Xbox 360 Wireless Receiver" deviceGUID="030000005e0400001907000000010000">
                <input name="a" type="button" id="0" value="1" />
                <input name="b" type="button" id="1" value="1" />
                <input name="down" type="button" id="14" value="1" />
                <input name="hotkey" type="button" id="6" value="1" />
                <input name="joystickleft" type="axis" id="0" value="-1" />
                <input name="joystickup" type="axis" id="1" value="-1" />
                <input name="l2" type="axis" id="2" value="1" />
                <input name="left" type="button" id="11" value="1" />
                <input name="pagedown" type="button" id="5" value="1" />
                <input name="pageup" type="button" id="4" value="1" />
                <input name="r2" type="axis" id="5" value="1" />
                <input name="right" type="button" id="12" value="1" />
                <input name="select" type="button" id="6" value="1" />
                <input name="start" type="button" id="7" value="1" />
                <input name="up" type="button" id="13" value="1" />
                <input name="x" type="button" id="2" value="1" />
                <input name="y" type="button" id="3" value="1" />
        </inputConfig>
</inputList>

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/4ac0066ff5e5d8de91f0ff72820ad5d9b6ab6aa4
thanks heinz

**Comment by digitalLumberjack** [comment]
Someone ?

**Comment by iMaster29** [comment]
Here is my es_input.cfg with XBOX360 wired controller: http://pastebin.com/ZwEC9652

**Comment by digitalLumberjack** [comment]
I just saw that imaster, you used the snes style config ?
Y X
B A

**Comment by iMaster29** [comment]
Yes, I think so.

**Comment by Cissoubaka** [comment]
http://pastebin.com/QzB4MyWX
Voila je pense que c'est ce que tu veux!

**Comment by spriggan59** [comment]
http://pastebin.com/6eUJYZ8B

3.3.3 pasnox 7

**Comment by digitalLumberjack** [comment]
We got that already @rockaddicted ?

**Comment by rockaddicted** [comment]
@digitalLumberjack yes I added it with xboxdrv activated and desactivated.
