### ISSUE TITLE
Xbox 360 wifi controllers still blinking with xboxdrv

### ISSUE THREAD

**Issue by Energizing** [digitalLumberjack/recalbox-os#94]
did you delete the old drivers? xboxdrv should stop the blinking

**Comment by rockaddicted** [comment]
If you are using the last recalbox version, v3.2.5, you can try to start xboxdrv by this command : 

xboxdrv --detach-kernel-driver --trigger-as-button --wid 0 --led 2 --deadzone 4000 --silent & sleep 1

This command is for the controller player 1, will fix the led on the first position and your trigger R2/L2 should be seen as simple buttons.

**Comment by Energizing** [comment]
well now it's fixed on player one but not responding on recalbox ahah

**Comment by rockaddicted** [comment]
you need to do a new mapping of your controller in the emulationstation frontend.

**Comment by Energizing** [comment]
oh ok, i figured i could fix it with a little googling but would be nice to set it as default so people don't have to do it!

**Comment by rockaddicted** [comment]
You must start this command after each reboot. If you don't want to do this, you can create a script in the directory /etc/init.d/ to run the command with the recalbox start.

**Comment by digitalLumberjack** [comment]
You cannot imagine how hard it is to set things by default... For example
here, if i use xboxdrv by default, it will take a joystick slot, even if no
joystick is connected. xboxdrv will then try to connect to dualshocks(
because it supports it) that are normally managed by sixad. It will screw
it all.
I'm thinking of a way to manage the use of xboxdrv through recalbox.conf.
Like usexboxdrv=1
xboxdrv_reserved_slots=2
for 2 joysticks.

What do you think @rockaddicted

**Comment by Energizing** [comment]
maybe you can check in retropie files to see how they set it

**Comment by rockaddicted** [comment]
Yes I was thinking about that too. Using recalbox.conf to activate a script that would execute xboxdrv might be a good idea. The people activate the option only if they use xbox360 controllers. This way, xboxdrv will not interfere with the other controllers integrated in the driver's support.

**Comment by Energizing** [comment]
maybe there's something useful here? 

https://github.com/petrockblog/RetroPie-Setup/wiki/Setting-up-the-XBox360-controller

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-buildroot/commit/6b61b7fda9b9f2d4511224ff72c7f2f847268283

**Comment by digitalLumberjack** [comment]
xboxdrv can be configured in recalbox.conf in 2.3.8

**Comment by digitalcohesion** [comment]
So was there a fix for this issue? I'm having the same thing in 3.2.11. I enabled the xboxdrv in the conf file, but I have to run the command manually for the led to work.
