### ISSUE TITLE
can't play 1 player NeoGeo with X360 wireless

### ISSUE THREAD

**Issue by Energizing** [digitalLumberjack/recalbox-os#95]
when i launch a NeoGeo game (metal slug 1 + 2 + probably more) i press start on the game menu and it launches 2 player mode, and even if i only have 1 controller on... + i play as the second player...

**Comment by digitalLumberjack** [comment]
I hate those controllers.

**Comment by Energizing** [comment]
ahahahah, me too... but it's all i got for now, can't get playstation controllers until i move out to canada or i'll be overloaded to take the plane!

**Comment by hstampfl** [comment]
@Energizing Do you use the xpad or the xboxdrv?

**Comment by Energizing** [comment]
i'd like to try with this:

xboxdrv --detach-kernel-driver --trigger-as-button --wid 0 --led 2 --deadzone 4000 --silent & sleep 1

but the controls don't work when i launch the game... probably because of the crash i always get after leaving the controller settings from the frontend!

**Comment by Energizing** [comment]
ok so i tried to launch xboxdrv while i was in RetroArch's Input settings for user 1 to change controls from there, and it all changes to keyboard buttons instantly, and i can't edit it

**Comment by hstampfl** [comment]
I can send you my es_config.cfg to verify if the mapping generally would work

**Comment by Energizing** [comment]
my bad, didn't plug the keyboard in today... i can change it now xD

im trying neogeo back with xboxdrv on

**Comment by hstampfl** [comment]
@digitalLumberjack: It's a microsoft device, it's normal ;)

**Comment by Energizing** [comment]
well looks like it doesnt take my new retroarch controlls... must have done something wrong

**Comment by digitalLumberjack** [comment]
retroarch controls are overwritten at each game launch because of the control configuration mechanism of recalbox.

**Comment by digitalLumberjack** [comment]
You are talking about neo geo games. In what emulator ?

**Comment by Energizing** [comment]
in FBA, but can't access to FBA menu so i tried to do it from another emulator but in retroarch's menu

**Comment by Energizing** [comment]
no retroarch core for fba i guess? gotta do it from fba2x.cfg?

**Comment by digitalLumberjack** [comment]
Could you give me the following
`dmesg` line added when you plugin you usb dongle
`cat /proc/bus/input/devices`
`cat /root/generateconfig.log`
`cat /recalbox/configs/retroarch/retroarchcustom.cfg`

**Comment by digitalLumberjack** [comment]
and ` cat /recalbox/configs/fba/fba2x.cfg`

**Comment by Energizing** [comment]
[  185.858749] input: Xbox 360 Wireless Receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.5/1-1.5:1.0/input/input7
[  185.861005] input: Xbox 360 Wireless Receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.5/1-1.5:1.2/input/input8
[  185.863382] input: Xbox 360 Wireless Receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.5/1-1.5:1.4/input/input9
[  185.865083] input: Xbox 360 Wireless Receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.5/1-1.5:1.6/input/input10

when i plug my dongle, let me get the other files i'll mail them to you

**Comment by Energizing** [comment]
(sent it an hour ago)

**Comment by digitalLumberjack** [comment]
corrected with xbox drv
