### ISSUE TITLE
Missing french translation of scraper's interface

### ISSUE THREAD

**Issue by dem1980** [digitalLumberjack/recalbox-os#96]
When we scap a game, in the bottom of the screen, some texts are not translated.
For example : 
(A) STOP (PROGRESS SAVED) => not translated (quand on est sur le bouton STOP)
+ NAVIGUER => ok
(A) PASSER => ok
(A) SEARCH => not translated (quand on est sur le bouton EDITER)
x GAMES SUCCESSFUL SCRAPED => not translated (quand on a fini)

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-emulationstation/commit/b912be43e8d164e4a2105558bbd3eb7eb6189847
