### ISSUE TITLE
Ability to show current network status in network settings

### ISSUE THREAD

**Issue by nekomania** [digitalLumberjack/recalbox-os#99]
Internet connection: Not connected / Ethernet / Wifi
Current IP Address: xxx.xxx.xxx.xxx

(optional information) Subnet, hardware mac address, signal strength, channel, etc?

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/recalbox-emulationstation/commit/9530429e7b104aff68ccb1afb1476877105f3d67 show ip address and connection status
